### ISSUE TITLE
open settingspanel when player click on item in Inventory.

### ISSUE THREAD

**Issue by Nawiks** [tastybento/askyblock#100]
Hi, I have create Inventory : 

    public void InventaireMenu(Player p){
		   
		   Inventory menu = Bukkit.createInventory(null, 18,"Menu SkyBlock");
		   p.playSound(p.getLocation(), Sound.CHEST_OPEN, 5, 5);
		   
		   ItemStack is = new ItemStack(Material.GRASS);
		   ItemMeta isMeta = is.getItemMeta();
		   isMeta.setDisplayName("§ePour retourner sur ton île");
		   is.setItemMeta(isMeta);

			menu.setItem(3, is);
			p.openInventory(menu);
			
			
    }

And I want that when the player clicks the slot 3  open the menu SettingPanels of the plugin askyblock.

@EventHandler       
     public void InventoryClickMenu(InventoryClickEvent e){

	 Player p = (Player) e.getWhoClicked();

                        
     if(!ChatColor.stripColor(e.getInventory().getName()).equalsIgnoreCase("Menu SkyBlock"))
      {
        return;
      }
        e.setCancelled(true);
       
      if(e.getCurrentItem() == null || e.getCurrentItem().getType() == Material.AIR || !e.getCurrentItem().hasItemMeta()){
        
        p.closeInventory(); 
        return;}
      
      if(e.getSlot() == 3){
    	  p.sendMessage("test");
    	  p.closeInventory();
    	  
    	  SettingsPanel panel = new SettingsPanel();
    	  panel.islandGuardPanel(p);
      }
     }

But there is nothing...
Can you help me ?
Thanks

**Comment by tastybento** [comment]
Are you writing a separate plugin?

Rather than directly call the method in ASkyBlock, you can issue a command as the player:

p.performCommand("island settings");

**Comment by Nawiks** [comment]
Oh yes sorry... Thanks you but I do not find wheree modifiy the names of the items which are in the various inventories (settingspanels etc..)

**Comment by tastybento** [comment]
You may not need to change the code!
The plugin is very customizable. Look at the yml files and just edit them how you like.
