### ISSUE TITLE
Incorrect equality

### ISSUE THREAD

**Issue by romanalexander** [tastybento/askyblock#102]
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/commands/Challenges.java#L1500

ItemStack can't equal Material

**Comment by romanalexander** [comment]
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/InventorySave.java#L57

Here too.

**Comment by tastybento** [comment]
Thanks! Fixed in new commits.
