### ISSUE TITLE
Add back button on panels if there is a control panel main menu

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#109]
http://dev.bukkit.org/bukkit-plugins/skyblock/#c944

**Comment by Steev93** [comment]
You still looking for help on this issue ?

**Comment by tastybento** [comment]
Yes, indeed. A pull request would be welcome. However, you may want to make sure you're using the latest branch (3.0.0)

**Comment by Steev93** [comment]
I thought I would add input on this matter of the custom GUI used in the plugin MyCommand.


`Example of use :

'example':
  command: /iconmenu
  type: ICON_MENU
  text:
  - 'POSITION:ITEM_NAME:ITEMDATA:COMMAND/MESSAGE:TITLE:DESCRIPTION;MULTILINES'
  iconmenu_title: '&cMyCommand &4ItemMenu'
  iconmenu_size: 27
  iconmenu_commands:
  - '0:GOLDEN_APPLE:0:/help:&2Help:&aOpen the help menu'
  - '1:COMPASS:0:/mycmd:Menu:MyCommand menu'
  - '9:EMERALD:0:/list:Player List:&bShow online players'
  - '10:WATCH:0:/time set 0:Day:Turn day'
  - '26:WOOL:11:%openiconmenu%/iconmenu2:Next Page:&cChange IconMenu Page;&a--------->'`

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#85
