### ISSUE TITLE
Drinking water enhancement

### ISSUE THREAD

**Issue by EnderSandman** [tastybento/askyblock#116]
Add a config option to specify if drinking water is harmfull or not. I want to use a plugin called Thirst and I cant unless I can disable harm from drinking water.

**Comment by tastybento** [comment]
I don't quite understand the request. Can you explain more?

**Comment by EnderSandman** [comment]
I would like it if there was a true/false option in the config file where I could specify if players were harmed by drinking water.

**Comment by tastybento** [comment]
Ok, understood.

**Comment by slkjoy** [comment]
I second this request, and besides disabling acid water drinking, to allow other drinks like curative potions for the Disease plugin. (see my recent request - sorry did not see this one prior to posting).

**Comment by tastybento** [comment]
I added a setting to config.yml to allow the switching off of acid bottles and buckets. Pre release is here and it will be in the next release: https://github.com/tastybento/acidisland/releases/tag/V2.9.9.1

You can see the setting here: https://github.com/tastybento/acidisland/blob/2.9.9.1/config.yml#L309
