### ISSUE TITLE
AllowSpawnBreakBlocks setting ignored for itemframes

### ISSUE THREAD

**Issue by Zachar543** [tastybento/askyblock#12]
If a player punches an Itemframe in spawn, even with spawn.allowbreakblocks set to true, the player is still told that the island is protected.

The event still gets cancelled [here](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/listeners/IslandGuard.java#L1119).

**Comment by tastybento** [comment]
Thanks. I fixed this in 2.8.9.
