### ISSUE TITLE
Schematic Problem

### ISSUE THREAD

**Issue by DirtyKDPlayer** [tastybento/askyblock#121]
Hello, my name is DirtyKDPlayer and I have a server network. I use your Skyblock Plugin. When I insert a Schematic, then spawn these 40 blocks higher. What could that be? Sry for my english, I'm from Germany .
Greets DirtyKDPlayer

Skype: tadeus081

**Comment by tastybento** [comment]
The schematic is pasted relative to the bedrock block. Check where that block is in the schematic.

**Comment by DirtyKDPlayer** [comment]
Here is my Problem: http://prntscr.com/8yj8df

**Comment by tastybento** [comment]
Put a block of bedrock 5 blocks under the tree. The island hight is set by the height of the top bedrock block.

**Comment by DirtyKDPlayer** [comment]
Thany youuuuu!!!!! 1 question... I will delete the "Island" Island. http://prntscr.com/8yv0v2

**Comment by tastybento** [comment]
You can call your schematic island.schematic and just overwrite the standard one, or call it something different and create a new section in config.yml. I recommend you do the first one unless you want to keep the standard island.
