### ISSUE TITLE
Worldedit commands lag terribly

### ISSUE THREAD

**Issue by Mace68** [tastybento/askyblock#123]
While totally alone in my ASkyBlock world (only two sparse islands so far) Worldedit commands affecting even less than 2000 blocks will lag terribly. If I Worldedit around 4000 blocks or more the server will boot me due to a timeout. ASkyBlock_nether and all other worlds are not affected.

Timings report of a ~1700 block worldedit:
http://timings.aikar.co/?url=13191973

**Comment by tastybento** [comment]
I looked at your timings but the Askyblock plugin isn't even listed as running. If WE is lagging, is it up to date for your server version? I.e. Does it give you any warnings win the console when you start the server?

**Comment by Mace68** [comment]
I've tried both the 6.1 releases and latest 6.1.1 snapshots of both worldedit and worldguard and none of those versions gave any warnings or errors. Is there another way to get timings that might be more informative?

**Comment by Mace68** [comment]
Just got a server error but ASkyBlock isn't mentioned anywhere in it (http://pastebin.com/PGpVc2jN). Maybe I need to contact sk89q? Can't figure out why it only does it in that one world though.

**Comment by Mace68** [comment]
Alright, new detail. It only happens on y=118 but worldedit isn't the issue. The server lag happens when placing blocks manually as well.

**Comment by tastybento** [comment]
The server crash log mentions WorldEdit - it appears there's a problem there. Can you remove ASkyBlock plugin from your server and see if you still see the same issues? I can't yet see the link between the problem your having and ASkyBlock except that you see the issue in the ASkyBlock world.

**Comment by Mace68** [comment]
Okay it's not the askyblock plugin or worldedit,it still does it with it disabled. Very strange, it lags on y=119 if i'm below 118 and it lags on y=118 if i'm above 119. Maybe I'll copy the islands and regenerate the world and see if it's the world generator.

**Comment by Mace68** [comment]
I made a fresh ASkyBlock world twice (deleted both the world and plugin config folders) and got the same lag/timeout both times. All of the other worlds behave as they should. Could it be the way the ASkyBlock world is being generated?

**Comment by tastybento** [comment]
I've no idea. How are you measuring lag? What are you doing? Using WE, or placing blocks some other way?
The world generator is only called when chunks are generated. And if the plugin is removed, there's nothing being called anyway, the world just is what it is. Of course, in this case it is all air, but I'm not sure why that'd be an issue.
In your timings, I see that Spigot's X-ray defeat is on - maybe switch that off or try CraftBucket and see if you still get lag? You could also try creating a world with sea in it (set in config.yml) and see if that changes anything. I'm just clutching at straws though!

**Comment by Mace68** [comment]
The server will pause for about 1 second every time a block is placed at the levels I mentioned above. If I use worldedit the amount of lag depends on how many blocks are being changed. The server will time out on less than 5000 blocks updated with worldedit, but it seems only if the affected blocks are at y118. Unfortunately adding a sea level and disabling x-ray had no effect. I'm at a loss as well lol.

**Comment by tastybento** [comment]
Just a basic question - what plugins are you running? Any?

**Comment by YellowZaki** [comment]
I experience fps lag when I place/destroy blocks that haven't got any blocks down (they are directly on the void). But I think that is a minecraft issue because it happened to me (and to everybody)  in other servers.

**Comment by Mace68** [comment]
Server version:
CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

The plugins I am currently running are:
WorldEdit 6.1
WorldGuard 6.1
Essentials TeamCity Build 12 from https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
EssentialsProtect TeamCity Build 12 from https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
EssentialsChat TeamCity Build 12 from https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
EssentialsAntiBuild TeamCity Build 12 from https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
EssentialsSpawn TeamCity Build 12 from https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
PerWorldPlugins 1.3.0
AdminControl 1.4
mcMMO 1.5.04-SNAPSHOT-b78
Vault 1.5.6-b49
bPermissions 2.10.9m
ASkyBlock 2.9.7.3
Greenhouses 2.4.5
PlayerVaults 3.5.7
Multiverse-Core 2.5-b710
Multiverse-Inventories 2.5-b398
Scavenger 1.6-63

**Comment by Mace68** [comment]
I've updated ASkyBlock to 2.9.7.4 but the problem still persists.

**Comment by Mace68** [comment]
I just noticed that the higher y level you're at the more worldedit lags, on all worlds. It just seemed like it was the skyblock world because you start higher to begin with. Discovering this I believe ASkyBlock is completely unrelated to this problem. Thanks a ton for your attention on this and sorry for the headache.

**Comment by tastybento** [comment]
Okay! Closed!
