### ISSUE TITLE
Island Spawn Rate

### ISSUE THREAD

**Issue by DirtyKDPlayer** [tastybento/askyblock#126]
Hey, i have a problem.

The Spawnrang is by 9 my players wrong.

See here:

![2015-11-16_20 16 52](https://cloud.githubusercontent.com/assets/15618464/11192078/3e0f8790-8c9f-11e5-8730-cb250d61c035.png)
![2015-11-16_20 16 54](https://cloud.githubusercontent.com/assets/15618464/11192079/3e1330e8-8c9f-11e5-8663-50308346eeaf.png)

**Comment by tastybento** [comment]
Sorry, I don't understand the problem. Can you say it in a different way. What are the screenshots showing?

**Comment by DirtyKDPlayer** [comment]
If a player is on its own island, the island is practically halved. In the middle of the island " he leaves the iland". His island radius does not come off the Bedrockblock 100 blocks in any direction, but 100 blocks left, back and front. I'm sorry for my english, I'm from Germany ...

**Comment by tastybento** [comment]
Haben Sie aus einem anderen Plugin konvertieren? Bitte tun Sie / asadmin info und teilen Sie das Ergebnis ein. Vielleicht die Inseln sind falsch Offset.
