### ISSUE TITLE
If you don't have permission to do '/island coop', a "command not found" message is sent rather than a permission error

### ISSUE THREAD

**Issue by Pokechu22** [tastybento/askyblock#129]
If a player does `/island coop` but does not have permission, the "Unknown command" message is sent rather than a "You don't have permission" message.  

This happens because [the if for checking for permissions](https://github.com/tastybento/askyblock/blob/37904a2314707c1e348fdb7b7f90839d02d649ac/src/com/wasteofplastic/askyblock/commands/IslandCmd.java#L2297) doesn't have a matching else if at the bottom.

**Comment by Poslovitch** [comment]
Fixed. Will come in a pull request as soon as possible.
