### ISSUE TITLE
Mavenize

### ISSUE THREAD

**Issue by drtshock** [tastybento/askyblock#13]
Hey! We use this plugin on my server and there is something I'd like to add and there will probably be more. I'm more than happy to at least open a PR for anything I add for my server as you guys are kind enough to keep your repo open <3 

To make contributing easier, mavenizing the project would be huge. I'd be happy to do it for you if I knew you are ok with it. If you have any questions on it just let me know!

**Comment by tastybento** [comment]
I looked at Maven and can't find a whole lot of value in it. The only dependencies of the code is on the Spigot API and Vault. I can't work out how to add those into the pom.xml - if you can do that, I'd be interested to see it. Also, I can't see how I can create a plugin jar with maven in eclipse. I must be missing the "make jar with maven" button somewhere - do you know how?

**Comment by drtshock** [comment]
You can just type `mvn clean package` into the command line to compile.
Vault can be added via the info in their readme https://github.com/MilkBowl/VaultAPI/blob/master/README.md

You can compile with Eclipse with maven package http://books.sonatype.com/m2eclipse-book/reference/running-sect-running-maven-builds.html
