### ISSUE TITLE
Problem with plugin

### ISSUE THREAD

**Issue by Lunora** [tastybento/askyblock#130]
27.11 21:06:45 [Server] INFO Using epoll channel type
27.11 21:06:46 [Server] ERROR Could not load 'plugins/acidisland.jar' in folder 'plugins'
27.11 21:06:46 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Vault
27.11 21:06:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot186.jar:git-Spigot-044d928-e8c6403]
27.11 21:06:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot186.jar:git-Spigot-044d928-e8c6403]
27.11 21:06:46 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot186.jar:git-Spigot-044d928-e8c6403]
27.11 21:06:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot186.jar:git-Spigot-044d928-e8c6403]
27.11 21:06:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

how to fix it?

**Comment by Lunora** [comment]
same thing with craftbukkit

**Comment by tastybento** [comment]
Download and install the bukkit Vault plugin. It is mandatory.

**Comment by Lunora** [comment]
Oh, that worked, thank you very much! 
But acid does not damage me at all sadly

**Comment by Lunora** [comment]
also not applies any effect on players

**Comment by Lunora** [comment]
Oh sorry i just realized what i did wrong, thanks again ^^

**Comment by tastybento** [comment]
Check your permissions. You and your players have likely been given acidisland.* permission. That should not be used except for admins. It includes the noburn permission.
