### ISSUE TITLE
Calculating island level

### ISSUE THREAD

**Issue by Nawiks** [tastybento/askyblock#136]
Hi how i can calculate island level of the player for use getIslandLevel(p.getuniqueId()) with ASkyBlock API ?
I want it for use in a sheduler.
Thanks !

**Comment by tastybento** [comment]
Not supported right now. I'll add it to the API.

**Comment by Nawiks** [comment]
Thanks !

**Comment by tastybento** [comment]
Added with 93092d7cf5b96d19cfab5fd4f1f54e4f34f4370b commit. Can you try the 2.9.8 branch and see if it works for you okay?

**Comment by Nawiks** [comment]
yes thanks, but how i can use : 
 public boolean calculateIslandLevel(UUID playerUUID) {
	if (plugin.getPlayers().inTeam(playerUUID) && !plugin.getPlayers().hasIsland(playerUUID)) {		
	    new LevelCalcByChunk(plugin, playerUUID, null, true);
	    return true;
	}
	return false;
  }
please ?

**Comment by tastybento** [comment]
Here's a gist of an example class: https://gist.github.com/tastybento/e81d2403c03f2fe26642

**Comment by tastybento** [comment]
Done.
