### ISSUE TITLE
Offline Explosion Toggle

### ISSUE THREAD

**Issue by drtshock** [tastybento/askyblock#14]
We have /fly as a perk for ranks on our server and people are going to other islands and putting creepers on there to blow stuff up and grief. Would be great if we could just disable explosions if all island members are offline similar to what factions allows you to do.

I'd be happy to add this and PR it if the project were mavenized (:

**Comment by tastybento** [comment]
So players can not only fly but have creeper eggs too? 

There are settings to prevent TNT and creeper explosion already. Do these not suffice?

I haven't had enough time to decide if I want to switch to Maven. I'll look into it.

**Comment by drtshock** [comment]
Honestly, not sure. The person that set up the server is currently away, I'll ask her when she's back tomorrow.
