### ISSUE TITLE
Error on 1.8.8

### ISSUE THREAD

**Issue by GeARCraft1** [tastybento/askyblock#141]
Hi, a was creating a server with ASkyBlock, and it was working fine when I received na error giving /island help on /is, so i searched the FAQ and i found the following error java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R1.NBTBase
So How Can i Solve it??

Thamk you, 
GeARCraft1 from http://craftygaming.me/

**Comment by tastybento** [comment]
The Minecraft server you are using is too old to run the plugin. You need to upgrade to at least 1.7.9.

**Comment by GeARCraft1** [comment]
I'm running with spigot 1.8.8, that's strange

**Comment by tastybento** [comment]
Can you share the console log? That'll point to where this is coming from.

**Comment by GeARCraft1** [comment]
Ok, I'll make a gist

**Comment by GeARCraft1** [comment]
The server log: https://gist.github.com/GeARCraft1/a8ac2f16ab006269ba5d

**Comment by tastybento** [comment]
One of your plugins, I'm not sure which has org.jnbt.* imported inside it and it's the old version. The only way to find out is to remove plugins one by one until you find out which it is. There may be an updated version of it.

**Comment by tastybento** [comment]
The plugin will have something to do with schematics in it.

**Comment by GeARCraft1** [comment]
Thank you, I checked all the plugins jar contents and it was InvMaster plugin.
