### ISSUE TITLE
Return copies of Lists in API

### ISSUE THREAD

**Issue by domisum** [tastybento/askyblock#144]
I am currently creating a plugin hooking into ASkyBlock. I used this code to get the players to display in a GUI menu. I didn't want the GUI to include some players, so I removed them from the list. 

```java
List<UUID> teamMemberUUIDs = ASkyBlockAPI.getInstance().getTeamMembers(player.getUniqueId());
teamMemberUUIDs.remove(somePlayersUUID);
```

When opening the GUI next time, the returned List didn't contain the previously removed players UUID anymore. This is caused by returning the real list in the API methods, not a copied one. I'd highly suggest changing that up so this cannot happen anymore.
Example:

```java
public class ASkyBlockAPI {
...
    public List<UUID> getTeamMembers(UUID playerUUID) {
	return new ArrayList<UUID>(plugin.getPlayers().getMembers(playerUUID));
    }
...
}
```

**Comment by tastybento** [comment]
Thanks for the tip. I've updated the API with those changes. Please try it and see if it works for you.

https://github.com/tastybento/askyblock/releases/tag/V2.9.8.1

**Comment by tastybento** [comment]
Fixed in latest.
