### ISSUE TITLE
POTENTIAL BUG Mobs despawning with nametags

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#146]
When I updated my 1.7 server to 1.8 I put some hostile mobs in the lobby world for decoration. These mobs despawned after some time. I tried naming them with name tags, summoning them with PersistenceRequired:1...
Today I realised that when I'm near to a mob, I leave the game and then I join again, the mob despawn. So I started to disable plugins one by one and I found that the plugin than was causing this is aSkyblock.
For me this is very important, please help.
PD: Only hostile mobs despawn doing the leave-join method although players have reported me that animals and villagers also despawn sometimes.
Thanks a lot.
Im using askyblock 2.9.7.3.

**Comment by YellowZaki** [comment]
I had:
loginremovemobs: true
I have turn it to false and now the problem doesnt occur. But  loginremovemobs should not remove mobs with nametags and PersistenceRequired:1. Also, it should not remove mobs in the lobby world.

**Comment by tastybento** [comment]
Thanks. This will be fixed in the next version.

**Comment by tastybento** [comment]
Fixed in latest.
