### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by CrayCrayBanaynay** [tastybento/askyblock#148]
Hi, I have turned on mob spawning (using /gamerule doMobSpawning true) and also set it to true on my server settings, but I can't get mobs to spawn on islands, even when I use spawn eggs.

**Comment by tastybento** [comment]
Is the world set as peaceful? It's probably another plugin preventing it - world guard, or essentials?

**Comment by CrayCrayBanaynay** [comment]
It is set on easy.  I have Essentials installed.  Mobs will spawn on other worlds on the server, but not acidisland.

**Comment by tastybento** [comment]
Do you have Multiverse installed? I can't help you unless you share some more information on your set up. What plugins do you have installed? What are the config files you've edited? What server are you running? etc. etc. It's a server setup issue.

**Comment by CrayCrayBanaynay** [comment]
I fixed it!  I disabled essentialsgroupmanager v2.0 :)  Thanks anyway.
Sorry, I'm very new to this server thing, just trying to create a safe place for my kids and their friends to play :)

**Comment by tastybento** [comment]
Okay, glad you got it working!
