### ISSUE TITLE
Different command

### ISSUE THREAD

**Issue by ArmyOps** [tastybento/askyblock#149]
I would like to use skyblock and acidisland, but doesnt it comes in problem if they both use command /island?
Somewhere was mentioned that i can use /ai or /ais, but is it configurable from config? and changes also help commands to /ais?

**Comment by tastybento** [comment]
If they are both running on the same server:

ASkyBlock uses /island, /asc and /asadmin
AcidIsland uses /ai, /aic and /acid

**Comment by Steev93** [comment]
just a thought for you Army if yu wanted to try something drifferent

I do suggest if you wish to use your own commands. Try "MyCommands" (http://dev.bukkit.org/bukkit-plugins/mycommand/)

Alias / Shortcuts commands: 
It's possible make an alias in 2 way. The first using the "ALIAS" Type,the second using the "RUN_COMMAND" command type. Example : 

'my_alias':
 command: /l
 type: ALIAS
 alias: /list
Or :

'my_alias':
 command: /l
 type: RUN_COMMAND
 runcmd:
 - /list
