### ISSUE TITLE
Inheritance Issue

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#151]
Now i am posting on behalf of another use, after i helped him bug test for almost an hour now, as see on the Spigot page.

The user is a boucanier rank

Issue states where under 4 ranks he has a perm node for each max size:

moucheur - askyblock.team.maxsize.4
artilleur - askyblock.team.maxsize.5
corsaire - askyblock.team.maxsize.6
boucanier - askyblock.team.maxsize.7

Now what has been done is given negative perms to each rank to see if it would work, example:
boucanier - askyblock.team.maxsize.7 -askyblock.team.maxsize.6 -askyblock.team.maxsize.5 askyblock.team.maxsize.4

then we decided to add it to the user's file as a single perm, "askyblock.team.maxsize.7" it worked, even with this in his ranking file boucanier - askyblock.team.maxsize.7 -askyblock.team.maxsize.6 -askyblock.team.maxsize.5 askyblock.team.maxsize.4

This did not work, so i decided to remove all "askyblock.team.maxsize.#" from all the group and just add "askyblock.team.maxsize.7" it works

His group manager files were transferred to myself and it was checked and rewritten, passed YMAL/YML checker and no console errors what so ever.

It seems that he cannot invite due to the previous Inheritance picking up that he is over his limit but he is not, as for now for until there is a fix he will have to apply some type of fix, but if you tastybento could look into this it would be greatly appreciated!

**Comment by tastybento** [comment]
Hi, I fixed this just now in e5702073012108d80e8bffad5f5f0b1f32fd4036 commit.

The largest maxsize value will be used if the player has multiple so you do not need to use negative permissions.

Here is the latest jar:
https://github.com/tastybento/askyblock/releases/tag/V2.9.8.1
