### ISSUE TITLE
top listings still dont work for op's

### ISSUE THREAD

**Issue by dahbawz** [tastybento/askyblock#157]
op's have the negative askyblock.excludetopten and askyblock.mod.excludetopten permission. still it won't show op's in the top 10

**Comment by Steev93** [comment]
Make sure it's a Negative if they are in a group ? and Single Perm ? have you tried both ?

**Comment by dahbawz** [comment]
both yes. doing /asadmin topten helped for the /is top command. But still op's are not in de holo top10. all op's have     - askyblock.admin.holoboard permission

**Comment by TWSSYesterday** [comment]
Try /island level, was supposed to fix for me but I ended up just doing a reinstall and it worked...

**Comment by dahbawz** [comment]
/island level works, we are showed in the top 10. but still not in de holographic.
besides that the holographic still has some bugs. Number 1 is a player with a level 7 island, number 2 is a player with an level 30 island and so on. Reload won't help.

**Comment by Steev93** [comment]
See what the refresh rate is like, sometimes it's at 30 mins, or something. I can come. Also your priorities in perms could be playing up with the perms ?

**Comment by tastybento** [comment]
I didn't write the holographic plugin so I can't help there.
