### ISSUE TITLE
Allow colours to be used in titles

### ISSUE THREAD

**Issue by TWSSYesterday** [tastybento/askyblock#159]
I'm unsure if it's a current feature and I'm doing it wrong or if it's not yet implemented.
It'd be nice to be able to change the title and subtitle colour. I'm using the latest version from Spigot and the locale.yml with the & colour codes.

**Comment by tastybento** [comment]
Ah, yes the colors are set. The only way to change them is to use the commands options in config.yml to issue your own titles.

**Comment by TWSSYesterday** [comment]
Would it be possible to have the colour option for titles/subtitles in the future directly in the locale?

**Comment by tastybento** [comment]
I'll add this to the next version of the game. You will need to use words like "gold", "blue" because the titles are set by JSON strings.

**Comment by TWSSYesterday** [comment]
Okay, sounds good.

**Comment by tastybento** [comment]
Done in V2.9.9

**Comment by TWSSYesterday** [comment]
<3
