### ISSUE TITLE
More Events

### ISSUE THREAD

**Issue by drtshock** [tastybento/askyblock#16]
Your plugin has some events, but could use some more. As well as a generic, abstract event that you can use as a base to reduce code duplication (just an ASkyblockEvent or something).

Events I'd like to see (can name however you want):
Island Start
* Player
* Schematic being used

Island Reset
* Player
* Old island info
* New island info

Island Join
* Island info
* Player

Island Leave
* Team info
* Player

Now, my terminology might be a bit off and if it is, I apologize. Spent a lot of time working with uSkyblock before saying fuck it and using this. Haven't had to do any of my own hacky fixes to have it running fine so I'm not familiar with the code base yet :)

Again, happy to do these myself if mavenized. Having this here to at least remind myself.

**Comment by roastnewt** [comment]
I would also like to see island join/leave events, to "cleanup" someone's stuff when they leave an island (private chests, homes, etc).

**Comment by tastybento** [comment]
I'd be open to pull requests for these.

**Comment by drtshock** [comment]
I made them in my own branch. I'm trying to catch it up now but the diffs are huge :c

**Comment by drtshock** [comment]
Caught it up only to see another 14k line addition :(

**Comment by tastybento** [comment]
Most of that is the jdbm package.

**Comment by tastybento** [comment]
See 2.9.3.4 for my implementation of these events. Feedback welcome on what they provide.
