### ISSUE TITLE
AcidIsland vs aSkyBlock commands

### ISSUE THREAD

**Issue by obiku19** [tastybento/askyblock#160]
Would it be possible to use completely different commands for both plugins?
Lets say
/ai /aisland for AcidIslands
/si /sisland for Skyblocks

And same for admin commands...
/aiadmin for AcidIsland
/siadmin for Skyblocks

With a multiverse server, using /is for both aSkyBlock and AcidIsland plugins is not working for me.

**Comment by tastybento** [comment]
They are completely different:

AcidIsland is /ai, /aic and /acid
ASkyBlock is /island, /c (or /asc) and /asadmin.

**Comment by obiku19** [comment]
Tasty,

Not entirely true, yes, the main command to get to your island in AcidIsland is /ai, but the alias is /is.... which on a Multiverse server with aSkyBlock plugin loaded too runs into trouble... sometimes /is brings me to an AcidIsland, sometimes to askyblock island...
