### ISSUE TITLE
Animal limit per island

### ISSUE THREAD

**Issue by blastic** [tastybento/askyblock#164]
Hi

I have a few issues with this plugin I wish you can help me resolve.
Can you please add a feature so that we can choose how many animals are allowed on each island.
I know there is already a setting for this "breedinglimit" but I mean I want to allow only 15 sheeps, 15 cows, 15 chickens and like 20 rabbits per island.
Also, all the animals on an island despawn when I have my multiverse settings to animal spawning false
and when I make it true there is all kinds of animals spawning on grass on islands. is there a way to disable natural spawning without the animals on islands despawning? 

I am using the latest version of the plugin today alongside spigot 1.8.8

Thanks!

**Comment by tastybento** [comment]
> when I make it true there is all kinds of animals spawning on grass on islands

What's the problem with that? 

> Is there a way to disable natural spawning without the animals on islands despawning?
Yes, in config.yml you can set the world spawn levels. Just set them to zero.

**Comment by blastic** [comment]
Yes but people make a layer of grass and they get horses and all animals really quick, the way I have done the challenges is that they can get all of these animals eggs so that they wouldnt have everything very fast. just making a bit harder and more interesting :p 

Thanks I don't know how I missed that option, im going to make animalspawnlimit to 0 and hopefully it works. 

Also is there a way to only allow a specific animal to naturally spawn? like if i want to make only rabbits to be able to spawn naturally can i do that with the plugin.

**Comment by blastic** [comment]
Btw are you going to be able to add the feature to choose how many  of each animal is allowed per island? just like the villager limit.

**Comment by tastybento** [comment]
The villager spawn limit function could be expanded to operate for every creature. It could add lag though because every time there was a spawn event the plugin would need to check the number. I'll add it to the list.

**Comment by blastic** [comment]
Ok thanks! can you let me know when you have updated the plugin with this feature.

**Comment by Poslovitch** [comment]
Please put it in 3.0.5 milestone. I will work on it ;)

**Comment by tastybento** [comment]
Let's move to 3.0.6 so we can release 3.0.5.

**Comment by Poslovitch** [comment]
To close ;)
