### ISSUE TITLE
vanilla nether voids

### ISSUE THREAD

**Issue by slkjoy** [tastybento/askyblock#168]
We are using the old vanilla nether with player claims. However, when a player resets their island, their claim in the nether gets deleted also - leaving a huge void (we have 200x200 protected areas, islands are 400 apart).

Is there a way to just remove the protection but not delete the blocks?

**Comment by tastybento** [comment]
What version of the plugin is doing this?

**Comment by tastybento** [comment]
I don't think this should happen with V2.9.9.

**Comment by slkjoy** [comment]
Yes, it was the version previous to 2.9.9. We notice that when we had the settings on for the custom nether (nether islands) - some players would spawn in a vanilla nether instead and never get a nether island. To address the inconsistency, I turned off the custom nether and deleted the nether worlds (both the world-nether and the acidisland-nether). Now, so far, player all go to a common nether, but there are no longer any claims in the nether. Which is suppose to be correct - nether without claims or with claims?

**Comment by tastybento** [comment]
With a common standard nether there are no claims. The area around the spawn portal is protected, but that's it.
