### ISSUE TITLE
Potion for Acid resistance

### ISSUE THREAD

**Issue by slkjoy** [tastybento/askyblock#172]
We would love to have some potion that can give temporary immunity to the acid. It would be even more useful if we can customize the recipe. Also would be good to have different strength levels - so one is only 1 minute, and a stronger can last 3 minutes, for example.

**Comment by tastybento** [comment]
The water breathing potion does this...

**Comment by tastybento** [comment]
Just to reiterate - water breathing potion gives acid immunity and there are two types with different lengths of protection.
