### ISSUE TITLE
Compatibility with Thirst & Disease plugin

### ISSUE THREAD

**Issue by slkjoy** [tastybento/askyblock#173]
We would like to use the Thirst & Disease plugins by Hmmcrunchy (https://www.spigotmc.org/resources/thirst.3316/) - but when players boil water, the water in the bottle is still Acid water and fatal to drink. Is there a way to allow players to boil water or distill it and allow them to drink it? Also, curative potions for diseases behave like acid water and kills players instead of healing them.

Another option is to allow water source blocks above sea level to no longer be acid and remain normal water when bottled. We are also open to an option to just disable acid water bottles and allow normal potions.

**Comment by tastybento** [comment]
I added a setting to config.yml to allow the switching off of acid bottles and buckets. There isn't a neat way to integrate with the requested plugin unless the two were written for each other. This is the simplest option. https://github.com/tastybento/acidisland/releases/tag/V2.9.9.1

You can see the setting here: https://github.com/tastybento/acidisland/blob/2.9.9.1/config.yml#L309
