### ISSUE TITLE
rewardcommands vs commands

### ISSUE THREAD

**Issue by slkjoy** [tastybento/askyblock#174]
I can't seem to get either rewardcommands: or commands: to work in the challenges.yml file. The comments say to use "rewardcommands:" while the actual challenges use "commands:"

I make sure not to use / and even tried uncommenting the example, but none work:

      rewardcommands:
      - pex user [player] group add Craftsman
      - kit tools [player]
      - spawn

I'm trying to do this for levelUnlock as well as for challenges themselves. See attached file.

Please advise on how to get commands to execute upon levelUnlock and completion of challenges.

Thanks!

[challenges.yml.zip](https://github.com/tastybento/askyblock/files/139855/challenges.yml.zip)

**Comment by tastybento** [comment]
The section heading for running commands in the level unlock area is just "commands:". To run a command as the player, it needs to be prefixed with [SELF] and to make it YML compatible, put in quotes. So the result is:

`  levelUnlock:
    Craftsman:
      # What additional message to send player
      message: 'Congratulations - you unlocked the &9Craftsman level challenges!'
      rewardDesc: '3 diamonds!'
      itemReward: 'DIAMOND:3'
      moneyReward: 100
      expReward: 100
      # List permissions separated by spaces
      permissionReward: ''
      # Commands to run on this player. Use [player] for their name.
      commands:
      - pex user [player] group add Craftsman
      - kit tools [player]
      - "[SELF] spawn"
      #- some other command`

**Comment by tastybento** [comment]
```  levelUnlock:
    Craftsman:
      # What additional message to send player
      message: 'Congratulations - you unlocked the &9Craftsman level challenges!'
      rewardDesc: '3 diamonds!'
      itemReward: 'DIAMOND:3'
      moneyReward: 100
      expReward: 100
      # List permissions separated by spaces
      permissionReward: ''
      # Commands to run on this player. Use [player] for their name.
      commands:
      - pex user [player] group add Craftsman
      - kit tools [player]
      - "[SELF] spawn"
      #- some other command`
