### ISSUE TITLE
How to enable fall damage

### ISSUE THREAD

**Issue by m0ns7err** [tastybento/askyblock#177]
Hello :) I have a question.
How can I enable fall damage on my server.I cannot find it anywhere.

**Comment by tastybento** [comment]
It sounds like a plugin is making player invincible to fall damage. I'm not sure which one does that. It could be WorldGuard, Essentials or any other plugin.

**Comment by m0ns7err** [comment]
How can I fix it ? Any suggestions ?

**Comment by tastybento** [comment]
Remove plugins one by one until it stops happening. Then you know which one is causing it. Then edit their config.yml file to remove the protection.
