### ISSUE TITLE
Find a way to allow chest shop signs to be broken by all team members

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#178]

**Comment by YellowZaki** [comment]
Oh my god, this would be awesome. I have thought on it a lot of times xD but I didn't think you would be able to do it.

**Comment by tastybento** [comment]
What's the actual plugin you use?

**Comment by Steev93** [comment]
http://dev.bukkit.org/bukkit-plugins/chestshop/

**Comment by Steev93** [comment]
Someone else updated i tho here: https://www.spigotmc.org/resources/1-9-chestshop.19511/

I am yet to test it

**Comment by 7rory768** [comment]
Why. It just listen to block break even and check if the block is a sign on the chest, check if it is a chest shop sign by casting it to a sign and checking the lines. And then if the event was canceled setCancelled false if it was broken on the island that that played belongs to

**Comment by 7rory768** [comment]
Did not mean to say why there

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#67
