### ISSUE TITLE
Existence Maven repository

### ISSUE THREAD

**Issue by games647** [tastybento/askyblock#179]
Do you have a maven repository? I couldn't find one, so I tried to use [jitpack.io](jitpack.io/), but it [fails](https://jitpack.io/com/github/tastybento/askyblock/-V2.9.8.2-gee10b6f-18/build.log) building your project.

**Comment by tastybento** [comment]
This project needs binaries to build it (Minecraft servers) that cannot be put on github. You will need to build them yourself and put them in a local folder that is in the POM. Sorry, copyright stuff...

**Comment by games647** [comment]
I see. Maybe you could build it on your local computer and deploy it to a maven server. It's ok if you refuse to do it. I'm just interested, because my maven config is already messed up with a lot of system dependencies.

**Comment by tastybento** [comment]
ASkyBlock is here:
https://bintray.com/tastybento/maven-repo/askyblock/view

AcidIsland here:
https://bintray.com/tastybento/maven-repo/acidisland/view

**Comment by tastybento** [comment]
`<dependency>
  <groupId>com.wasteofplastic</groupId>
  <artifactId>askyblock</artifactId>
  <version>3.0.0.8</version>
  <type>pom</type>
</dependency>`

`<repositories>
<repository>
<snapshots>
<enabled>false</enabled>
</snapshots>
<id>bintray-tastybento-maven-repo</id>
<name>bintray</name>
<url>http://dl.bintray.com/tastybento/maven-repo</url>
</repository>
</repositories>`

**Comment by games647** [comment]
Thanks a lot.
