### ISSUE TITLE
Skyblock Settings

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#181]
Little bug i found tonight, when i updated the config a few weeks ago and stuff, i turned allowchestaccess ON, however t's now disabled yet some islands still have it on and wont change. Any way to fix this ?

**Comment by tastybento** [comment]
I've just added an admin command to globally reset islands to default protection settings. Other than that you'll need to fly to each island as Op and set them one by one.

**Comment by Steev93** [comment]
Well crap... Okay i will get this update ASAP. Can you verify the command please?

**Comment by tastybento** [comment]
It's /asadmin settingsreset confirm.

**Comment by Steev93** [comment]
When will this command exist i just updated and nothin to work as of yet

**Comment by tastybento** [comment]
Where did you get the release? It's here: https://github.com/tastybento/askyblock/releases/tag/V3.0.0

**Comment by Steev93** [comment]
Spigot thanks will update this now
