### ISSUE TITLE
[Brewing] Potion/Alchemy Issue

### ISSUE THREAD

**Issue by Kinjah** [tastybento/askyblock#182]
I've gone ahead and tested this on different versions with the same underlying issue.

Whilst in a Skyblock world managed by aSkyblock, the skill "Alchemy" from McMMO cannot seem to work properly.

However, whilst in the overworld or even after disabling aSkyblock the "Alchemy" skill seems to work just fine.

Any help would be greatly appreciated! :)

Information:
Server: PaperSpigot 1.8.8
Plugin: 
- aSkyblock 2.9.9 (Tested from 2.9.5 - Current)
- McMMO B85 (Tested from B52 - B85)

**Comment by tastybento** [comment]
Try latest plugin that has removed potion brewing code.
