### ISSUE TITLE
1.9 problem with rewardcommands and repeatrewardscommands

### ISSUE THREAD

**Issue by RenaudRl** [tastybento/askyblock#184]
Good evening , I tested the v3.0.0 is over there have a problem with the rewardcommands , they do not It Works .
Can you fix this .
Thank you.

**Comment by tastybento** [comment]
I can't replicate this. What is your challenges.yml file?
This works fine:

`    dyemaker:
      friendlyname: 'Dye Maker'
      description: 'Craft 2 cactus green dyes'
      icon: INK_SACK:2
      level: 'Novice'
      type: inventory
      requiredItems: 'INK_SACK:2:2'
      takeItems: true
      itemReward: 'SAPLING:0:2 SAPLING:1:2 SAPLING:2:2 SAPLING:3:2'
      rewardText: '2 oak, 2 birch, 2 jungle and 2 spruce saplings'
      moneyReward: 10
      expReward: 30
      permissionReward: ''
      repeatable: true
      repeatItemReward: 'SAPLING:0:1 SAPLING:1:1 SAPLING:2:1 SAPLING:3:1 SAPLING:4:1 SAPLING:5:1'
      repeatRewardText: '1 of each kind of sapling'
      repeatMoneyReward: 5
      repeatExpReward: 10
      # Max times limits how many times a challenge can be done. Comment out to make unlimited
      maxtimes: 100
      rewardcommands:
      - kit tools [player]
      repeatrewardcommands:
      - kit dtools [player]
`

**Comment by tastybento** [comment]
So does this:

```  levelUnlock:
    Competent:
      # What additional message to send player
      message: 'Congratulations - you unlocked the &9Competent level!'
      rewardDesc: 'A diamond!'
      itemReward: 'DIAMOND:1'
      moneyReward: 100
      expReward: 100
      # List permissions separated by spaces
      permissionReward: ''
      # Commands to run on this player. Use [player] for their name.
      commands:
      - kit tools [player]
      #- some other command
`

**Comment by tastybento** [comment]
Also, make sure you're using the latest binary build, or build it yourself because it has been worked on.

**Comment by RenaudRl** [comment]
i use the last binary build,all of my challenges work but the rewardcoammands not,i have test the default template challenges,it's not work for me

**Comment by tastybento** [comment]
It must be your YML or something. For the above tests, all I did was remove the # to uncomment the kit command (which is from essentials). Can you confirm whether that works?

**Comment by I3lizzardI3east** [comment]
I have the same issue, and I was able to narrow it down that when permissionsex is loaded, the commands are not executed.  There is no message to the console either.  But if I remove permissionsex, then everything works again.  I've had this issue for a long time, but I only today figured out it is permissionsex in the mix that is killing the reward commands.

Is there a trick to allowing the reward commands to execute?  I am OP, and it doesn't even work when *I* complete a challenge unless I disable permissionsex.

**Comment by I3lizzardI3east** [comment]
SOLVED (at least for me) - As OP, I had access to all permissions, so I had to specifically deny askyblock.command.challengeexempt for myself.  Looks like the issue may have been only me, but left me thinking it was everyone because of testing on myself as OP.

**Comment by tastybento** [comment]
Thanks I'll add this to the FAQ!
