### ISSUE TITLE
1.9 Missing Island

### ISSUE THREAD

**Issue by kunisadako** [tastybento/askyblock#186]
My name is luthfianda. This is the problem .
when i log out. then i log in to the server, i type "/is" .usually it show up the GUI about my island. but this is different. when i type "/is", it show the GUI to choose starter island for newbie instead show up the GUI about my island. 
this is weird, but when i type "/home" (because i sethome in my island). and my island exist. but when i type "/is" it show the GUI to choose starter island for newbie instead show up the GUI about my island. when i type "/is go" , it says "you dont have an island", but actually my island is exist but i didnt have access to it
![2016-03-10_01 25 15 - copy](https://cloud.githubusercontent.com/assets/17769056/13678727/05e290c8-e6a5-11e5-950c-2b1379cc17d7.png)
![2016-03-10_01 25 22 - copy](https://cloud.githubusercontent.com/assets/17769056/13678731/0b9adcc8-e6a5-11e5-8633-2aa45016697e.png)
![2016-03-10_01 25 58 - copy](https://cloud.githubusercontent.com/assets/17769056/13678738/14fb59aa-e6a5-11e5-8e33-e1a2cb942a09.png)

**Comment by tastybento** [comment]
I think your islands.yml file has become corrupted because of a server crash maybe. Stop the server, move islands.yml to islands.old and start the server again. It should fix the problem.

**Comment by YellowZaki** [comment]
If I delete islands.yml and I restart the server, will the existing islands be automatically added to the new islands.yml with any problems?

**Comment by tastybento** [comment]
@kunisadako : Another thought - did you change the island distance in config.yml by accident? Check that it is the same as what it used to be. That can cause serious mis alignment of islands.

@YellowZaki : Player owned islands, yes. The spawn island position will be lost, so you'll need to make that again if you had one. Also, any unowned islands (unregistered) ones will lose their settings, like PVP and you will need to go to them again and set them back up again.
