### ISSUE TITLE
askyblock.nohunger doesn't work correctly

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#189]
Steps to reproduce the problem:
1 Have the askyblock.nohunger permission
2 Run (in another zone that it is not the island) to decrease the hungerbar.
3 Run in my island ---> My hungerbar doesn't decrease here BUT when I eat, the food item is consumed and the hungerbar doesn't increase. To eat, I need to go out of my island.

Other times, the hungerbar doesn't increase although I'm not in my island and the food item doesn't get consumed. To eat, I need to relog and eat in a place that it is not my island.

**Comment by tastybento** [comment]
Yes, I agree. It's too simplistic right now. This can be fixed.

**Comment by tastybento** [comment]
Fixed in 	c0f6d29
