### ISSUE TITLE
There are no new blocks from 1.9 in blockvalues.yml

### ISSUE THREAD

**Issue by wasder** [tastybento/askyblock#192]

**Comment by tastybento** [comment]
Okay I'll look at this. You should be able to add them manually. But I'll look at adding some.

**Comment by wasder** [comment]
I could if I knew where to find all the correct names for the items.

**Comment by tastybento** [comment]
Here's a reference: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by tastybento** [comment]
Added in 3.0.0.3
