### ISSUE TITLE
Island restart issue

### ISSUE THREAD

**Issue by xerobeagle** [tastybento/askyblock#193]
Using latest version, when someone does /is restart it lags the server badly to the point of timing out.

The CPU usage of the server spikes to using a full core @ 100% and stays there for around 30 seconds. Ram is unaffected.

**Comment by Steev93** [comment]
This got fixed I believe in the latest updates I believe https://github.com/tastybento/askyblock/releases

**Comment by xerobeagle** [comment]
Using the latest version and it is still happening

**Comment by tastybento** [comment]
What server version are you using? Are you using the clear up blocks option? What's your protection and island sizes?

**Comment by xerobeagle** [comment]
Kcauldron 1.7.10, Clear up block option false.

Protection range 200
distance between islands 1000

**Comment by tastybento** [comment]
Okay. Please confirm you're using 3.0.0.2 version. Also, please pastebin the crashlog. Or dropbox URL because I need to see where it's crashing. 
When did this start happening? Was it fine with a previous version and then you upgraded? If so, which version were you on before.

**Comment by xerobeagle** [comment]
There is no crash report as the server doesn;t actually crash, it just hangs the server for around 25 to 30 seconds. 

It times everyone out and then a few seconds later everyone is able to rejoin again, very weird issue, However as i said previously when it happens it uses 100% of 1 core on the CPU but ram is unaffected, and to confirm yes latest version.

**Comment by tastybento** [comment]
Question - does this happen when you do **/asadmin delete (name)** as well? Or just when you do **/is reset**? I'm wondering if it's slow because of the island deletion or the pasting. Do you have a custom island schematic?

Can you paste your start up log? I'm wondering if NMS has stopped working you your server.

Also, check your log for any string that says: "Island delete".

**Comment by xerobeagle** [comment]
Yes this also happens when /asadmin delete (name) is used aswell. 

Tried it using a custom schematic & the included ones, same results.

I've attached the server's latest log from startup to hang.
[server-latest.txt](https://github.com/tastybento/askyblock/files/181866/server-latest.txt)

**Comment by xerobeagle** [comment]
Ok found the issue.

I ripped apart the pack and removed 3 of the mods and now islands are creating/deleting without issues.

The mods that are incompatible are
CustomOreGen-1.7.10-1.2.24
HarderWildlife-13.21.0a
HardLib-13.21.0a

Just thought you would like to know what is causing an issue and maybe help someone else if they having problems aswell.

Thanks for you time.

**Comment by tastybento** [comment]
Okay, thanks for the tip.
