### ISSUE TITLE
Add translations for challenges GUI

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#194]
It's just a little thing xD. I would like to translate the message: "Click to see <levelname> challenges!" when you put the pointer over the books of the challenges GUI.
And I would like to change the color of the descriptions of challenges (they are GOLD for default)

PD: Also, it would be good to use DATA in a challenge type:island for example to check if the netherwart is grown (115:3:1--> It would check for a netherwart fully grown)

**Comment by Steev93** [comment]
Yes you can do all of this your side, and as for gold? you can do this do find the right color codes ad use them.

There is an island challenge, ls an inventory challenge, if you use the challenge stand within 10 blocks of full grown nether wart, the challenge will work

**Comment by YellowZaki** [comment]
You haven't understood me. Right now, you can't change the challenges color description.
And if you complete an island challenge that requires netherwart planted on soulsand, it ignores if the netherwart is grown or not.

**Comment by tastybento** [comment]
Look in the locale.yml or other language files at the challenges.navigation line. You will see "Click to see [level] challenges!". Have you tried putting &b or &c, etc. in front of it? I can't test right now, but it should work.

Interesting idea about the data. It may be possible, I'll mark this issue as an enhancement request.

**Comment by YellowZaki** [comment]
In locale.yml I can't find that line.
And not, it is not posible to add colors in challenges descriptions.

**Comment by tastybento** [comment]
Okay, you found a bug - it's missing from the translation. You can add the line 

```challenges: 
  navigation: "Click to see [level] challenges!"`

**Comment by YellowZaki** [comment]
Yes, it works with that missing line, thanks!
Could you check my another issue about potions on challenges? It is more important.
