### ISSUE TITLE
Potions don't work on challenges

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#195]
When there are more than 1 potion in required items for challenges like:
      requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1'
There are not detected and it says: You have not the items to complete the challenge.

However, if there is just 1 potion like:
      requiredItems: 'POTION:FIRE_RESISTANCE::::1'
It works well.

**Comment by Steev93** [comment]
this has all changed cause of the new items I suggest checking Spigot ?

**Comment by tastybento** [comment]
@YellowZaki 
I can't replicate this. It seems to work fine, for example the alchemist challenge is:

      requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1 POTION:SPEED::::1 POTION:INSTANT_HEAL::::1 POTION:INSTANT_DAMAGE::::1 POTION:INVISIBILITY::::1 POTION:STRENGTH::::1 POTION:REGEN::::1'

and works. 

I also tried:
requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1'

went into creative, gave myself these two potions and completed the challenge.

Can you pastebin your full challenge.yml?

**Comment by YellowZaki** [comment]
Here is the challenge:
    hechicero:
      friendlyname: 'Hechicero'
      description: 'Prepara 1 poción de: velocidad y resistencia al fuego (no importa el nivel)'
      icon: POTION
      level: 'Medio'
      type: inventory
      requiredItems: 'POTION:SPEED::::1  POTION:FIRE_RESISTANCE::::1'
      takeItems: true
      itemReward: 'GOLDEN_APPLE:0:4'
      rewardText: '4 manzanas de oro'
      moneyReward: 200
      expReward: 160
      permissionReward: ''
      rewardcommands:
        - aa announce 5 &c&l[player] &6completó el reto &2&lHechicero
      repeatable: false
      repeatItemReward: 'ICE:1'
      repeatRewardText: '1 block of ice'
      repeatMoneyReward: 5
      repeatExpReward: 10
      maxtimes: 1


I'm using the latest version (3.0.2)

**Comment by tastybento** [comment]
It does work, but you have to brew the fire resistance potion yourself. For some reason, the potion if you pick it from the creative mention is level 2, but if you brew it yourself it is level 1. Note that level 2 is an illegal setting.
One other issue - using POTION as an icon will work in V1.8.x but isn't a valid icon in 1.9 for some reason.

**Comment by YellowZaki** [comment]
Well, Water bottle+Netherwart+MagmaCream= 373:8195 This works fine. But the creative potion is 373:8227. And you can get that potion in 1.8 with Water bottle+Netherwart+MagmaCream+Redstone+Glowstone.
I don't know how have the users got those potions (it is applicable for other potions)


Can you make those rare potions xD compatible? They can be obtained in survival

**Comment by YellowZaki** [comment]
I have another challenges that:
      requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1 POTION:SPEED::::1 POTION:INSTANT_HEAL::::1 POTION:INSTANT_DAMAGE::::1 POTION:INVISIBILITY::::1 POTION:STRENGTH::::1 POTION:REGEN::::1 POTION:POISON::::1 POTION:NIGHT_VISION::::1 POTION:WEAKNESS::::1 POTION:WATER_BREATHING::::1 POTION:JUMP::::1'

I have made all potions manually but it doesn't work

**Comment by tastybento** [comment]
I've rewritten the potion handling code. It should work better. If a potion aspect is not specified, it assumes any value is okay. So, in your examples, any fire resistance potion will be okay (any strength, any kind, etc.)
https://github.com/tastybento/askyblock/releases/tag/V3.0.0.3

**Comment by YellowZaki** [comment]
Ok, thank you!
