### ISSUE TITLE
a-skyblock challenge reward issue

### ISSUE THREAD

**Issue by AcesGamingUK** [tastybento/askyblock#196]
players aren't getting reward commands or repeat reward commands from challengesany advice?

here is what we are using

commands:
- lbs admin giveLuckyBlocks 5 [player]

rewardcommands:
- lbs admin GiveLuckyBlocks 2 [player]

repeatrewardcommands:
- lbs admin GiveLuckyBlocks 2 [player]

any advice?

**Comment by tastybento** [comment]
Check permissions. See https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#challenge-commands-do-not-work

**Comment by tastybento** [comment]
Also paste what you see in the console when a player completes the challenge (not an op).

**Comment by AcesGamingUK** [comment]
ahh ok thanks i see what it was now.. when the perms were set by the previous guy he put 
- -askyblock.command.challengeexempt. as a base perm.... thanks for the help XD
