### ISSUE TITLE
Island Spawn Point

### ISSUE THREAD

**Issue by drtshock** [tastybento/askyblock#20]
Hey so we made some nifty schematics with a small pirate ship attached to it for a pirate themed server. We made the schematic from the center of the ship where we wanted people to spawn but upon making a new island, players are spawning on the main part of the island above the chest (isn't room next to it). Is there a way to hard set the spawn point on each schematic?

**Comment by tastybento** [comment]
Added in 2.9.3. spawnblock in the config will define the block where the player should spawn.
