### ISSUE TITLE
Add no splash option to settings

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#200]
From AcesGamingUK

**Comment by Poslovitch** [comment]
@tastybento No splash? What does it mean?

**Comment by tastybento** [comment]
Okay, I'm not sure we should care about this, so let's discuss. No splash means prevent splash potions. However, I'm thinking this should just be a system setting, not a per-island setting.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#66
