### ISSUE TITLE
Minishop Pig Egg

### ISSUE THREAD

**Issue by herbstduft** [tastybento/askyblock#201]
hi,

when i buy a pig egg in the minishop; it looks like a sheep egg. but when i use the egg, no pig spawns. there is no error in the console.

**Comment by tastybento** [comment]
Since 3.x, the monster eggs need to be defined by name. Simple fix, delete minishop.yml and restart. You also need to do that with challenges.yml.

**Comment by herbstduft** [comment]
in challenges.yml i edit all egg correctly. I test this with minishop.yml. thx

**Comment by herbstduft** [comment]
i deleted now the minishop.yml, that works out. but now the players dont receive damage through rain.

**Comment by herbstduft** [comment]
ok, it now works all.
