### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by xion87** [tastybento/askyblock#203]
Hi i dont know why but with these latest update (1.9), skyblock seem to use 90%-100% cpu usage based on online players, example i have 18 players online and it using 90-100% cpu. 
All others my server is using 30%-40% cpu with 50-80 players...

Plugins (20): WorldEdit, Skript, Nicky, PlaceholderAPI, DuckSuiteTeleports, Craftconomy3, FeatherBoard, ChatControl, ViaVersion, BungeePerms, Vault, ProtocolLib, WorldGuard, TitleManager, AAC, ASkyBlock, MobStacker, DuckSuiteWarps, ChestShop, Auctions

Spigot version:This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)>

Any idea what it can be?

**Comment by tastybento** [comment]
What version of the plugin?

I have heard of CPU issues with saving of files. There's a 5 minute timer to save the islands.yml and that can cause high CPU.

Do you see anything in timings?

**Comment by xion87** [comment]
i already using  backupduration: 10, there are some cpu spike from 5% to 50%, when 1 player play, and it happen like in 1-2 minutes: http://www.spigotmc.org/go/timings?url=15754072

**Comment by meytro** [comment]
This is the process of saving files. These 36ms aren't even worth a look if it they only occur all 10 minutes.

**Comment by tastybento** [comment]
@xion87 - which version did you update from?

**Comment by xion87** [comment]
The situation well go to 45- 55% cpu usage with 20 players online, after playing a little with spigot.yml and bukkit.yml and purget latest 365 old island... i will keep to monitoring if happen again

**Comment by tastybento** [comment]
I suspect it is JVM garbage collection running in the background.

**Comment by xion87** [comment]
@tastybento i upgraded from 2.9.9 to 3.0.0 then to 3.0.0.3

**Comment by xion87** [comment]
the server dont run out ram, i dedicated 10 gb on skyblock server ... 
my starting propt is: -Xmx$10240M -Duser.timezone=Europe/Rome -jar spigot.jar nogui

**Comment by philip-ulrich** [comment]
I'm also seeing some odd CPU usage: http://www.spigotmc.org/go/timings?url=15959954

I'm on spigot 1.9.2 and askyblock 3.0.0.3. There was literally just me on during that time and no one else. :|

**Comment by tastybento** [comment]
This isn't anything to do with the plugin, but what you are being hammered with is a BlockPhysicsEvent that is being called on average 2,350 times per tick. You can see it in the plugin reports, every plugin that listens to that is being hit. The event is fired when a block moves, e.g. sand falling. I don't know why you're getting so many blocks moving in your world.

**Comment by philip-ulrich** [comment]
Ahh. Good to know. I'm not sure why that is, but I'll try to look into it. Thanks @tastybento!

**Comment by xion87** [comment]
Again 120% cpu usage with 30 user....

**Comment by tastybento** [comment]
@xion87 can you post timings? Also, can you try 3.0.0.4? I don't know if it'll make any difference, but I'm going to release it very soon.

**Comment by xion87** [comment]
http://www.spigotmc.org/go/timings?url=16004851

**Comment by xion87** [comment]
now cpu usage is 30-40% 17 players... wtf

**Comment by tastybento** [comment]
How are you measuring cpu usage? Via a MC control panel? Or do you have access to the linux shell and run top?

**Comment by xion87** [comment]
i am using pufferpanel, that it replect the cpu see in "top" process of the server

**Comment by tastybento** [comment]
Okay, so then the CPU usage could be a process running in the background.

**Comment by xion87** [comment]
nope, is a dedicated server, each panel/process has it own cpu usage

**Comment by tastybento** [comment]
If the CPU usage does not show up in the timings, but shows in the control panel, then it is the JVM doing something, most likely garbage collection. Right now, I'd guess that it is just 1.9 server operation. It *may* be related to my plugin, but I doubt it. You can try 3.0.0.4. I removed a library that does name > uuid look up, but I don't know if it'll make any difference to CPU or not.

**Comment by tastybento** [comment]
@xion87 Also, you can try https://github.com/tastybento/askyblock/releases/tag/3.0.0.5. I did a source code check for potential resource leaks and around a couple. It'd be interesting to see if it helps or not.

**Comment by xion87** [comment]
gonna test now, and let you know :)

**Comment by xion87** [comment]
Ther are some peaks of 90% 150% cpu usage when user login, cpu usage is normally 30-40% with 10 players right now
