### ISSUE TITLE
Move name<>UUID database from JDBM to MapDB

### ISSUE THREAD

**Issue by vemacs** [tastybento/askyblock#204]
The JDBM implementation is old, unsupported, and occasionally prone to data corruption (I have to manually rebuild the cache every 2 months or so on a server with 180,000 entries). It would be nice if ASkyBlock could move to JDBM's successor, MapDB. The latest stable version is 1.0.9.

**Comment by tastybento** [comment]
Okay, I'll look into it.

**Comment by tastybento** [comment]
I looked at the library but it was too big. Instead I went with a simple text file and removed the db library all together. This should work a lot better.
