### ISSUE TITLE
Add option to have reset limit set by schematic type

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#207]
Requested by https://www.spigotmc.org/members/pepsiisgross.10752/

**Comment by Poslovitch** [comment]
Can you explain a bit this idea?

**Comment by tastybento** [comment]
Yes, we should discuss because it may not work very well. The idea is to make the reset limit based on the schematic. I think the requestor wanted players to only have say 3 goes to make a specific island before they had to chose another one. I'm not sure why. The problem is with trying to track that, forever. We have enough baggage to store for the challenges!

Do you think this is a good idea? If not, let's reject it.

**Comment by Poslovitch** [comment]
Okay I see.
I think we should reject it. It is too much tracking and too much difficulty to setup properly.

**Comment by tastybento** [comment]
Agreed.
