### ISSUE TITLE
Challenges GUI not working correctly.

### ISSUE THREAD

**Issue by NitsanDA** [tastybento/askyblock#209]
Hello, I am contacting you about a possible bug in your plugin. When executing /c you are presented with a GUI that has all the challenges presented in the form of clickable items. On my server it seems that players and I can simply pick out the items from the GUI hence presenting a problem. 
I dont know if its somthing wrong with how I set it up but this was never an issue before. 
Any help would be great from you. 
Thank you and have a nice day, 

Nitsan

**Comment by tastybento** [comment]
It's another plugin that is interfering with the inventory. If you remove them it'll work fine. Start with any one that does inventories or chests.
