### ISSUE TITLE
Issue loading Taiga recipe

### ISSUE THREAD

**Issue by Scizornician** [tastybento/askyblock#210]
I'm having this issue below on the newest version of the plugin:
http://prntscr.com/as5hff

**Comment by tastybento** [comment]
On 1.8 servers it has to be COLD_TAIGA. On 1.9 servers TAIGA_COLD.  Yes, Minecraft switched the biomes...

**Comment by Scizornician** [comment]
Sorry my bad, didn't read the changelog on Spigot.
Reverting back to a 1.8 version of your plugin should work fine then right?

**Comment by tastybento** [comment]
I recommend you keep the latest version, but just change the text in the biomes.yml (line 19).
