### ISSUE TITLE
Bug with ASkyBlock and AcidIsland plugin

### ISSUE THREAD

**Issue by renzotom** [tastybento/askyblock#213]
Hello, I am found bug. When I have AcidIsland plugin and ASkyBlock too, when I try /ai ms I can´t buy items. No text, but when I write /plugman (I use plugin plugman) reload ASkyBlock, it works. I think, AcidIsland load after ASkyBlock and it don´t work (when I try /plugman reload AcidIsland, it still don´t work).

**Comment by tastybento** [comment]
Please explain more about "I can't buy items " what happens exactly?

**Comment by renzotom** [comment]
When I click on it, it doesn´t write none text. Nothing will happen

**Comment by tastybento** [comment]
Is the title of the mini shop in Acid Island and Askyblock? They must be different. Use a different color or letter.

**Comment by renzotom** [comment]
How I change title? I must change it in all language files?

**Comment by tastybento** [comment]
Yup, this is a bug. The Minishop title in the locale files in AcidIsland became the same as ASkyBlock and that causes problems if the two shops have different items in them in different places. 
This build fixes your problem. Make sure you delete the locale folder so the new files can be used.
https://github.com/tastybento/acidisland/releases/tag/3.0.0.6

**Comment by tastybento** [comment]
Fixed
