### ISSUE TITLE
Potentiak bug, unlimited team size and homes.

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#217]
In the latest versions I have noticed that players have unlimited team size and homes.
In my config I have maxteamsize set to 4.

**Comment by YellowZaki** [comment]
Solved erasing the permission askyblock.team.*
That permission is not supposed to give askyblock.team.maxsize.99
I think that is a versiom bug.

**Comment by tastybento** [comment]
Right - askyblock.team.* gives unlimited permissions, which includes the max maxsize, which is 99.
I'll have to look into how to change.

**Comment by YellowZaki** [comment]
Older versions didn't have this issue, you should update the permissions page.

**Comment by tastybento** [comment]
I went back to the old way of checking the permissions. It shouldn't matter now.
