### ISSUE TITLE
Island Names

### ISSUE THREAD

**Issue by drtshock** [tastybento/askyblock#22]
Instead of having it just go by the island leader's name, why not let them set a 'name' or a tag or something? Would be cool for the /is top list and what not. With an option to set the min and max characters the tag can be (like factions).

**Comment by tastybento** [comment]
Yes, this is a very good idea. I want to make use of the Settings panel to do this and model it off what I did in Districts. In Districts, the players can set the properties of their district via a control panel (and subsequent conversations). They can set the name, and what is allowed/not allowed in the district, like PVP, or chest access. The admin also has a global panel that will be able to allow players to set their setting or not for each property.

**Comment by drtshock** [comment]
That would be quite handy.

**Comment by tastybento** [comment]
Custom settings for Island Guard will be in V2.9.6.
Naming is not in there yet. I'll add that another time.

**Comment by tastybento** [comment]
Added island naming in 0744b94.
