### ISSUE TITLE
1.9 Island missing again

### ISSUE THREAD

**Issue by kunisadako** [tastybento/askyblock#221]
this is the second time i send this issues, and the problem still the same. when i type /is command, it show me the GUI for creating an island instead show up the GUI about my island control panel. And then when i try to log out and login, my inventory were rollback, so it did'nt save my character inventory. another player too. why is this happening? maybe because server crash? or corrput file? can you explain to me?
sorry for bad english , i cant speak english very well, also i did'nt have the screenshot

**Comment by YellowZaki** [comment]
Make sure you have enough storage. My players' file were becoming corrupted due to insufficient space (host's fault)

**Comment by tastybento** [comment]
Sounds like corrupted files to me!

You can try this:
1. Stop server
2. Delete islands.yml file
3. Restart

This will rebuild information from the players folder. However, if that folder is messed up, then you need to go back to a backup.
