### ISSUE TITLE
/s spawn

### ISSUE THREAD

**Issue by renzotom** [tastybento/askyblock#223]
Hello, command /is spawn don´t work, it write Unkown command.

**Comment by tastybento** [comment]
Have you set the island spawn with /asadmin setspawn?

**Comment by renzotom** [comment]
The island space is owned by Renzotom.
Move further away or unregister the owner. You have idea? It is on my island (spawn).

**Comment by tastybento** [comment]
/is spawn only works if you set up a spawn island. Not all admins do this. Some put spawn in another world. If you want a spawn island, you should place it somewhere away from normal islands. So, maybe teleport to 10000,10000, create an island (with world edit) and then set it as spawn /asadmin setspawn.

Alternatively, if you want to make your own island the spawn, unregister yourself (/asadmin unregister renzotom) and then do /asadmin setspawn to make the island the spawn island.
