### ISSUE TITLE
option for fire block damage

### ISSUE THREAD

**Issue by DamageDoctor** [tastybento/askyblock#224]
I have been playing with the plugin (which is fantastic) but haven't been able to find an option to enable fire block damage. Is fire block damage completely disabled when using the plugin because from experimentation it appears so? If so, is there any chance of getting an option to allow this damage as it can be used to make things much harder by forcing players to not use wood on a cobble gen?

Thanks,

**Comment by tastybento** [comment]
Yep, it's supported. Do a search for fire spread in config.yml.

**Comment by darkcamo12** [comment]
"Friend of damagedoctor"


We have fire spread enable so the fire will spread to the adjacent block but as for destroying the block on the other had it doesn't not

As a test we removed all plugins and added then back 1 by 1 until we found what it was 

As another test we only ran the server with just askyblock and well even with the fire spread setting on block wouldn't get destroyed

**Comment by tastybento** [comment]
@darkcamo12 I can't replicate this. If I run the plugin by itself (and Vault) and apply fire, it spreads and blocks are destroyed if allowfirespread: true. See [here](http://giphy.com/gifs/minecraft-fire-spread-3o7qDLZbN2VxaFT4eQ).

**Comment by DamageDoctor** [comment]
@tastybento I just ran server up with only ASkyBlock 3.0.0.8 and Vault 1.5.6 and still have the same issue with fire not actually burning anything. Can I ask what you are running on your server? Thermos? Cauldron? etc? Are you running on FTB or just adding your plugin to Vanilla minecraft? We are using FTB Infinity Skyblock.

**Comment by tastybento** [comment]
I focus on Spigot 1.9.4 and CraftBukkit associated with it.

**Comment by DamageDoctor** [comment]
hey @tastybento . sorry for wasting your time. found a typo which was causing the issue. any thoughts on putting error checking / logging into the config file parsing for stupid people like us who can't type properly? ;)

**Comment by tastybento** [comment]
Ah, okay. Sorry, unless the YML is actually broken (doesn't pass YML synth checking) it isn't possible to verify that settings are not correct...
