### ISSUE TITLE
Feature Request: /is limits

### ISSUE THREAD

**Issue by ghost** [tastybento/askyblock#226]
This command could show how many island limits a player already has reached (hopper, animals, monsters, tileentities). Would be useful for all players and for admins there could be also the command /asadmin limits <island> to check the limit of a specific player.

**Comment by Steev93** [comment]
Following

**Comment by Poslovitch** [comment]
Please put it in 3.0.5 milestone

**Comment by tastybento** [comment]
Let's move to 3.0.6 so we can release 3.0.5.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#64
