### ISSUE TITLE
Chat prefix 

### ISSUE THREAD

**Issue by renzotom** [tastybento/askyblock#227]
Please, what chat plugin support per-world prefix? I  think, in ASkyBlock worlds (ASkyBlock and ASkyBlock_nether) will be prefix {ISLAND_LEVEL}  and in Survival world (world) it doesn´t will be.

**Comment by tastybento** [comment]
Most plugins should work, but I've tested Essentials Chat, PEX and HeroChat.

**Comment by renzotom** [comment]
And how I set it to Essentials chat plugin ?

**Comment by tastybento** [comment]
You just have to put {ISLAND_LEVEL} in the prefix in the Essentials Chat config.yml. Like this:

`  format: '<{DISPLAYNAME}> {MESSAGE} ({ISLAND_LEVEL}) [{ISLAND_CHALLENGE_LEVEL}]'
`

**Comment by renzotom** [comment]
And I can set it only in worlds ASkyBlcok and ASkyBlock_nether ?I don´t want it in world :/

**Comment by tastybento** [comment]
I don't know, sorry. I only provide the prefix. It's up to the other plugin to decide when to show the prefix. It may be possible to have per-world prefixes but I don't control that.

**Comment by renzotom** [comment]
Ok :(. Thanks, I try find some free plugin with per-world prefixes.

**Comment by renzotom** [comment]
I also tried it in permissionsex -           prefix: '{ISLAND_LEVEL} &f[&aSkyBlockHrac&f]&f ' and didn´t work
And what is chat prefix for AcidIsland?

**Comment by tastybento** [comment]
I'm not an expert of chat prefixes but you often have to switch off other plugin's chat system if you want to use PEX's. 

Actually, there isn't a chat prefix different for AcidIsland, so that could cause a problem if they are both running on the same server.

**Comment by renzotom** [comment]
I have both on one server. And you think, problem is, beacuse I have essentials chat and pexs?
