### ISSUE TITLE
island locking on reset

### ISSUE THREAD

**Issue by DamageDoctor** [tastybento/askyblock#228]
We are trying to enforce island locking by default. The start commands appear to work in achieving this for the first island but is there any chance of allowing island locking on a reset?
Does the **resetcommands:** section occur before or after new island creation?

**Comment by tastybento** [comment]
Yes, just put - "[SELF] island lock" in the reset commands.

**Comment by DamageDoctor** [comment]
thanks @tastybento. you are a champion!
