### ISSUE TITLE
Feature Request: Island Guard - Fly

### ISSUE THREAD

**Issue by ghost** [tastybento/askyblock#230]
I would like to see a feature which gives players the option to enable flymode on their own island for all players. 
- if players leave their own island, they will lose their flymode
- there should be an enhancement which removes the flymode only after X more seconds so that it's possible to fly outside of the island to build things on the border for a few seconds/minutes
- there should be an enhancement which removes the flymode instantly after teleporting outside of the island (/tpa, /tp, /is for another island, /spawn)

**Comment by meytro** [comment]
Now that it's labeled as "enhancement" will it be implemented soon or is it a "maybe in the future"?

**Comment by Poslovitch** [comment]
It should be added in 3.0.5 ;)
I'll work on it @tastybento !

**Comment by tastybento** [comment]
Let's move to 3.0.6 so we can release 3.0.5.

**Comment by tastybento** [comment]
Pull request is still WIP.

**Comment by Poslovitch** [comment]
I will work on it today ;)
I was just trying to find a proper way to delay the fly whrn going outside of island boundaries ;)
