### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Gaurav99** [tastybento/askyblock#231]
There's a very weird bug that can result in duping that some of my players have been caught abusing. You can get someone their island resets back (if it hits 0) if your server limits it. You need 2 players - player A and player B.
If player B runs out of resets, player A simply invites B to his/her island, and player B joins A's island then leaves. Player B now gets a new island and all of their resets back. They have to wait the "invitewait" time to be reinvited of course, but it's still a simple way to reset your resets.

**Comment by tastybento** [comment]
Do you have any recommendation of how this could be avoided?

**Comment by meytro** [comment]
Don't give them new resets after getting kicked from an island should solve the problem, shouldn't it?

**Comment by Gaurav99** [comment]
Ideally the above (not giving them new resets after getting kicked from or leaving an island). I'm not entirely sure how your plugin works because I didn't make it, so I don't know how difficult this would be to implement. If it would require a redo of that section or something like that, we could try to figure out a workaround solution.
Thanks for your help!

**Comment by tastybento** [comment]
Okay, I'll look into it.

**Comment by tastybento** [comment]
Hmm, seems I knew about this:
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/commands/IslandCmd.java#L1778

**Comment by tastybento** [comment]
Fixed in b6e4728.
