### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by doitliketyler** [tastybento/askyblock#232]
Just wanted to report this error showing up on server startup. I'm running on Spigot 1.9.4 and the latest version of AcidIsland.

19.05 17:30:03 [Server] ERROR [AcidIsland] Could not parse biome FLOWER_FOREST using default instead.

**Comment by tastybento** [comment]
You have "FLOWER_FOREST" in your config.yml or somewhere. It's no longer a valid biome in 1.9. You should change it to just FOREST if you want to get rid of the error.

**Comment by doitliketyler** [comment]
Ok. Does that mean they removed the Flower Forest? What about the Flower Forest specific flowers?

**Comment by tastybento** [comment]
Yeah, they removed it. I think the flowers just got in the forest now. Here's the biomes:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html

**Comment by doitliketyler** [comment]
Dang...I had no idea that happened. Thanks for the info.
