### ISSUE TITLE
Level unlock issue when adding new challenges

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#235]
So this is sort of a bug, but it also makes sense as to why it happens, even though it really should be blocked from happening. Let me describe what I am talking about in more detail below:

- I have challenge tiers requiring EVERY challenge be done to move ahead
- Player1 has the Competent challenge tier unlocked and gets the unlock rewards
- I add a new challenge to the Novice challenges
- Player1 now gets bumped down to Novice challenges only
- Once completing new challenge, gets the unlock rewards a SECOND time

Could there be a way that it tracks players tier unlock rewards, so if they get bumped down due to some challenge updates, they can't reap the rewards again? I like letting my community suggest challenges, and we add new ones here and there, but it gives lots of players a big advantage when they are above the new challenge and get all the unlock rewards again.

Hope that makes sense, thanks for reading!

**Comment by tastybento** [comment]
I think this can be done. Unlocking levels will be a one-time event.

**Comment by tastybento** [comment]
Added in 	3204a5b

**Comment by SpaZMonKeY777** [comment]
And this will be reset when challenges are reset for a player correct? Just want to double check, so players can re-do them if they restart their island, etc.

**Comment by tastybento** [comment]
@SpaZMonKeY777 Thanks. Addressed in 4b6279c.
