### ISSUE TITLE
Disable villager use on island visit

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#236]
I have searched to see if it's been requested before, but did not see anything (to my surprise).

Would it be possible to have a config/permission for players to have an island setting to enable/disable their island visitors from being able to trade with their villagers? Some of my players like it being open to trade for their shop areas, but others do not like it as they don't want certain trades locked out, etc.

**Comment by tastybento** [comment]
Done in 	cf2ab0f
