### ISSUE TITLE
Add some new translations

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#237]
I would like to translate messages about blocks limits. For example: Island Armor Stand limit of 15 reached!.
The current limit message for hoppers doesn't work (hopper: "Island hopper limit of [number] reached!"). I translated it, but it keeps showing the english message.

**Comment by tastybento** [comment]
Use this:

'''moblimits: 
  entity: "Island [entity] limit of [number] reached!"

**Comment by tastybento** [comment]
It's missing in the yml files but in the code. I'll add it.
