### ISSUE TITLE
Feature Request - Whitelist of mobs not to butcher

### ISSUE THREAD

**Issue by roastnewt** [tastybento/askyblock#24]
Our players enjoy the feature where hostile mobs are butchered when you /is.

However, there are a couple mobs we would like to be exempt from this, namely withers and zombie villagers in the process of being healed.  Is there any way to add a whitelist of mob types to not be killed by /is?

**Comment by tastybento** [comment]
I will add this to 2.9.4. There is extra functionality in 2.9.4 for the Wither experience, so this will tie in well with that.

**Comment by tastybento** [comment]
Complete.
