### ISSUE TITLE
ASkyBlock Lag Timings Link

### ISSUE THREAD

**Issue by FiratKayaHD** [tastybento/askyblock#240]
Hello my friends. My server is 1.8.8 but very big lagging. Tps down 10-11.
I use last version this plugin.

My timings link: http://www.spigotmc.org/go/timings?url=16614152

**Comment by tastybento** [comment]
Hoppers are killing you.  You can limit hoppers in config.yml. Also, limit villagers per island to limit iron farms. 
Change the hopper timings in spigot.properties. 
Finally, switch off X-ray because you don't need it.

**Comment by FiratKayaHD** [comment]
Hello my new entitylimit in config.yml

   entitylimits:
     #BANNER: 20
     #ITEM_FRAME: 30
     #FURNACE: 10
     CHEST: 50
     #TRAPPED_CHEST: 50
     #ENDER_CHEST: 1
     #JUKEBOX: 5
     #DISPENSER: 5
     #DROPPER: 5
     #SIGN: 10
     #MOB_SPAWNER: 10
     #NOTE_BLOCK: 5
     #ENCHANTMENT_TABLE: 5
     #BEACON: 12
     #SKULL: 50
     #DAYLIGHT_DETECTOR: 10
     HOPPER: 30
     REDSTONE_COMPARATOR: 30
     #FLOWER_POT: 20
     #PAINTING: 5
     #ARMOR_STAND: 5

Good?

**Comment by FiratKayaHD** [comment]
What do you suggest for villagerlimit ?

**Comment by tastybento** [comment]
I recommend 10. That will enable each player to make one iron farm (you need 10 villagers to have an iron golem spawn)

**Comment by tastybento** [comment]
What are your spigot.yml settings? Try increasing these and see what happens to your timings. For example:

    ticks-per:
      hopper-transfer: 16
      hopper-check: 16

**Comment by FiratKayaHD** [comment]
ticks-per:
  hopper-transfer: 1
  hopper-check: 1

My spigot.yml good?

**Comment by tastybento** [comment]
No, you need to go the other way - make them bigger.

**Comment by tastybento** [comment]
If they are 1 now, then set them to be 8. Then try 16 if that helps.

**Comment by FiratKayaHD** [comment]
continue lag :(

**Comment by meytro** [comment]
@tastybento hopper-check doesn't work anymore in Spigot - only way to reduce hopper lag is the limitation if you don't want to use custom software.

**Comment by tastybento** [comment]
@FiratKayaHD are you on the latest version of 1.9?

**Comment by tastybento** [comment]
@meytro - thanks it looks like you are right about hopper-check - I can't see anything about hopper-transfer being removed though. Do you have any links on this?

**Comment by meytro** [comment]
hoper-transfer still decreases/increases the transfer speed but it doesn't have an impact on the server performance.

**Comment by FiratKayaHD** [comment]
My spigot is paperspigot 1.8.8. Plugin version is 3.0.8

**Comment by tastybento** [comment]
@meytro bummer. Not sure there's much to do if there's already too many hoppers then.
