### ISSUE TITLE
"Island Protected"

### ISSUE THREAD

**Issue by Jafforo** [tastybento/askyblock#242]
I read this - https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions

But it wasn't really useful. I am getting this error, even though my island isn't at 0, 0, and don't have WorldGuard (or protection plugins).

Not sure, what's causing this.

Plugins: http://prntscr.com/b7yiha

Error: http://prntscr.com/b7yila

**Comment by tastybento** [comment]
When you are on the island and do /asadmin info what do you see? If it says no one owns the island the do /asadmin info (playername). If it says the player owns the island then the islands.yml file is out of sync with the player files. Stop the server, delete the file and restart so it can be regenerated. 
If the player info says they don't have an island, register them.

**Comment by Jafforo** [comment]
Fixed, thank you.
