### ISSUE TITLE
locationIsOnIsland

### ISSUE THREAD

**Issue by mastercake10** [tastybento/askyblock#243]
The method com.wasteofplastic.askyblock.ASkyBlockAPI.getInstance().locationIsOnIsland(args) is outdated, it only returns the island in overworld, not in nether. Please fix,
hear from you.

**Comment by tastybento** [comment]
Yes, that method returns a boolean and checks in the location is on the home island of the player (which could be in the overworld or the if the player started in the nether). As the dimensions between nether and overworld are identical,  you can check either locations just by changing the world to use the overworld. 
Example:
locationIsOnIsland(location.toVector().toWorld(ASkyBlock.getIslandWorld()).
