### ISSUE TITLE
Enable falling while TP'ing for pearls, etc

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#244]
So a few of my players recently told me that if they are falling, they can't use enderpearls or eat Chorus  fruit in hopes of saving themselves. And I imagine it's because the teleport event must be cancelled out in all different ways?

Is it possible to allow these kinds of teleporting (pearls and chorus fruit) to be enabled as a great use for these items? It's not a guaranteed way to survive, but would be a nice touch to be able to allow these while having TP commands disabled (like /is, /is go, etc).

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#63
