### ISSUE TITLE
Guests can kill animals with a flame bow

### ISSUE THREAD

**Issue by meytro** [tastybento/askyblock#245]
There is currently a bug which allows guests to kill animals on other islands with a bow. The plugin says, that the island is secured but the animal still gets damaged/killed.

Problem occurs with version 3.0.1 (https://github.com/tastybento/askyblock/releases/tag/3.0.1)

**Comment by meytro** [comment]
Added: Issue only occurs if the guest uses a flame bow.

**Comment by tastybento** [comment]
Thanks. I'll look into it. It's probably that the fire isn't being canceled.

**Comment by tastybento** [comment]
Hmm, I can't replicate this. Can you give me more info on how to make this happen? I enchanted a bow with Flame and then went to an island and I can't hurt any animals at all.

**Comment by meytro** [comment]
Well I made the same: Enchanted a bow with flame, went to an island and use the bow with arrows to shot animals/armorstands at they start burning.

**Comment by tastybento** [comment]
What are the island settings? Is hurting animals allowed on the island? Are you cooped? Do you have bypass protection permissions? Does it happen for all players, or just some?

**Comment by meytro** [comment]
This are the default island settings which got not changed: http://pastebin.com/bWRDeDYg
Every player/island is impacted without /is coop or /is invite.

**Comment by meytro** [comment]
I'm using Paper 761

**Comment by tastybento** [comment]
Okay, I've confirmed that this issue occurs on Paper, but not Spigot. Now, let me see if I can do anything about it.

**Comment by tastybento** [comment]
Fixed with 3e4b5c6

**Comment by tastybento** [comment]
@meytro - have you found any of the settings in paper to improve performance, e.g., of hoppers?

**Comment by meytro** [comment]
What do you mean with "found"?

**Comment by tastybento** [comment]
I mean, have you made any settings in paper.yml that improve performance when running ASkyBlock vs regular Spigot? In other words, why do you run Paper Spigot?

**Comment by meytro** [comment]
I only use it because of the use-hopper-check feature and the redstone optimiztion. 
Beside that: Pretty bad software with a lot of bugs.
