### ISSUE TITLE
Acid bug with gamemode 3

### ISSUE THREAD

**Issue by renzotom** [tastybento/askyblock#246]
Hello, here in ASkyBlock and AcidIsland, when players use gamemode 3 and there is in config:
   # Ops receive damage from acid (Set to true if you want Ops to play properly)
   damageops: false
they receive damage, when they have gamemode 3. When they have gamemode 1, they don´t receive damage, but I think, in gamemode 3 it is very bad....

**Comment by tastybento** [comment]
Gamemode 3 isn't currently supported. I'll have to study this.
