### ISSUE TITLE
Dupe glitch (needs attention ASAP)

### ISSUE THREAD

**Issue by HunterGPlays** [tastybento/askyblock#247]
On our server we run PlayerVaults. While on someone else's island, you can stand on top of a lilypad, break and jump and you will be glitching in the lilypad. This makes you able to dupe items.

I've made a video to explain this because it's extremely bizarre. I can't patch it because I don't know the cause of it.
https://www.youtube.com/watch?v=wyASnKkWRiQ

Pardon me if it's something to do with PlayerVaults, not Askyblock. Just let me know and I'll ask on their issue tracker.

**Comment by tastybento** [comment]
What version of the server are you running and what version of the plugin? I tried to duplicate it, but I couldn't get a glitch on my server. I wasn't running PlayerVaults though yet.

**Comment by HunterGPlays** [comment]
Never mind, it turns out it's PlayerVaults. My bad. Anyway, I've quickly made a [patch](terrocidepvp.net/files/PlayerVaultsDupePatch.jar) for it.
