### ISSUE TITLE
About ASkyblock

### ISSUE THREAD

**Issue by Airnexus** [tastybento/askyblock#248]
Hi :) I love your plugin and my server is using it too. Also, my server 's main topic is skyblock, so we use it very much, but i get a problem. The problem is some players will lost their own island's permission of control although he is the owner of that island , also he only can place blocks and open chests but can't destroy. In addition, there has no any msg when he leave or enter island. The next problem is some players will lost their own island. I mean the whole island. So when he type /is home or /is , he will fell down to empty and die. Could you help me to fix the problem?

Sorry for my poor English and thx a lot :)

**Comment by tastybento** [comment]
I expect that the server crashed at some point and the islands.yml file is now out-of-sync with the player files. To fix, you can do the following:

1. Stop the server (very important)
2. Move the islands.yml to islands.old
3. Restart the server - the islands.yml file will be remade from the player files in the player's folder

That *should* work.
