### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by roastnewt** [tastybento/askyblock#25]
When a specific player does /island, it crashes the server with an out-of-memory error.  Here's the thread dump:

http://pastebin.com/raw.php?i=VJKehWg1

**Comment by roastnewt** [comment]
More info:  I think the memory issue is something to do with the subroutine that finds a safe spot to place someone when they teleport to their island?  His island is entirely covered in lava, there is no safe space.

**Comment by tastybento** [comment]
How big is the protection range?

**Comment by roastnewt** [comment]
400

**Comment by tastybento** [comment]
Okay, I know what's going on. It needs to go async.

**Comment by tastybento** [comment]
Fixed in 2.9.4.
