### ISSUE TITLE
Upgrading to 3.0.1 (config.new.yml, wrong version name).

### ISSUE THREAD

**Issue by BiGUNMAN** [tastybento/askyblock#252]
The new config generated writes at the top: 
'#' Config for ASkyblock V2.9.8.1
instead of
'#' Config for ASkyblock V3.1.0

This can't be intentional, and I'm running the new version: http://i.imgur.com/xQ9WUju.png

**Comment by tastybento** [comment]
That's probably your old config.new.yml. Delete it and a new, new one will be created.

**Comment by BiGUNMAN** [comment]
That's what I did before I reported the issue here.

**Comment by BiGUNMAN** [comment]
Oh wow.. I didn't stop the server before I deleted it and so I guess that's how it lead to me being here. Thanks!

**Comment by tastybento** [comment]
Ok!
