### ISSUE TITLE
Acid doesn't hurt

### ISSUE THREAD

**Issue by stoneferry** [tastybento/askyblock#253]
Hi, newly installed world. I may have missed something silly here although I'm not sure what it is. Acid isn't hurting my player. 

config.yml
   aciddamage: 10

Island generator works find and I end up on an island with the tree + cow etc, but a dip in the water yields no damage as expected. 

Is it because my test player is listed in ops.json ?

**Comment by stoneferry** [comment]
Versions: 

latest spigot.jar as of today
vault installed
essentials for spigot (jenkins) 

MineCraft client v1.10

**Comment by tastybento** [comment]
Yep. If you want ops to feel acid damage you can set that in config.yml. See around like 310:

`   # Ops receive damage from acid (Set to true if you want Ops to play properly)
   damageops: false`
