### ISSUE TITLE
[ASkyBlockAPI] [HELP] Failure to get island location using a UUID

### ISSUE THREAD

**Issue by 7rory768** [tastybento/askyblock#254]
Code:
http://pastebin.com/D7Q88TdS
Output: ["7rory768:"](http://prntscr.com/bmeeuf)

Error:
> [16:41:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EnhancedGenerators v1.0 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:111) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:831) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92] at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] Caused by: java.lang.NullPointerException at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandLocation(ASkyBlockAPI.java:107) [?:?] at org.plugins.enhancedgenerators.EGMain.onInteract(EGMain.java:30) [?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [?:1.8.0_92] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [?:1.8.0_92] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [?:1.8.0_92] at java.lang.reflect.Method.invoke(Method.java:498) [?:1.8.0_92] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397] ... 18 more

**Comment by tastybento** [comment]
Seems to work for me. When does this happen? The null pointer exception is coming from the players object in ASkyBlock not existing. That is usually only the case when the plugin has not actually started properly. Does ASkyBlock actually work? I.e., can you make islands, etc. play the game. Please share when this occurs, step by step would be useful.

**Comment by 7rory768** [comment]
This occurs on the line that I have commented out in my code, I test it out by left clicking bedrock while on my askyblock island so...

**Comment by tastybento** [comment]
Right, I understand that it happens on Line 9. That calls the getIslandLocation method and then an error occurs in ASkyBlockAPI. That error should not occur unless for some reason, ASkyBlock is not running correctly. If you do /island, do you teleport to your island? What do you see if you do /asadmin info <your_name>?

**Comment by 7rory768** [comment]
http://prntscr.com/bmg3vp

**Comment by tastybento** [comment]
What do you see if you do /asadmin info on your island? If it says it is not owned, then that is the problem.

**Comment by 7rory768** [comment]
I just sent you a screenshot of it, look above

**Comment by tastybento** [comment]
No, it's two different things. **/asadmin info <player>** will give info on the player. If you go to the island itself and do **/asadmin info** only, then it checks what the island thinks is the owner. Are they both the same result?

**Comment by 7rory768** [comment]
They are exactly the same

**Comment by 7rory768** [comment]
I just tried Bukkit.broadcastMessage("" + this.skyblockAPI.getIslandLevel(e.getPlayer().getUniqueId())); becuse thats actually what I need to get for my plugin (the islands level) but I get this error

> [01:09:36 INFO]: 7rory768:
[01:09:36 ERROR]: Could not pass event PlayerInteractEvent to EnhancedGenerators
 v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:231) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd03
97]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:198) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd03
97]
        at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractMa
nager.java:111) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:831) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [s
pigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [s
pigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9
.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandLevel(ASkyBlockAPI
.java:78) ~[?:?]
        at org.plugins.enhancedgenerators.EGMain.onInteract(EGMain.java:42) ~[?:
?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        ... 18 more

**Comment by 7rory768** [comment]
Solved: I saved the API as a final variable outside of the onEnable method which broke the variable.
