### ISSUE TITLE
Companion spawning problem and damage upon starting island

### ISSUE THREAD

**Issue by BiGUNMAN** [tastybento/askyblock#256]
Either the companion mob isn't spawning or its falling off the island. Here's my config for the schematic:
http://pastebin.com/EztTsLkf

I took a look at the default config in the code and this seems to be right.

MC Version: http://i.imgur.com/KnI0HKs.png
Pl version: http://i.imgur.com/qQqacAw.png

Additionally, when using a custom island I noticed when the island first starts there's a chance the player might be damaged (have no idea from what, but it happened to me occasionally when I reset my island while setting up the schematic).

Edit: I just reset my island and in this case I lost around 4 hearts of health.

**Comment by tastybento** [comment]
There's different questions here. Regarding the damage do you have a spawn set up? If you don't, then during the reset, you are falling and then receive damage. I recommend you set up a spawn point somewhere (where you go when doing /spawn) or use the ASkyBlock spawn.

**Comment by tastybento** [comment]
For the companion thing, is there a patch of grass where the companion can spawn? They need at least one block.

**Comment by BiGUNMAN** [comment]
Yeah, there is a spawn setup using essentials spawn (but I think I found the issue nonetheless, something to do with priorities and multiverse). 

Regarding grass, I got a ton of it on the default island: http://i.imgur.com/hxBXCft.png - Here's just a small bit of the island where there is grass.

**Comment by tastybento** [comment]
Could you dropbox me the island schematic so I can try and see what's going on?

**Comment by BiGUNMAN** [comment]
https://www.dropbox.com/s/8yplijnjtwakna0/skyblock_island.schematic?dl=0

**Comment by tastybento** [comment]
The pig appears to be at the top of the mountain:
https://gyazo.com/692288de3eca78846c1790c3675d5230

**Comment by BiGUNMAN** [comment]
Can't believe I didn't notice that :/. I guess I have a feature request which would be an option to set a block for where the companion shoudl spawn, similar to the "spawnblock" option.
