### ISSUE TITLE
Issue with Item Limits

### ISSUE THREAD

**Issue by PegasusExe** [tastybento/askyblock#258]
There is a problem with the calculation of the island limits if the map gets pretty large.
Distance: 200
Protection Range: 200
 
At some point the limits of islands get counted for the island neighbour. Sometimes there are 1-20 rows of blocks which get counted for the neighbour island. Is it possible that Math.round causes this problems?
 
You use this:
Settings.islandStartX = Math.round((double) x / Settings.islandDistance) * Settings.islandDistance + Settings.islandXOffset;
 
and also for z coords.
 
Is there a chance too fix this problem?

**Comment by tastybento** [comment]
I'm not sure what you mean by "limits". 

When you set the distance and protection range to be the same value, you need to also set **overridelimit** to true in config.yml and also usually **cleanupblocks** too. Did you do that?

**Comment by PegasusExe** [comment]
I mean with limits everything that can be set on entitylimits. We have set the Hopper limit to 50 and the permissions of building and breaking are right. But the entitylimits get count for the neighbour island if they place for example a Hopper at the near of the neighbour island. We have set cleanupblocks and overridelimit to true.

**Comment by tastybento** [comment]
I see. Okay, please try this release:
https://github.com/tastybento/askyblock/releases/tag/3.0.1.2

**Comment by PegasusExe** [comment]
Same Issue still exists.

**Comment by tastybento** [comment]
Huh. Can you give me coordinates where it occurs?

**Comment by tastybento** [comment]
No answer. Closing...
