### ISSUE TITLE
[Feature] Nearby island info /is near

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#260]
Title kind of explains the feature all in it's own.

My community was suggesting this and I thought I would pass it along. They often have neighbors that are active but not online when they are, so a command like '/is near' would display some info about the islands in all 4 directions of them (north, south, east, and west). Naturally it wouldn't be a default command, but could have a permission to give to players that we wanted to give it to.

Thanks for reading!

**Comment by tastybento** [comment]
What info would it show?

**Comment by SpaZMonKeY777** [comment]
Just the owner's name of the nearby islands so they could contact them if needed, or island member names too? Can't think of much else, just a simple display of island owner info really.

**Comment by Jack-McKalling** [comment]
Maybe also just the island level besides that. So that you can figure out the "size" of an island without needing to wait or ask.

**Comment by tastybento** [comment]
Interesting. It could be done. 
That's actually similar to the Dynmap info. I assume you've see that too right? It's not within the game of course. Also, it is possible to find player's levels by doing /is level <name>.

**Comment by Jack-McKalling** [comment]
Yes I'm aware of /is level, but without /is near that command is useless since you don't know the owner's name. It would be convenient to have both the name and level bits in the same output. It would help identify which island is which, also.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#61
