### ISSUE TITLE
Joining someone's island resets player's reset limit

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#261]
So I have in my config the island resets limited at 5 per player, but some players of mine noticed that if you reach the limit, join another player's island, and leave, it resets that limit back to 0 for them. I can't think of any reason this would be intentional, so I can only assume it's a bug.

**Comment by tastybento** [comment]
That should not happen and was changed in 3.0.1 (it used to happen, but was removed). What version of the plugin are you using?
