### ISSUE TITLE
Custom Nether Island Spawnblock problem

### ISSUE THREAD

**Issue by BiGUNMAN** [tastybento/askyblock#262]
Hi, I recently setup a custom nether island but I seem to be spawning in a completely different area other then the configured spongeblock (there is only 1 spongeblock in the schematic, and it does get replaced with air, but the player (or atleast I when testing it) did not spawn where the sponge block was in the schematic. I'm in a completely different area.

Here's my config:
http://pastebin.com/pDdjmF8c

**Comment by tastybento** [comment]
That is correct behavior. The SPONGE is only for the original starting island. So, if the nether island was visible as a choice, then players could start in the nether and they would start at the block. If the player just teleports to the nether, they will arrive at a "safe spot" near to the center of the island. If they build a portal in the nether and light it, they will teleport to that portal exactly.

**Comment by BiGUNMAN** [comment]
Is there any way to specify exactly where the player should spawn when they first enter the nether without using bedrock? The nether island I constructed uses bedrock preventing me from using the center bedrock block to get the player in any good spawn location.

**Comment by tastybento** [comment]
Not right now. You might try using a portal in the schematic. That may work.

**Comment by BiGUNMAN** [comment]
I've tried making an island with a portal. What happens now is that when you enter the portal on your overworld island, it never teleports you.

**Comment by tastybento** [comment]
If you have an active portal in the nether and a player goes through a portal in the overworld, they should appear in the nether portal. That's what I meant.

**Comment by BiGUNMAN** [comment]
Yes, I've created an active nether portal in the nether schematic and saved it. Does not work. Their does seem to be a problem where when the schematic gets pasted the portal doesn't get pasted, which may be why it doesn't use the portal.

**Comment by Steev93** [comment]
~ Following

I have noticed this issue also. that when you do go through the portal you spawn anywhere in that area not the "Spawn_Point" in the Config.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#60
