### ISSUE TITLE
My custom plugin wont allow ASkyblock to start?

### ISSUE THREAD

**Issue by 7rory768** [tastybento/askyblock#263]
I don't have much information about this but I was told by the person who request that I made this plugin that ASkyblock will randomly fail to startup but after replying my plugin and reloading it restarts without a problem. He said there are no errors.

Here is the only code that uses the ASkyblockAPI: http://pastebin.com/e6C0X4AU

Entire class: http://pastebin.com/jqMem6f8

**Comment by tastybento** [comment]
I'll try and look at this this week.

**Comment by 7rory768** [comment]
23 days to respond

**Comment by tastybento** [comment]
I'll ignore that comment.

There are a number of potential issues with your plugin.

- Does your plugin.yml have **depends: [ASkyBlock]** in it?
- As your plugin also depends on a world check, you may want to require either a **loadafter: [Multiverse-Core]** or **softdepends: [Multiverse-Core]** in it too.
- You don't do any check in onEnable that the ASKyBlock plugin is active. It's not essential, but good practice.
- In this line:
`int level = this.skyblockAPI.getIslandLevel(this.skyblockAPI.getIslandAt(e.getBlock().getLocation()).getOwner());`
it is possible for cobble to be generated outside of island areas, or on an unowned island, in which case, the owner will be null and you'll get an NPE. I recommend you get the owner, do a null check and then proceed if it isn't null.

The fact that the plugin works after a reload indicates to me that it is a timing issue, that your plugin is either loading before ASkyBlock. That's my best guess without seeing the explicit error. If it happens again, get the console log and past bin it.

**Comment by 7rory768** [comment]
loadafter is not an option for plugin ymls http://wiki.bukkit.org/Plugin_YAML but I have now added the softdepend: [Mtuliverse-Core]. I also added the check in onEnable and the island null check but I think it is a load timing issue because  ASkyBlock seems to load islands up for a decent amount of time after all other plugins have loaded (possibly?). Either way the person I made this plugin for gave me absolutely no information on it's failure they just told me that their server did not startup but when they removed my plugin it did and apparently it corrupted all ASkyBlock data or something so he had to restart his server progress but I don't understand how that's even possible.

**Comment by tastybento** [comment]
There is a new event coming in 3.0.3 that will fire once all files are loaded and the plugin is ready to play. You can find it in the github code and try it out with the pre-release if you like. I'll close this now.
