### ISSUE TITLE
Flag for chorus fruit teleportation

### ISSUE THREAD

**Issue by Pokechu22** [tastybento/askyblock#269]
I think it would make sense to have a flag that disables chorus fruit teleportation on an island, much like the existing flag with ender pearls.

Here's some additional considerations when doing this that make it different from ender pearls, though, some of which could be implemented multiple ways:

* How should it work when the to island and from island are different?  Should one be able to warp from a protected island to an unprotected island, or should that be denied since it's using a chorus fruit on a protected island?
    * I personally think that either from or to islands being protected should cancel the teleportation
* Should the eating still go through (IE, give food points) and just the teleportation be denied?  Or should that also be denied?
    * I personally think that the eating should go through and the teleportation should be denied
* Should the default be to allow chorus fruit use on non-island areas?
    * I personally think so
* Should the default be to allow chorus fruit use at spawn?
    * I personally think they shouldn't
* If #244 is added/implemented, what should happen if the chorus fruit randomly attempts to teleport someone off their island?  It would suck to try to eat one to save oneself and only get a "Island Protected" in response.
* Should the default be to allow chorus fruit use on islands?
    * I'm not sure about this; maybe or maybe not.

I'm working on a patch to create such a flag, basing it off of the current ender pearl protection and the changes made in cf2ab0fefb179222d8e25f73304491cc96abb5af (which shows what is needed for new flags, more or less)

**Comment by tastybento** [comment]
Cool idea.
A basic option would be to use the same flag/icon as EnderPearl teleporting and just have it apply to chorus fruits too. 
If you do code it, remember to put it into the areas of code that apply to 1.9 and above only so that it's backwards compatible with 1.8 and earlier.
