### ISSUE TITLE
Minishop

### ISSUE THREAD

**Issue by SeVen94** [tastybento/askyblock#27]
Hello ;)
first i say sorry for my bad english 

I have a question.

How i can put enchanted diamond_pickaxe

we test it:

item23:
 material: DIAMOND_PICKAXE
 quantity: 1
 extra: 32:5
 price: 170 

but it doesnt work..

i hope you can help me

**Comment by tastybento** [comment]
Enchanted items are not supported (yet), so I'm marked this as an enhancement request.

**Comment by tastybento** [comment]
Not going to add.
