### ISSUE TITLE
permissions help

### ISSUE THREAD

**Issue by random1167** [tastybento/askyblock#270]
i had a issue with an admin and there account and i dont know if someone has added or changed a permission or if theres been a config update option thats been over looked...witch bring me here,
Is there a perm or a setting that dosent allow a user to leave/delete there island if no one else is on it ?.ive been looking and am still looking.
EDIT:
heres the ingame error
![k926n7g4](https://cloud.githubusercontent.com/assets/13611085/17011001/9debb5b0-4f4c-11e6-964d-9ca47eb9846d.jpg)

**Comment by tastybento** [comment]
/is leave is a command to leave a team. There isn't a command to just abandon an island. If a player wants to reset their island they can use /is reset or /is restart (same thing). If an admin wants to delete and island use /asadmin delete <name of player>
