### ISSUE TITLE
Make reset number depend on a permission

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#273]
For example, if player has askyblock.resetlimit.10, they can reset up to 10 times.

**Comment by aycgit** [comment]
Nah dont think this is needed, limiting resets is asking for problems

**Comment by Poslovitch** [comment]
It should be the last thing to do for 3.0.5 :D

**Comment by tastybento** [comment]
Moving out of 3.0.6.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#59
