### ISSUE TITLE
Add other required settings for challenges

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#275]
Add requiredExp
requiredLevel
permissionRequired - ties in with another request - should affect if a challenge is shown too.

**Comment by Poslovitch** [comment]
What would be "requiredLevel" ?

**Comment by tastybento** [comment]
The asker wanted it to be the required island level to complete the challenge. However, currently, for type 'level' challenges, we just put the level number in the requiredItems space. So, if we do this, then we should make it so that requiredLevel works for all challenges so that level challenges can use it as well.

**Comment by Poslovitch** [comment]
Okay. I'm fully rewriting how the challenges works, so I'll create a ChallengeType called "MEGA", that can handle it.

**Comment by Poslovitch** [comment]
Will be done in #349

**Comment by tastybento** [comment]
Handled in #566
