### ISSUE TITLE
/is setting not working

### ISSUE THREAD

**Issue by NyteriaRising** [tastybento/askyblock#276]
Tried to find a solution but really couldn't. Player are no longer able to change island settings. When they do /is setting the menu comes up but when they try change settings nothing happens... there are no errors. Is there a possible solution?

**Comment by tastybento** [comment]
Do they have the permission? askyblock.settings.* ?

**Comment by NyteriaRising** [comment]
They should do. However we have just switched to PEX. I will look into it thanks for the reply.
