### ISSUE TITLE
/island Major Bug

### ISSUE THREAD

**Issue by Muggyy** [tastybento/askyblock#280]
I am currently experiencing a major issue with this plugin that has NOT happened to me before and cannot identity what may have happened to cause this. Heres the error:

http://pastebin.com/JkBAs1by

**Comment by tastybento** [comment]
This error:
Caused by: java.lang.NullPointerException
    at com.wasteofplastic.askyblock.commands.IslandCmd.chooseIsland(IslandCmd.java:2860) ~[?:?]

Doesn't make sense. Line 2860 of IslandCmd.java is a return true statement and not in the chooseIsland method. Did you compile your own version? If so, what is line 2860 in your source code?

**Comment by Muggyy** [comment]
I did not compile my own version, and I even tried a few different old versions. I will try to check the source now.

**Comment by tastybento** [comment]
What version are you using?

**Comment by Muggyy** [comment]
Taco 1.8.8

**Comment by Muggyy** [comment]
Tried Paper and Spigot as well, same server version. Sorry for double post.

**Comment by Muggyy** [comment]
Downloaded directly from spigot. Download for it here: https://www.dropbox.com/s/id45d0u6xxowj78/askyblock.jar?dl=0

**Comment by tastybento** [comment]
What I'm trying to find out is the line number of the error. Do you see a different error line number with Spigot?

It's definitely something to do with creating a new island. What customization have you done?

 - are you using a custom schematic? 
- did you change the language files?
- did you edit the schematicsection of config.yml?

I need more info.

**Comment by tastybento** [comment]
Okay, I found the problem. For some reason, the player who is trying to make an island has no islands available to him based on permissions. None. Not even the default island. It looks like there must be a permissions setting placed on all the islands in the schematicsection?
I've fixed the plugin so it won't create an error, but in this case all the player will see is "Command not ready" and the console will say there are no valid islands for the player. So, you need to allow at least one islands to be valid, e.g., the default island.

**Comment by Muggyy** [comment]
Thanks a ton. Your comment actually got me thinking and I looked for a fix for a few hours and finally found that it was GroupManager. I switched to Pex now and everything is ok. No idea why it worked before with GM but at least it is now with Pex. Thanks for the help.
