### ISSUE TITLE
Add 2 more options in Config.yml

### ISSUE THREAD

**Issue by Creatif** [tastybento/askyblock#282]
Hello Tasty,
- Could you please add an option to disable minishop only ?:

```
   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false,
   # no money is used or give and the mini-shop is disabled.
   # If there is no economy plugin present anyway, money will be automatically
   # disabled.
   useeconomy: true
```

example:
`useminishop: false`
- Could you please add an option to enable/disable mobs spawning  by island (in /is settings ?) ?

```
   # Allow mob spawning
   allowmobspawning: true
```

and only user with the following permission could change settings:
`askyblock.settings.allowMobSpawning`

Thanks again for your amazing plugin,
iCrea

**Comment by tastybento** [comment]
The minishop can be disabled using permissions: **askyblock.island.minishop** To disable it, give players the **-askyblock.island.minishop** permission. This enables some players to have it and some not.

**Comment by tastybento** [comment]
I'll consider the mobspawning.

**Comment by Steev93** [comment]
and only user with the following permission could change settings:
askyblock.settings.allowMobSpawning

I believe this is something like this already! If they have they perm node they can on there own island but you can block this command "spawnmob" when they visit other islands

**Comment by Poslovitch** [comment]
To close.
