### ISSUE TITLE
i need help with the plugin i think i have a bug

### ISSUE THREAD

**Issue by KiritoHellWolf98** [tastybento/askyblock#283]
hey i was useing you plugin https://www.spigotmc.org/resources/a-skyblock.1220/ when i make a island it show i have it then when i leave it like to go to spawn it remove the island and will not let me go back it say (That warp is not safe right now. try again later.) and i have update the multiverse to 2.5-b717 and it then unloaded the worlds and not letting me reload them back and when i have a home set there is say (Error: Hole in floor!) 

thxs you for taking you time to read this i will love the help because i been trying to get it to work and i really need this plugin to work. 

and yes i have read the https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions

**Comment by tastybento** [comment]
I answered on Spigot or Bukkit.
