### ISSUE TITLE
getIslandMembers

### ISSUE THREAD

**Issue by TWSSYesterday** [tastybento/askyblock#285]
Is there a way to get the name of the players? At the moment I can only use getIslandOwnedBy. 
Thanks

**Comment by AlfieC** [comment]
getIslandMembers, if I recall correctly, will return a list of UUIDs - why not just do Bukkit#getOfflinePlayer on it and use getName()? Getting offlineplayer by UUID isn't that slow - or you could simply maintain your own cache.

**Comment by tastybento** [comment]
UUID's can be turned into player names using the Bukkit API as @AlfieC said.
