### ISSUE TITLE
Client crash on /is warps using 1.10.2

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#286]
I don't know if this also occurs using 1.10. But with 1.8 it doesn't crash.

**Comment by tastybento** [comment]
Need... more.... info...

crash log? console log? Steps to replicate?

**Comment by YellowZaki** [comment]
It seems so be a skull rendering issue, here is the client crash log:
http://pastebin.com/SMhsCa0f

**Comment by tastybento** [comment]
I recommend updating to the latest server version. Is the server offline? There's no Mojang UUID of 2b4b6389-7b02-3c8e-ad00-d05eec934277.

**Comment by YellowZaki** [comment]
Yes, it is offline. If you wanna join the ip is geoblock.es

**Comment by YellowZaki** [comment]
I removed the warp sign of the user that the log indicated and now it doesn't crash.

**Comment by tastybento** [comment]
Okay. Weird.

**Comment by tastybento** [comment]
I believe this is due to names > 16 chars. I'm going to try and prevent this.

**Comment by YellowZaki** [comment]
Nop. I guess there are some crashy skulls. The log indicated a rendering issue of the skull of the player "holhol". When I deleted his warp sign everything worked fine.
I also obteined his skull with give command and it also crashed me.

**Comment by tastybento** [comment]
Ahahah. Hmm. Okay, may be more difficult than I thought.
