### ISSUE TITLE
Island lock causing player deaths.

### ISSUE THREAD

**Issue by zquirrelz** [tastybento/askyblock#288]
There are a few of my players that have locked their island to visitors. This is fine and all, however when an island is locked the plugin seems to try to port the "offending" player outside of the protected area. When in a boat this causes damage and death coupled with being spammed with island locked messages. Would it be possible to change this action to tp the "offender" to either their own island or to spawn?

I also noticed an issue teleporting into the end. After the initial entrance no one can enter the end. Error message states that it is unsafe and players get "stuck" spammed with messages. This can be resolved by moving the spawn in the end manually via multiverse, but it would be nice to not have to manually set the spawn.

![javaw_2016-08-13_14-40-34](https://cloud.githubusercontent.com/assets/21014340/17646065/ed03ee42-6176-11e6-8a2c-caa00f828885.png)
![javaw_2016-08-13_14-40-44](https://cloud.githubusercontent.com/assets/21014340/17646066/ed05dbda-6176-11e6-9def-9426fff5d55e.png)

**Comment by tastybento** [comment]
The End isn't a supported part of the game. I don't know what's going on there.

For the island locking - player's should be teleported back to their island. Then if they don't have one, to spawn. If that isn't happening (you on the latest?) then something weird is going on.

**Comment by zquirrelz** [comment]
This is from v3.0.2.1 which was current when the issue happened I will be updating to the most current soon and will retest.

As far as the end, as I mentioned I can work around it by setting the end spawn location.

**Comment by tastybento** [comment]
Still happens? Can you give some steps/set up that replicates it?

**Comment by zquirrelz** [comment]
Sorry I have been very busy recently. I will be getting back to you on this by Wednesday 31/8/2016. I have not had a chance to test it out again.

**Comment by zquirrelz** [comment]
https://youtu.be/k_iWG0oD08Y 

This is a video showing the issue. I created a brand new test server to film this on. The only plugins are AcidIslands 3.0.3.2, PeX 1.23.4, and Vault.

Travelling to a locked island causes the player to fall out of their boat and die.

**Comment by tastybento** [comment]
Thanks. I'll look at it. What I see though is that the player is trying to row into a locked island. That causes them to be teleported back out a bit to keep them out. Teleporting in a boat is temperamental and can cause ejection. I will see if there's a solution

**Comment by tastybento** [comment]
This was improved in recent builds. I'm closing for now because there isn't much more that can be done.
