### ISSUE TITLE
Feature: Renaming islands (Welcome message)

### ISSUE THREAD

**Issue by TWSSYesterday** [tastybento/askyblock#289]
Example command:
/is rename "The kingdom of the dead"
Example output: You have successfully renamed your island's welcome message to "The kingdom of the dead".
When someone teleports there: "Welcome to The kingdom of the dead"

**Comment by tastybento** [comment]
Island naming is supported already using the **/is name** command...

**Comment by TWSSYesterday** [comment]
Does the name come up in the message? I meant to add a "Probably in here already but..."

**Comment by tastybento** [comment]
Yes, it does.

**Comment by TWSSYesterday** [comment]
No need for this ticket, thanks :)
