### ISSUE TITLE
Challenges with mob spawn eggs require items doesn't work

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#290]
Here is the challenge config:

    spawneador:
      friendlyname: 'Spawneador'
      description: 'Craftea 1 huevo spawn de: creeper, esqueleto, araña, zombie, pigman, bruja y blaze'
      icon: 383
      level: 'Avanzado' 
      type: inventory
      requiredItems: 'MONSTER_EGG:CREEPER:1 MONSTER_EGG:ZOMBIE:1 MONSTER_EGG:WITCH:1 MONSTER_EGG:BLAZE:1 MONSTER_EGG:SPIDER:1 MONSTER_EGG:SKELETON:1 MONSTER_EGG:PIG_ZOMBIE:1'
      takeItems: true
      itemReward: 'MONSTER_EGG:RABBIT:1'
      rewardText: '1 huevo spawn de conejo'

And here is the console error:
http://pastebin.com/URAwsjYb

**Comment by YellowZaki** [comment]
Bump

**Comment by tastybento** [comment]
Not supported. Format of required items is:

Material:Qty
or
Material:DamageModifier:Qty

**Comment by tastybento** [comment]
These eggs are not normally craftable. Do you have some mod that enables that?

**Comment by YellowZaki** [comment]
I have a lot of custom craftings on my server.

**Comment by YellowZaki** [comment]
Now I use:
      requiredItems: 'MONSTER_EGG:50:1 MONSTER_EGG:51:1 MONSTER_EGG:52:1 MONSTER_EGG:54:1 MONSTER_EGG:57:1 MONSTER_EGG:66:1 MONSTER_EGG:61:1'

But it tells me I don't have the required items.

**Comment by tastybento** [comment]
Numbers don't work any more with 1.9+ servers. They got rid of the "damage" thing and moved to names (meta data). It's a real pain all round unfortunately. To do what you want will take explicit coding of the egg things.

**Comment by YellowZaki** [comment]
So do I delete the challenge or will you fix it?

**Comment by tastybento** [comment]
Delete the challenge for now because it isn't supported. I'm super busy at real work right now so I can't add stuff right now. We can leave this ticket open as a marker to be done.

**Comment by YellowZaki** [comment]
Ok thanks. I have replace it to the EnderKnight challenge XD.
One question, if I add more than 18 challenges to a level, will it be 3 rows in the GUI? I have 6 levels with 13 challenges each (78 challenges in total) and I want to add more cool challenges but I don't want to create more levels.

**Comment by tastybento** [comment]
You can have up to 49 items in the inventory, so you should calculate how many levels you need and that will tell you how many challenges.
