### ISSUE TITLE
/is warps kicking players

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#292]
```
[23:55:10 INFO]: Player123 issued server command: /is warps
[23:55:10 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 33557 bytes encoded, max 32767)
```

```
>ver askyblock
[17:02:49 INFO]: ASkyBlock version 3.0.3.1
[17:02:49 INFO]: A SkyBlock Plugin
[17:02:49 INFO]: Author: Tastybento
```
```
>ver
[17:03:06 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[17:03:06 INFO]: Checking version, please wait...
[17:03:07 INFO]: You are running the latest version
```

There were no issues before when we were using 3.0.0.8.

**Comment by tastybento** [comment]
Hmm, it may be that there is a sign that has > 16 chars in the line placed by a hacked client. (Based on this discussion https://www.spigotmc.org/threads/error-io-netty-handler-codec-encoderexception-string-too-big-was-32789-bytes-encoded-max-32767.71401/)

I need a copy of your world and ASkyBlock folder. Can you drop box them to me? I'll then track down the offending sign/player and build in some mitigation code.

**Comment by L4BORG** [comment]
World is huge, because its been forever since we had last reset...

Is it normal that client would get disconnected right away? Before they would even saw GUI that should show up after executing /is warps?

Also I was under the impression that this was patched in development of 1.8 and we've been running latest 1.8.8 for months now...

**Comment by L4BORG** [comment]
Also /is warp <playerName> works, from what I saw so far it's GUI that is kicking players (before it's rendered) for some reason.

**Comment by tastybento** [comment]
So, I don't know what is actually causing the issue. It could be a sign or it could be something else. What I'd like to do is add some debug code that will spit out info on each sign that is being processed until it gets to the offending one and then find out what is odd about it. It may be something to do with the name of a player (maybe too long?) or the sign or the head, or something.
If the world is too big, then all I can do is give you a build for you to try.

**Comment by L4BORG** [comment]
Yeah, I understand, we had some players bypassing bungeecord awhile ago and some crashes, so there might be some invalid data or even players with invalid usernames (dots, strange chars, ...) I was kinda hoping /is purge would "validate" and remove invalid data.

I'm almost certain there might be some players with invalid usernames left somewhere... I wouldn't mind if AI would skip and/or purge those islands since those players can't join anymore...

**Comment by L4BORG** [comment]
For example name-uuid.txt contains entries such as: '>10lucifers10<' (with single quotes)
and: trokutinjo:d (with colon which would broke .yml files?)
or: "\tmarceleddie" (with double quotes and backslash)

but I have no idea how to clean up those and what would happen if I just remove them from name-uuid.txt?

**Comment by tastybento** [comment]
Purge should destroy any islands that haven't been used for a while. It doesn't validate any data though. 
Do you have a copy of your server you can run a test on? Shall I give you a debug version?

**Comment by tastybento** [comment]
You can safely delete any lines you want from name-uuid.txt (when the server is shutdown).
Also, you can search for associated UUID's in other files too, like the warps.yml and in the player's folder and delete them from there.

**Comment by L4BORG** [comment]
DId some purging and now the issue is gone. I assume it was bad player name...
