### ISSUE TITLE
Suggestion: Add minimum island level required for welcome warp

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#294]
The reason for this is pretty simple, new players / abusers are trying to ruin other players experience by creating welcome warps on islands with traps, lag machines, etc...

A simple limitation, minimum island level required for creation of welcome warps would prevent this in most cases.

**Comment by tastybento** [comment]
There is a permission associated with warp signs. It can be given via a challenge to achieve a certain island level, e.g. 10. This was in the original challenge set but I removed it. You can add it quite easily.

**Comment by Poslovitch** [comment]
Done. Have to be closed.
