### ISSUE TITLE
Persitent coops not so persistent ;)

### ISSUE THREAD

**Issue by Creatif** [tastybento/askyblock#298]
Hello

a little issue with the last askyblock version:
with:
   persistentcoops: true

coops still be removed after each reboot of my server.

Other bugs (wrote on spigot: player can't tp when they are flying, and loginremovemobs remove mobs even if it's set on false).

Skymine

**Comment by tastybento** [comment]
Hmm, I can't replicate that issue with the latest version. It was an issue with an earlier one. Which one are you using? Can you double check? There is a file coops.yml where the names of coops are stored. Does that exist okay?

The other issues have been resolved with recent commits.

**Comment by Creatif** [comment]
Hello tasty,

it seems resolved by itself. I don't understand x).

Sorry,
iCrea
