### ISSUE TITLE
Challenge Error

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#301]
Running 3.0.3.1

Error Code on completing this Challenge...

>     timetopaythetax:
      friendlyname: 'Tax Time'
      description: 'Pay the tax''s $5,000'
      icon: DIAMOND
      level: 'level5'
      type: inventory
      # You can require the player has a certain amount of money for inventory challenges.
      # Remember to mention it in the description!
      # If takeItems is true, the money will be removed, so you may want to give it
      # back in the reward.
      requiredMoney: 5000
      takeItems: true
      itemReward: 'DOUBLE_PLANT:0:6'
      rewardcommands: ''
      rewardText: 'Sun flowers'
      moneyReward: 155
      expReward: 125
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0

ERROR Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.1
29.08 16:52:17 [Server] INFO org.bukkit.event.EventException
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
29.08 16:52:17 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
29.08 16:52:17 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.1
29.08 16:52:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
29.08 16:52:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source) ~[?:?]
29.08 16:52:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
29.08 16:52:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO ... 15 more
29.08 16:52:17 [Server] INFO Caused by: java.lang.NullPointerException
29.08 16:52:17 [Multicraft] Skipped 9 lines due to rate limit (30/s)
29.08 16:52:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
29.08 16:52:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
29.08 16:52:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
29.08 16:52:17 [Server] INFO ... 15 more

**Comment by tastybento** [comment]
Fixed in https://github.com/tastybento/askyblock/releases/tag/V3.0.3.3

However, you still need to have a requiredItems line, with ''. So use this:

`
    timetopaythetax:
      friendlyname: 'Tax Time'
      description: 'Pay taxes $5,000'
      icon: DIAMOND
      level: 'level 5'
      type: inventory
      requiredItems: ''
      requiredMoney: 5000
      takeItems: true
      itemReward: 'DOUBLE_PLANT:0:6'
      rewardcommands: ''
      rewardText: 'Sun flowers'
      moneyReward: 155
      expReward: 125
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
`

**Comment by Steev93** [comment]
Will do thanks :)

**Comment by Steev93** [comment]
@tastybento 

Updated to the latest version 3.0.3.3

However;

> 
30.08 18:20:58 [Server] ERROR Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.2
30.08 18:20:58 [Server] INFO org.bukkit.event.EventException
30.08 18:20:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
30.08 18:20:58 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
30.08 18:20:58 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.2
30.08 18:20:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
30.08 18:20:58 [Server] INFO at sun.reflect.GeneratedMethodAccessor299.invoke(Unknown Source) ~[?:?]
30.08 18:20:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
30.08 18:20:58 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
30.08 18:20:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
30.08 18:20:58 [Server] INFO ... 15 more
30.08 18:20:58 [Server] INFO Caused by: java.lang.NullPointerException
30.08 18:20:58 [Multicraft] Skipped 13 lines due to rate limit (30/s)

**Comment by Steev93** [comment]
This update has made it disappear from challenges in game using /c
