### ISSUE TITLE
New Nether Island Error & Crash Report

### ISSUE THREAD

**Issue by BiGUNMAN** [tastybento/askyblock#302]
Here's the error: http://pastebin.com/UzwipkYV - It worked fine before.

Here is the Crash report: http://pastebin.com/S4LPvqXt - Seems to be involved with ASkyblock, but I may be wrong. 

SkyBlock Version: 3.0.3.2

**Comment by Steev93** [comment]
Did you just update this and it caused the Error ?

**Comment by BiGUNMAN** [comment]
Seems like it.

**Comment by BiGUNMAN** [comment]
Thats what it seems like

**Comment by tastybento** [comment]
Do you have some logging switched on in buycraft? That plugin is trying to log every block that is being pasted when a new island is made.

net.buycraft.plugin.bukkit.logging.BugsnagGlobalLoggingHandler.publish(BugsnagGlobalLoggingHandler.java:35

**Comment by BiGUNMAN** [comment]
No, BuyCraft doesn't log anything in terms of blocks, or at least shouldn't.

**Comment by tastybento** [comment]
That appears to be where the error occurred when pasting the nether island:

```
[18:41:36] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to ASkyBlock v3.0.3.2
java.lang.StackOverflowError
    at net.buycraft.plugin.bukkit.logging.BugsnagGlobalLoggingHandler.publish(BugsnagGlobalLoggingHandler.java:35) ~[?:?]
`

Does this continuously happen, or was it just a one-off?

**Comment by tastybento** [comment]
I can't do anything on this, sorry.
