### ISSUE TITLE
Island level prefixes 

### ISSUE THREAD

**Issue by nate9790** [tastybento/askyblock#303]
How can i change colors for different milestones? 
I see it on big servers, and they don't do it manually

**Comment by tastybento** [comment]
I don't know exactly what you mean. Can you give an example?

**Comment by nate9790** [comment]
Basically what i'm trying to do is having milestones for different island
levels.
1000 Island levels gets gold color
5000 gets blue
10000 gets red
Etc... Stuff like that

**Comment by tastybento** [comment]
I don't know how those servers do it exactly, but you can create challenges that require an island level and then run commands when the player completes the challenge that changes their chat prefix, gives them a permission or promotes their rank.

**Comment by nate9790** [comment]
Dang... Thanks though
