### ISSUE TITLE
Add New island of ASKYBLOCK

### ISSUE THREAD

**Issue by NyCoSD** [tastybento/askyblock#305]
[FR]
Bonjour @tastybento ,
- **Je vous contact aujourd'hui pour vous invitez a mettre en place un système identique au nether mais avec l'end. J'ai vu les issues et j'ai donc pu voir que je ne suis pas le premier a le demandé. Voyant vos réponses je me sens obligé d'insister sur ce point qui pour moi est important. Cela mettrais un coup de jeune à votre plugin. je comprend que cela soit long à mettre en place. Mais je vous invite quand même a y pensé sérieusement.** _J'ai actuellement mis en place mon end sur un monde a part. Mais je souhaiterais vraiment cette option !_
- _Un autre petit point que j'aimerais traité: la possibilité que le monde ASkyBlock soit mis en monde principale et unique du serveur pour alléger les serveurs. Ceci n’étant en rien essentiel mais peux êtres bien a voir._

Cordialement,
_NyCoSD_

**Comment by NyCoSD** [comment]
[EN]
Hello @tastybento ,
I'm contacting you today to invite you to set up a system identical to the one for the nether but for the end . I have seen the issues so I could see I 'm not the first to ask. Seeing your answers I feel compelled to emphasize this point that for me is important. This would put a makeover to your plugin. I understand this to be long to set up . But I invite you to seriously considered them . I have now set up my end on a world apart . But I really like this option!

Another small point I would talk about : the possibility that the world " ASkyBlock " becomes the single main server world to alleviate the servers. This is nothing essential but if could be looked into.

Kind Regards,
NyCoSD

**Comment by Creatif** [comment]
Another small point I would talk about : the possibility that the world " ASkyBlock " becomes the single main server world to alleviate the servers. This is nothing essential but if could be looked into.

It's already possible ...

(c'est actuellement possible. tu as juste a changer la map par défault, qui est world, par ASkyBlock, au niveau bukkit si je me souviens bien.)

**Comment by tastybento** [comment]
I think that adding The End would be an interesting "Next Chapter" and when I get some time to focus, I'll look at it. 

For running ASkyBlock as the main world, see this in the FAQ:
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#how-do-i-set-up-my-server-so-that-askyblock-is-the-main-world

**Comment by NyCoSD** [comment]
Thanks :)

**Comment by NyCoSD** [comment]
Hello,
I am contacting you today to ask you if it would be possible to remove the fact that the mouse back to the middle of the screen when were full of challenges and even that is being sold in the Minishop
Kind Regards,
NyCoSD

**Comment by tastybento** [comment]
@NyCoSD I cannot control the cursor, sorry. But you can still click multiple times and it will work.

**Comment by dracnis** [comment]
Bon je veux pas dire mais il y a un an j'ai proposé le code pour l'end ainsi que le curseur et pour finir pouvoir customiser les menus pour pas juste avoir un truc à la suite en échange de devenir un collaborateur, il y avait aussi d'autre code que j'avais déjà donné et qu'il a prit mais a refusé mon marché, donc tout ceci est faisable ( surtout se curseur c'est même très simple ) il y avait aussi un maj+clic pour compléter en boucle le challenge ( genre tu peux 50x ça te dit complété x50 au lieu de 50 messages de 4 lignes )

**Comment by Poslovitch** [comment]
Tasty est américain, et je doute qu'il comprenne ton message, c'est pour ça que je te réponds : 
Le développememt des îles de l'End n'a pas commencé ; et pour cause, c'est un sacré challenge. C'est personnellement au dessus de mon niveau, et sera probablement très chronophage.
Le grade "Collaborateur" sue GitHub est automatique : tu codes pour le plugin, tu fais une pull request et si l'auteur merge, tu es considéré comme Collaborateur. Sur bukkit/spigot, je suis à ce jour l'un des plus grands collaborateurs (j'ai codé la majorité des fonctionnalités de la 3.0.4 et de la future 3.0.5), et pourtant peu de personnes savent que je travaille sur ASkyBlock.

Je ne comprends pas cette histoire de curseur :  dans Minecraft, lorsq'un menu s'ouvre, le curseur se replace au milieu de l'écran, et ça on y peut rien du tout.

Je peux créer un clic spécial pour compléter d'un seul coup le plus de fois possible un challenge. Ça arrivera probablement fin décembre, début 2017.

**Comment by dracnis** [comment]
Niveau challenge le plus difficile c'est de faire un générateur custom pour l'end sinon c'est très simple de le rajouter, en 4h de travail je l'ai fais.
Le grade que je demandais était sur bukkit dans author histoire d'être pris en compte.
Pour cette histoire de curseur comme dis c'est très simple, il s'agit juste d'une ligne de code à supprimer.
J'avais proposé  de recoder quasiment tout le plugin ( ce que j'ai fais pour mon serv il y a un an ) et je suis surpris que la version officielle n'a pas encore rattrapé la mienne. Le seul truc que je demandais était de me mettre dans la liste de auteurs sur bukkit.

**Comment by Poslovitch** [comment]
Je ne suis personnellement même pas dans la liste des auteurs du plugin, je n'ai été à vrai dire cité publiquement qu'une seule fois, dans une review sur Spigot où quelqu'un remerciait Tasty d'avoir codé MagicCobbleGenerator, ce à quoi il a toutefois répondu que le crédit me revenait ; et pourtant j'accepte d'y consacrer quasiment tout mon temps libre. Je refais actuellement complètement les challenges, et sont compris dans cette réfection leur fonctionnement, le menu, et de nouvelles fonctionnalités.

Si tu as réussi pour l'End, pourquoi alors ne pas faire une pull request, au lieu de relancer le ticket avec comme arrière pensée : "Regarde, moi j'ai réussi et toi t'as toujours pas avancé" ? Par égoïsme ?

Mes questions ne demandent pas de véritables réponses. Je te dis juste que cela ne sert à rien de se vanter de quelque chose que l'on a réalisé après l'avoir demandé, et que l'on garde pour soi au lieu d'en faire profiter le grand nombre qui adhère à cette proposition.

**Comment by dracnis** [comment]
Juste que je n'aime pas le fait que quelqu'un ai prit mon code sans même me remercier.

**Comment by tastybento** [comment]
Replaced by #396
