### ISSUE TITLE
Spawn Eggs dont work 1.9 from challenges

### ISSUE THREAD

**Issue by tyler489** [tastybento/askyblock#306]
Due to 1.9 changes spawn eggs use datatags instead of ids unfortunatly this breaks all the spawneggs in challeges please advise how to fix for 1.9/1.10

**Comment by tyler489** [comment]
similar to #300 the issue is data tags there,

**Comment by tastybento** [comment]
Spawn eggs as rewards are supported, but there's no support for having to _craft_ a spawn egg (which isn't possible in regular servers) and have it as a required item. To make a spawn egg as a reward, you just use the type of egg as a name instead of a number, e.g. MONSTER_EGG:PIG

**Comment by tyler489** [comment]
Thanks for the quick response... i did mean challenges does it have to be in all caps?

**Comment by tastybento** [comment]
It shouldn't be required, but if you find it only works if it is captials, let me know. I usually do a conversion to captials.

**Comment by tastybento** [comment]
Handled in #566
