### ISSUE TITLE
Disable redstone for offline players

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#309]
My server lag usually comes from the huge amount of redstone clocks active. It would be a mayor performance improvement to disable redstone on a island when the user is not online, so although the chunk is loaded (because of a near player island), the redstone wouldn't have impact.
In addition, all skyblock users know about the frustating lighting fps lag. There are some users that build something with pistons which is being expose to the void. And then, they can't disable it because it is imposible with 0fps. Players with near island have this issue too, so disabling redstone for offline players would solve it.
I think this is a difficult enhancement but I know you are good.

**Comment by tastybento** [comment]
I'll  look into this.

**Comment by Poslovitch** [comment]
It looks simple : listen to BlockRedstoneEvent and cancel it if any owner or team member of the island where the BlockRedstoneEvent was fired is online. But it may cause problems with visitors if they have to open a door or activate a redstone system when nobody is online. So, i suggest to add a config option to toggle it.

I will have a look soon.

**Comment by Poslovitch** [comment]
Will be done for 3.0.5 ;)
