### ISSUE TITLE
ItemStack leak

### ISSUE THREAD

**Issue by AlfieC** [tastybento/askyblock#310]
Hey,

After extensive profiling (and a server uptime of 4+ days) it appears that the control panel is storing references to millions of ItemStacks. This has led to over 500mb of ItemStacks being retained in memory. See below.

![Screenshot of profile](http://i.imgur.com/n4iZexq.png)

- Alfie

**Comment by AlfieC** [comment]
After a little investigation, it appears that you don't clear up the `ControlPanel` object or `CPItem`s after an inventory is closed.

**Comment by tastybento** [comment]
Thanks. I'll look into this.

**Comment by voodootje0** [comment]
I hope this can be fixed asap, my server is lagging and the tps is dropping when it's more than 24 hours online, this can be the cause.

**Comment by tastybento** [comment]
It should be fixable. I will look at it when I get back next week.

**Comment by tastybento** [comment]
Okay, I now clear the inventory when it is closed. Please try: https://github.com/tastybento/askyblock/releases/tag/V3.0.3.3

**Comment by AlfieC** [comment]
After a little reviewing of your fix - that is a start but is not where the issue lies. The issue is that you don't clear up the ControlPanel objects themselves - simply removing them from the map on close will fix. (might be the CPItem objects - forgot which one)

**Comment by tastybento** [comment]
Oops i mis read your comment. Which map are you referring to?
