### ISSUE TITLE
Teamchat bug with DeluxeChat

### ISSUE THREAD

**Issue by voodootje0** [tastybento/askyblock#311]
Dear tastybento,

I've got a issue with deluxechat and teamchat.
![image](https://cloud.githubusercontent.com/assets/6852308/18607512/93638eba-7cce-11e6-8c4a-5448663f4841.png)
Could you fix this? =)
- voodootje0

**Comment by tastybento** [comment]
I would like to. This is definitely an incompatibility with Deluxe Chat. It is a paid plugun though so I can't look at their code. When I get back to the US I will write the author and try to see why it is happening.

**Comment by voodootje0** [comment]
Thank you really much for the fast answer, even when you're not at home.

**Comment by MeltedLux** [comment]
Seems this issue still exists. any temporary fix?

**Comment by tastybento** [comment]
Duplicate of #317
