### ISSUE TITLE
AcidIsland Minishop Players can buy without money

### ISSUE THREAD

**Issue by WoodlandWhimsy** [tastybento/askyblock#312]
My players can open the minishop and buy any item even without money.

It gives the message that they can't afford it, but it pops out anyway. 

Thanks.

**Comment by tastybento** [comment]
What version of the plugin are you using? What is your economy plugin, and what other plugins are you using?

**Comment by WoodlandWhimsy** [comment]
Thank you for your quick reply.  V3.0.3.2, EssentialsX, GUIShop, GriefPrevention, Multiverse, Plotsquared, Groupmanager, Statz, Vault, WorldEdit, WorldBorder, Dynmap, Mcmmo and a few other incidental ones.

I hope this answers your question fully.

**Comment by WoodlandWhimsy** [comment]
I found out it was the GUIShop plugin causing the problem.  I have uninstalled that plugin because their option to disable worlds doesn't work.  I've left a comment for that developer, but I wanted to share for anyone who might run into the same issue in the future.  Thanks again.
