### ISSUE TITLE
Add a build limit to islands

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#314]
It's possible to set the server to allow heights above 255. This feature would limit height building based on player permission so that donors could get more height.

**Comment by Pokechu22** [comment]
> It's possible to set the server to allow heights above 255.

Is it?  I'm pretty sure that, protocol-wise, you can't have heights above 255 without protocol-level mods (IE, not bukkit) - the game simply doesn't support it.

But it is possible to set a max height that's less than 255 (I know a server that had it at 170), so such a feature could still be useful.

**Comment by tastybento** [comment]
@Pokechu22 Ah okay, thanks. I didn't know about this until someone asked. I haven't confirmed it either way. Maybe I'll kill this for now.
