### ISSUE TITLE
DeluxeChat - help wanted

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#317]
This plugin is becoming more popular, but it requires integration at the API level. Can anyone contribute a pull request to add that?
See:
https://github.com/extendedclip/DeluxeChatPlaceholderAPI/blob/master/src/me/clip/placeholdertest/PlaceholderTestPlugin.java
https://www.spigotmc.org/resources/deluxechat.1277/

**Comment by xion87** [comment]
Also confirmed to have this issue with chatcontrol, but it can manage event priority, which priority is using the chat?
