### ISSUE TITLE
New commands - comment if you think they're useful

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#318]
Got this request:

/Is allow (Allows players to go on your island even if it's locked.) [Re-doing command disallows them again/This can also be /is disallow]
/Is banlist (Lists the players you have banned from your island)
/Is bans (lists the islands you are banned from)

**Comment by Poslovitch** [comment]
I totally agree!

**Comment by SwiftSwamp** [comment]
Would love to see these added.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#55
