### ISSUE TITLE
Welcome Sign conflicts with Essentials Sign Shop

### ISSUE THREAD

**Issue by Earthgamez** [tastybento/askyblock#319]
Since the welcome sign format uses the [ ] brackets to form the sign, it is interfering with the creation of Essentials Shop signs. You are unable to create them. It would be nice to have a config option to change the brackets to < > or something else that we would want to use. This way it would not conflict! Thanks!
EDIT: This is for Acid Island

**Comment by tastybento** [comment]
You can change that in the locale files. Look in locale.yml at the end in the warps section. Also, change the other language files to match.
