### ISSUE TITLE
ASkyblock messages spam with on log-in teleport plugin

### ISSUE THREAD

**Issue by Zaino60** [tastybento/askyblock#321]
I have a small plugin called Spawn-TP (https://www.mediafire.com/?6t4px9te9k05424) that teleports you to the Skyblock spawn when you log-in to the server. However, since I have the "not allowed to teleport while falling" ASkyBlock feature, when someone logs-out and logs-in the SkyBlock server while falling it spams its chat with the "You can't teleport while falling" message like crazy
Example of spam: https://gyazo.com/b6f571224a1f6c30034c63823f72cf7d

**Comment by tastybento** [comment]
Quick question - what priority do you have on your onJoin event? Have you tried setting it to LOWEST?

**Comment by Zaino60** [comment]
How do you I check that?

**Comment by tastybento** [comment]
It's a part of the @EventHandler

```
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = false)
    public void onJoin(PlayerJoinEvent e)
`

However, I just tried your plugin and I cannot get it to do what you show. Everytime I log out while falling and then log in again, it says that I cannot teleport while falling. What version of ASkyBlock are you using? Is there any other plugins you have that may affect this?
