### ISSUE TITLE
Make item pickup a toggle option 

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#323]

**Comment by Poslovitch** [comment]
What kind of item pickup? On island? At spawn?
And as a player setting or global setting?

**Comment by tastybento** [comment]
Right now the visitor item drop and pick up are globally set in config.yml. This would be to make it a toggle option in the settings screen.

**Comment by Poslovitch** [comment]
So it would be a global setting?
Add this in 3.0.5 milestone please

**Comment by tastybento** [comment]
No, it would change it from being a global setting to be an individual setting. So players could switch it on and off. There are two settings today in the config:

```
   # Allow item drop by visitors
   allowvisitoritemdrop: true
   # Allow item pickup by visitors
   allowvisitoritempickup: true
```

These need to be personalized.

**Comment by Poslovitch** [comment]
So i switch these settings to players settings. Looks simple ^^

**Comment by tastybento** [comment]
Let's move to 3.0.6 so we can release 3.0.5.
