### ISSUE TITLE
Add support for meta data to items in chests in schematics

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#325]

**Comment by Poslovitch** [comment]
Do you still need help?

**Comment by tastybento** [comment]
Yes, but this is extremely difficult. Maybe if it is only supported on 1.11.2 and onwards it may be possible.

**Comment by Poslovitch** [comment]
I'll have a look, but I don't i'll do it for 4.0

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#53
