### ISSUE TITLE
Protection range help

### ISSUE THREAD

**Issue by random1167** [tastybento/askyblock#326]
Hello i dont know were we messed up, After updating players old islands are a few blocks shorter
![z6n286m5](https://cloud.githubusercontent.com/assets/13611085/19373149/3e5288e4-9205-11e6-9514-28c9067212f6.jpg)
![j8o8g062](https://cloud.githubusercontent.com/assets/13611085/19373160/4bc49ff8-9205-11e6-9052-aff232ab1b09.jpg)

**Comment by tastybento** [comment]
Make sure you have the override set to true in config.yml otherwise protection range has to be 16 less than the island distance.
