### ISSUE TITLE
Allow loss of items if death at spawn

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#327]
if the config option "allowvisitorkeepinvondeath" is set to true players don't loose their inventory when visiting other's islands AND in spawn. Is there a way to make it so they keep inventory if they die while visiting other's islands but they loose it if they die in spawn? Because I have a PvP arena at the Skyblock spawn and the idea is players to actually loose their items if they die there, but I don't want to disable this entire feature because of trolls killing visitors with lava and stealing their items

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#52
