### ISSUE TITLE
Exempt /is coop'd players from an /is lock?

### ISSUE THREAD

**Issue by roastnewt** [tastybento/askyblock#33]
Sorry for spamming your tickets :)

It'd be nice if, when you lock your island, /is coop'd players would be exempt from the lock.  They seem to be partially exempt, but they can't use /is warp <player> if <player>'s island is locked.

**Comment by tastybento** [comment]
Interesting idea. Actually, if an island is locked, no one can use the warp sign, even the owner. So, I'd say that this enhancement would be to exempt owner, team and coop players.

**Comment by tastybento** [comment]
Okay, done! https://github.com/tastybento/askyblock/commit/2a4cb5cfcb46f171a81bc4a0f3ab9c1538b35897
