### ISSUE TITLE
API: add a getChallengesMap() that returns a HashMap<Category,List<Challenge>>

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#332]
I was trying to enhance the basic ASkyBlock's Challenges GUI, but I found no way to get all the challenges simply and cleanly.
So my idea's simple : add a way to get a list of all the challenges in every category by an HashMap.

Hope it'll be done.

**Comment by Poslovitch** [comment]
Did it and made a pull request : https://github.com/tastybento/askyblock/pull/334

**Comment by tastybento** [comment]
Thanks!
