### ISSUE TITLE
Make ghasts spawn in Nether more often

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#34]
Make it so that ghasts will spawn more often in the new nether. They are too rare and getting a tear is nigh on impossible.

**Comment by Yive** [comment]
Any progress on this bug? There's only been one ghast spotted on my server so far.

**Comment by tastybento** [comment]
Ghasts spawn over lava pools or large flat areas and as those don't naturally exist in the Island Nether, they don't spawn that often. They're pretty rare to begin with too. It's not a bug per se but I haven't added anything yet to make ghasts spawn extra.

**Comment by Yive** [comment]
Would it be possible to just add in either a function where if the player is in the nether, then spawn a ghast spawner 100 blocks above them at random intervals? or just add the ghast to the spawner list on the 2nd tower, but make it so it's only one spawner at max

**Comment by tastybento** [comment]
Yes, I was thinking something along the lines of your first idea, but adding the spawner to the tower is also a good idea. It's possible to do that yourself too by editing the nether.schematic and saving it using WorldEdit. Actually, that may be the best idea. Let me try some tests.
