### ISSUE TITLE
Latest ASkyblock version error

### ISSUE THREAD

**Issue by Muggyy** [tastybento/askyblock#341]
Error occurring with latest version of the plugin

Error: http://pastebin.com/2Zh6rGy1

Start of error is at the top, and ends at the bottom of the paste.

**Comment by Muggyy** [comment]
The top islands (/is top) dont seem to be generating either. Ive made sure that the config is up to date and that the world is reset. It is only me with an island on a test server, and it still does not seem to update.

**Comment by tastybento** [comment]
For the first error - this seems like a very complex error and I'll need to ask you a few questions -

1. What have you changed in the config? Pastebin it if you can - I suspect there's some change to the schematic section?
2. When is the error occurring? It looks like it's when you are making a new island?
3. Are you in the process of setting up a new server and changing various settings? if so, you may need to delete islands.yml to clear any old islands you have.

For the second comment - please read the FAQ. You are most likely excluded from the top ten because you have the askyblock.excludetopten permission or * or askyblock.* or similar.

**Comment by Muggyy** [comment]
For the top ten, I thought it would be something like that, so I tried it with a non op account but there is still nothing in the top ten. I am using leader heads with NPCs to represent the top island owners. The NPCs update when someone creates an island, but the level does not, says it is 0 for them both (my account and the alt). Ive also noticed when the server restarts the level does not update itself in chat, and everyone must manually type /is level for the variable to appear in chat.

For the first, my config is here: http://pastebin.com/u1cFkg4y I do not believe I did anything wrong in the schematic section, but you would know best.

It does seem to be appearing upon island creation, as I just did one for the non-op account.

I already reset the entire world and folder for ASkyblock, and only kept the config, schematics, locale, and challenges.

**Comment by Muggyy** [comment]
Ive reset all settings (deleted world and plugin folders) and the level does work in chat after a reset, the leaderheads signs are updating properly, and everything seems to be working. I just need my config file, so if that is the issue, I need to know what it is.

**Comment by Muggyy** [comment]
So Ive manually redone the new config for this update, and reset the server at every change I made. Nothing was wrong until I put my schematics in and started a new island. Thats when the error showed up and the level stopped updating itself in chat. The error is the same as above and this is my current schematic section: http://pastebin.com/GmpyqYM9

And overall config if it helps: http://pastebin.com/MwJaRUMy

Sorry for being a bit overwhelming, just trying to narrow it down for you.

**Comment by Muggyy** [comment]
Now Im getting this error: http://pastebin.com/ktM6KyCK

This plugin is really broken...

**Comment by Muggyy** [comment]
http://pastebin.com/vA0D0KDn

This is beyond frustrating. I touch 1 single value in any of the Askyblock files I get flooded with errors. How no one else is experiencing this issue is astounding. Just fix this please.

**Comment by Muggyy** [comment]
Just an FYI, I cant change the config at all without the island level in chat not updating, the is top not generating, and getting this error: http://pastebin.com/XzekhM8e

**Comment by Muggyy** [comment]
On island creation: http://pastebin.com/npjBpfgQ

With the same config, but default schematics: http://paste.md-5.net/sibucefaki.vbs

**Comment by tastybento** [comment]
I'm not at my pc right now so i cant check it, but what do you see in the console if you do /admin reload? Maybe there is a schematic error, e.g. no bedrock.

**Comment by Muggyy** [comment]
No errors on asadmin reload. Checked all schematics, bedrock on each.

Error on island creation with my schematics one more time: http://pastebin.com/HQBM5Gxc (top to bottom)

**Comment by Muggyy** [comment]
Its my challenges.yml

I dont know why its causing this error, but after a lot of work ive found that thats whats causing it. No yml errors or anything, just weird.

Hope that helped.

**Comment by tastybento** [comment]
So everything works?
