### ISSUE TITLE
Cant break blocks on island until they reset.

### ISSUE THREAD

**Issue by ReasonWhyGamer** [tastybento/askyblock#344]
Hi There,
I don't have any protection plugins used in the askyblock world and every time someone makes their first island they cant break any blocks or interact with anything. They have to restart their island just to be able to break blocks and interact with stuff. There is no console error log at all when they create their island.

Also when i put {ISLAND_LEVEL} and {ASKYBLOCK_ISLAND_LEVEL} In essentials and Deluxchat they both do not work i have PlaceholdersAPI and MVdWPlaceholderAPI installed and up to date and its still not working.

Test it yourself at play.supremepixel.net 24/7 server

Thankyou
Lewis,

**Comment by tastybento** [comment]
Please read the FAQ. Is the island at 0,0? Maybe the server spawn protection is preventing use of the island. What error do you see when you try to interact? DeluxeChat isn't supported.

**Comment by ReasonWhyGamer** [comment]
Its not at 0,0 i dont have spawn protection because its not even in a spawn world and i tried using essentials for the placeholder and it still does not work.

**Comment by tastybento** [comment]
Okay. What error do you see when players try ti interact withe the island? Island Protected?

**Comment by ReasonWhyGamer** [comment]
There is no message it just doesn't let them interact with anything. plus how will i fix the placeholder thing?

**Comment by tastybento** [comment]
If there's no message, then I doubt it's due to ASkyBlock. You can test it if you like by removing ASkyBlock temporarily and seeing if the same problem occurs. I suspect it will not. Note that spawn protection (in the server.properties file should be zero spawn-protection=0).

**Comment by ReasonWhyGamer** [comment]
Trust me I know a lot about minecraft and its nothing to do with spawn protection which is and has been set to 0 since i made the server. How do i fix placeholders??????????

**Comment by tastybento** [comment]
Deluxe Chat is not supported. If that plugin is not installed and you want to use Essentials Chat then check if you see the Essentials chat prefixes. I assume you know how to get that working. Once that is, just put the {ISLAND_LEVEL} tag in the prefix.

**Comment by ReasonWhyGamer** [comment]
Yes i have tried that but it does not work.

**Comment by tastybento** [comment]
It's probably a config issue.

Here are the plugins I used to test:
[21:32:57 INFO]: Plugins (7): WorldEdit, InvSwitcher, Vault, ASkyBlock, Essentials, EssentialsSpawn, EssentialsChat

Here's the Essentials Chat config section I use:

```
############################################################
# +------------------------------------------------------+ #
# |                   EssentialsChat                     | #
# +------------------------------------------------------+ #
############################################################

# This section requires the EssentialsChat.jar to work.

chat:

  # If EssentialsChat is installed, this will define how far a player's voice travels, in blocks.  Set to 0 to make all chat global.
  # Note that users with the "essentials.chat.spy" permission will hear everything, regardless of this setting.
  # Users with essentials.chat.shout can override this by prefixing text with an exclamation mark (!)
  # Users with essentials.chat.question can override this by prefixing text with a question mark (?)
  # You can add command costs for shout/question by adding chat-shout and chat-question to the command costs section."
  radius: 0

  # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting

  format: '&7<{DISPLAYNAME} &r({ISLAND_LEVEL})&7>:&r {MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

  # If you are using group formats make sure to remove the '#' to allow the setting to be read.
`

Here's a screenshot of it working:
https://i.gyazo.com/0afa1e847618c5f4043f1ba2541ff408.png

This is running on Spigot 1.10:
[21:33:37 INFO]: This server is running CraftBukkit version git-Spigot-047f737-744e1a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by ReasonWhyGamer** [comment]
I got this working like 10 mins after my last post sorry I didn't respond after that.
There is just 1 more thing. the Topten plugin you made for Askyblock is there anyway you could maybe integrate citizens so then instead of there being a skull there is a NPC stood there? that would be amazing.
Thankyou.

**Comment by tastybento** [comment]
Interesting. I haven't played with Citizens before, but that sounds like a cool idea.
