### ISSUE TITLE
/title command issues

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#346]
Askyblock and AcidIsland plugins use /title Minecraft command to sent title to users... 

https://github.com/tastybento/askyblock/blob/45891146c46750a5e922517556a47edf59941d17/src/com/wasteofplastic/askyblock/commands/IslandCmd.java#L819

now, this is a problem when plugins try to override command /title and I think we could easily fix this by calling /minecraft:title instead of /title

opinions?

**Comment by tastybento** [comment]
Sounds good. I didn't know about the /minecraft: thing...

**Comment by Poslovitch** [comment]
Fixed. Have to be closed.
