### ISSUE TITLE
Add new potion arrows to challenges

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#347]
Hello, I would like to create a challenge which requires to have on inventory some potion arrows. How can I do that?
Thanks.

**Comment by Poslovitch** [comment]
I'll make an easier support for these arrows in my challenges-rewrite branch. But it may take a little time.

**Comment by tastybento** [comment]
Yes, it's not possible right now.

I had a thought that it would be cool to be able to auto-generate challenges by collecting what is needed in your inventory and then just execute a command that'll make the challenge. In that way, you won't need to create a description language for the items. In the old days, every item could be defined by integers, but now Minecraft is using meta data to define everything, which is great, but makes it a lot more complex to define these items in a scaleable way.

**Comment by tastybento** [comment]
Handled in #566
