### ISSUE TITLE
Entity limits does not apply on nether islands

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#348]
Players found a new way to "glitch" the entity limit (and NPC limit, by the way) to get more NPC on their overworld island : they infinitely reproduce them in the nether, and get back them in the overworld.

**Comment by tastybento** [comment]
I think this should be relatively easy to fix:

https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/listeners/IslandGuard.java#L532

**Comment by Poslovitch** [comment]
I'll have a look. I'll send a pull request this evening.

**Comment by tastybento** [comment]
Fixed in 647adfa.

**Comment by Poslovitch** [comment]
Okay thanks. Just a question : will 3.0.4 branch be soon merged to master?

**Comment by tastybento** [comment]
Yes, really soon.
