### ISSUE TITLE
Players stuck in death loop if they warp to an island without first creating their own island.

### ISSUE THREAD

**Issue by TheReverend403** [tastybento/askyblock#351]
The situation: Two worlds, one is a hub world the other is the skyblock world. Players spawn in the hub world when they first join. If they then use `/is warp` to go to any island without first explicitly creating an island and they die on the island they are visiting, askyblock attempts to spawn them in the skyblock world's spawn point, which obviously doesn't exist if you have a hub world for new spawns.

~~This shouldn't actually happen when the config is set up like below, but it seems askyblock doesn't trigger an island generation if the user warped to the skyblock world.~~

Update: <Fulcnix> like, it gives you a inventory box to select which island you want when you first go into skyblock. problem is, you can exit the tab and you don't have to make an island

```
# Make island if player teleports to the island world and does not have one
makeislandifnone: true

# Immediately teleport player to their island (home 1 if it exists) when·
# entering the world
immediateteleport: false

# Have player's respawn on their island if they die
respawnonisland: true
```

**Comment by tastybento** [comment]
1. If you want to have islands created automatically when a player teleports to the island world and doesn't have one then you need to switch off the schematic GUI in the config.

2. askyblock does not actually handle where a player respawns when he or she dies if the player does not have an island. The server is spawning the player at 0,0. You can use plugins like Essentials Spawn to make sure players spawn back on the hub world.

**Comment by TheReverend403** [comment]
I've done exactly as you said regarding the config and players are still constantly respawned in the void. I've even configured multiverse to use my hub world as the skyblock respawn world. Still nothing.

**Comment by tastybento** [comment]
Have you tried Essentials Spawn? Use /setspawn to assign the location for all spawning.
