### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#354]
I'm working on adding MySQL database storage in a branch.

**Comment by Poslovitch** [comment]
It is a well-wanted enhancement. I hope you will succeed !
Why don't name this update ASkyBlock v4.0.0?

**Comment by tastybento** [comment]
Yes, I think it will be, but I'm still working on it. I'm planning on calling this a "pro" version too. :-)

**Comment by Poslovitch** [comment]
"Pro" ? Does it mean the plugin will be charged?

**Comment by tastybento** [comment]
Maybe, to help for support. The plugin will always be free to download though.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#51
