### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#357]
See
https://www.spigotmc.org/threads/bukkit-1-11-api-draft.193437/

**Comment by TNTUP** [comment]
I'd say look at both plugins which I'm running (ASkyBlock, Grid and AcidIsland) when a new comer joins, the server hangs a bit then it works, like a 1-3 sec lag delays. I'm doing 1.11 testings (Can't test plugins which rely on NMS) I'll report back here :)

You're the best Tasty :) Your plugins are very tasty! :wink:

**Comment by tastybento** [comment]
6614db3
deef5aa

**Comment by tastybento** [comment]
Complete.

**Comment by TNTUP** [comment]
Should I wait testing or if production use (When 1.11 becomes stable in my opinion) with the Challenges rewrite, anyway I don't care if I reset mines, never touched it or customize, hope the translations will come :)
