### ISSUE TITLE
GUI Issue

### ISSUE THREAD

**Issue by lolorz13** [tastybento/askyblock#358]
It is possible to remove items from the gui by CTRL clicking them out using thermos and this plugin

**Comment by tastybento** [comment]
Please read the FAQ.

**Comment by lolorz13** [comment]
@tastybento none of the other plugins in use add chest inventories nor do they add guis, this occurs only when CTRL clicking an item out of the inventory

EssentialsX-2.0.1.jar 	
EssentialsXSpawn-2.0.1.jar 	
ItemRestrict.jar 	
Multiverse-Core-2.5.jar 	
PermissionsEx-1.22.10.jar 	
Vault.jar 
askyblock.jar
worldedit-bukkit-6.1.3.jar
worldguard-6.1.2.jar

**Comment by tastybento** [comment]
What server are you using? Also, are you in creative mode? Finally, are you sure the item is actually in your inventory, or just appears to be, i.e, when you click on it, it disappears?

**Comment by tastybento** [comment]
I can't get Thermos to run right now.
