### ISSUE TITLE
I am working on a custom version for my server

### ISSUE THREAD

**Issue by KingTux2** [tastybento/askyblock#359]
Hello, this is my code?
I want to edit the /is setup and it does not work. It keeps using the old one?
The default version is it hardcoded ? or is it somewhere else.
`
public class IslandCmd implements CommandExecutor {

	public IslandCmd(ASkyBlock aSkyBlock) {
		// TODO Auto-generated constructor stub
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
		Player player = (Player) sender;

		if (cmd.getName().equalsIgnoreCase("island")) {

			if (args.length == 0) {
				player.openInventory(ControlPanel.controlPanel.get(ControlPanel.getDefaultPanelName()));
				return true;
			}
			return true;

		}

		return false;
	}

}
`

**Comment by tastybento** [comment]
I do not understand your question completely. The island command handling is in the IslandCmd class. You should edit that if you want to change commands.

**Comment by KingLinuxMC** [comment]
Lets say I want to reformat the command format. How would I do that. I couldn't find. if(command.getname().equalsignorecase("island")){}?

**Comment by tastybento** [comment]
If you want to change the command "island" to something else, you need to change it in two places:

1. plugin.yml
2. ASkyBlock.java

In plugin.yml, there is a commands section:

```
commands:
    island:
        description: Main player command
        aliases: [is, island]
        usage:  |
             /island help
    asadmin:
        description: Admin commands
        usage:  |
            /asadmin
    asc:
        description: Game challenges
        aliases: [c, challenge, aschallenge, challenges]
        usage:  |  
            /challenge
`

As you can see, you can actually set aliases, so if you just want to _add_ a command to the alias, you can do it here. If you want to change it, you must change "island" to something else.

Then you need to change the command registration in ASkyBlock. Look for the string **getCommand("island").setExecutor** and change the word island. There are a number of these in the file.

**Comment by KingLinuxMC** [comment]
Ok
