### ISSUE TITLE
enableJoinAndLeaveIslandMessages default to false with upgrading

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#363]
Islands that do not have this setting (upgraders) end up with enableJoinAndLeaveIslandMessages being false.  From https://dev.bukkit.org/bukkit-plugins/skyblock/tickets/672-no-island-enter-leave-message-appears

This is because the default setting is not loaded if the setting does not exist and instead defaults to false. As this setting's default is true, this is switching off all enter/leave messages by default for upgraders.

To fix, I'll have all settings for an island set to default first before loading.

To fix the issue for servers in the field, I plan to add an admin command similar to **/asadmin settingsreset confirm**, but that can globally reset any specific setting. e.g. **/asadmin settingsreset enableJoinAndLeaveIslandMessages**.

I will make **/asadmin settingsreset confirm** become **/asadmin settingsreset all**.

**Comment by Poslovitch** [comment]
Oh. I'm sorry to forgot this thing :/ Excuse me.

**Comment by tastybento** [comment]
Fixed with 49d8200
