### ISSUE TITLE
Cobble Generators Break

### ISSUE THREAD

**Issue by Gaurav99** [tastybento/askyblock#368]
Hey,
I love the new addition (I switched from another plugin), but there's one issue with it that's explained in this really short video: https://www.youtube.com/watch?v=qKR3bf6iHV4&feature=youtu.be

Basically, we used to be able to mine the cobblestone in the current setup (in the video).  The lava was down one block and to the side of the water, with a row of blocks above it.  The water then went diagonally upwards of the lava blocks, the water then after the cobble is broken falls into the lava and creates obby messing up the whole generator.  This didn't happen before, the ore generation happened before the water could flow and mess up the generator.  Could this be fixed, please?  

Thanks so much

**Comment by tastybento** [comment]
I built your generator exactly as shown in the video and I get obsidian every time I try and do what you do with or without ASkyBlock on the server (I tried 1.11 and 1.8.9). Can you confirm that this issue occurs only when ASkyBlock is active and the magic cobble generator is operational?

**Comment by Poslovitch** [comment]
I knew this setup. It looks like the plugin does not handle water coming from upside. I'm not sure and I will be able to check only this evening (GMT).

Thanks for using my feature :)

**Comment by tastybento** [comment]
@Poslovitch What I don't understand is that this setup causes obby for me even without the plugin. Is there something I'm missing here?

**Comment by Poslovitch** [comment]
@tastybento I saw my players using a similar setup and they don't get obsidian... 
It must be lava flooding to water to make cobblestone. Otherwise it makes obsidian. 

I think the shown setup is quite wrong, but I can't affirm anything.

@Gaurav99 Does other cobblegen setups have the same problem?

**Comment by Poslovitch** [comment]
I talked with Gaurav and it seems that it worked fine before.
He sent me the old plugin he was using (OreGeneratorRevolution). I'm looking about differences between what i made and how this plugin was made.

I hope I'll find a fix.

**Comment by tastybento** [comment]
@Gaurav99 Can you post a video of it all working on vanilla? Like I wrote, in my testing, I could not avoid the lava turning to obby when running no plugins. Also, what server version are you running? I tested on 1.8 and 1.11.

Here are the potential situations:

1. Lava becomes/does not become obby in vanilla (no ore gen or Askyblock running).
2. Lava becomes/does not become obby when the old ore-gen plugin is running.

I'd like to find out what happens in these two situations.

**Comment by tastybento** [comment]
I think this should be fixed in the next version 3.0.5.
