### ISSUE TITLE
Option to make visitors invincible

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#369]
Aim is to prevent players from killing themselves either intentionally or by accident (except by falling).

**Comment by Poslovitch** [comment]
Duplication of https://github.com/tastybento/askyblock/issues/322 :-)

Will you work on it? I think I can easily make it this week-end.

**Comment by tastybento** [comment]
Ha! Yes! I had forgotten about that.  It should be possible to kill two birds with one stone here. Please go ahead and do it.

**Comment by Poslovitch** [comment]
To close?
