### ISSUE TITLE
Llamas cannot be companions

### ISSUE THREAD

**Issue by WauloK** [tastybento/askyblock#373]
I tried to change the default companion to LLAMA but get this error even in the latest 3.0.4.1 version:

> [Server thread/WARN]: [AcidIsland] Island companion is not recognized. Pick from COW, PIG, SHEEP, CHICKEN, VILLAGER, HORSE, IRON_GOLEM, OCELOT, RABBIT, WOLF, SNOWMAN, BAT, MUSHROOM_COW

I updated the config.yml from config.new.yml

**Comment by tastybento** [comment]
Yes, this is a known issue and will be fixed in the next release. In the meantime, you can define the companion in the schematicsection for each island and that will work.
