### ISSUE TITLE
TopTen don´t work

### ISSUE THREAD

**Issue by Groodian** [tastybento/askyblock#374]

**Comment by Groodian** [comment]
Hello,
On my server don´t work the Top Ten.
I type /is top in the Chat and it comes only "These ar the Top 10 islands:" but not the Players, and the TopTenHead don´t Work too. 
Can you help me?
Sorry for my bad english ;(

**Comment by tastybento** [comment]
Hmm, try this: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#help-im-not-in-the-top-ten

**Comment by Groodian** [comment]
Thanks
