### ISSUE TITLE
Add "Likes"

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#375]
Idea picked from https://dev.bukkit.org/bukkit-plugins/skyblock/tickets/557-island-like/

Add a config option to toggle island likes
Add a command for visitors (/is like) to increase the island's likes score 
Add a TopTen Chat/GUI by the likes score
Maybe an admin command to edit the score?

Maybe a /is unlike command? (So make sure banned players cant downvote the island)

Edit: i can work on it but i'll need some help, especially for how to get/save score

**Comment by tastybento** [comment]
Yes. Where i got stuck was keeping a track of who voted and who didnt. This must be as compact as possible. Alternatively, maybe players can be given 1 vote a week or something so that they can vote multiple times but we dont have to track too much.

**Comment by Poslovitch** [comment]
I think we should try to release it in 3.0.6

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#50
