### ISSUE TITLE
Give permissions when on island

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#380]
Give permissions to players when they enter their own island (or coop) and take the permission away when they leave (or teleport out). This would enable admins to give players a lot of temporary perms, like essentials.fly for example. 

The list of permissions to give can be placed in the config.yml file.

**Comment by Poslovitch** [comment]
And i want to say... 3.0.5 milestone! Looks very simple to setup when island fly will be merged

**Comment by tastybento** [comment]
Let's go for it!

**Comment by tastybento** [comment]
Let's move to 3.0.6 so we can release 3.0.5.

**Comment by tastybento** [comment]
Need to remove perms when a player logs out or on disable of the plugin so that players don't accidentally keep perms.

**Comment by Poslovitch** [comment]
Will be done today (or friday)
