### ISSUE TITLE
Needed island level to be able to open portals/warp/...

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#381]
https://www.spigotmc.org/threads/a-skyblock.30325/page-151#post-2053282

**Comment by tastybento** [comment]
I'd like to try and make this more generic so that we don't have to do multiple variations on it (island level to open a chest, island level to open a gate, island level to warp, etc.). Maybe use permissions and just have a silent upgrade of perms? Also will need a downgrade too.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#49
