### ISSUE TITLE
Cannot place saplings

### ISSUE THREAD

**Issue by PotatoBoiii** [tastybento/askyblock#382]
Saplings will not place on dirt even if the island is protected. Some dirt blocks saplings place on, but the island owner cannot place saplings on dirt. However I found out saplings can be placed on grass. Is this a bug?

**Comment by tastybento** [comment]
What server are you using? This is no unheard of, but I've never linked it to ASkyBlock.

**Comment by PotatoBoiii** [comment]
I have a Spigot 1.11 server

Full list of plugins: (as of /plugins)

CoreProtect, WorldEdit, DoubleJump, ClearLag, Boost, ProtocolLib, WorldGuard, LibsDisguises, SuperTrails, UltimateSkyGrid, PermissionsEx, RandomTeleport, Vault, MassiveCore, ChestShop, Essentials, ObsidianAuctions, PerWorldInventory, PlotSquared, ASkyBlock, EssentialsXMPP, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, EnjinMinecraftPlugin, Multiverse-Core, Multiverse-Portals, GriefPrevention, Statz, MultiWorldMoney, Autorank.

Side note: for Essentials its not the official Essentials, its EssentialsX

**Comment by tastybento** [comment]
That's a too few many for me to test! There is nothing in ASkyblock to stop saplings being placed, so I think it's from another plugin. Sorry, but I don't think there's much I can do right now.

**Comment by PotatoBoiii** [comment]
Thanks for the help. I will test which plugin is doing this. Your skyblock plugin is still doing fantastic otherwise!

**Comment by PotatoBoiii** [comment]
It was GriefPrevention, in case you wanted to know.

**Comment by tastybento** [comment]
Wow - thanks for the info - that's actually really useful to know because I have seen this issue from others!
