### ISSUE TITLE
Extended Coop with timeout

### ISSUE THREAD

**Issue by azatoth** [tastybento/askyblock#386]
Currently there is only the normal coop, and the permanent coop via config setting.
I would like to have some kind of extended coop that can be given to people which will be in effect for a specified time, regardless if the cooper(?) or the coopee(?) logs out.

For example: `/is tcoop 6h Notch` will allow Notch to be coop on this island for 6h unless expelled manually, even if the person issuing the command logs off.

The main usecase for this is when you really need to go (irl), but you have friends working on stuff on yer island right now. Asking an admin to permanently switch coops to be permanent might not be a viable solution.

**Comment by TALLPUP** [comment]
Yes, this would be a very nice feature to have!

**Comment by Poslovitch** [comment]
My players also suggest me this idea. I approve !

**Comment by Latouth** [comment]
Isn't this kinda the point of TEAM...?
Like, i get some servers want infinite coop time, but some want to be a "One island only" server, so you can only really work on one.
Like the one I'm running, coop is used if you want to give someone access to help you make a cactus farm, or help you with this.. not really APART of your island.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#47
