### ISSUE TITLE
Configurable default language in config.yml

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#387]
https://dev.bukkit.org/bukkit-plugins/skyblock/tickets/309-configurable-default-language-in-options/
Should be easier to use than the actual system.

Will be done for the language update (3.0.6)

**Comment by tastybento** [comment]
Yes, I get a lot of complaints caused by having a locale.yml and separate language files.

**Comment by Poslovitch** [comment]
Can you please work on it? I dont understand the way you made the load of the locales.

**Comment by tastybento** [comment]
Okay
