### ISSUE TITLE
Island Bank

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#388]
If a config option that enable this feature is set to true, this will enable players to withdraw/put money in an island bank. Only team members should have access.
Maybe add some securities to prevent join-steal-leave.

**Comment by tastybento** [comment]
Hmm, maybe, but we need to be careful not to bloat ASkyBlock too much. There are bank/economy plugins already. Interesting idea though.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#46
