### ISSUE TITLE
Make events cancellable

### ISSUE THREAD

**Issue by Mrtenz** [tastybento/askyblock#389]
This would be very helpful.

**Comment by Poslovitch** [comment]
Which events? I already thought of this, but cancel some events may cause problems. (Especially IslandEnter and IslandLeave, or ASkyBlockEvent or some others...)

**Comment by Mrtenz** [comment]
TeamJoinEvent, TeamLeaveEvent, CoopJoinEvent, CoopLeaveEvent

These should be able to be cancellable without problems.

**Comment by Poslovitch** [comment]
Looks okay. Tasty, please put it in 3.0.5 milestone :)
I'll do this saturday, just needs to implements Cancellable in those events ;)

**Comment by tastybento** [comment]
@Poslovitch Ha! I know you're joking. Take care - it may need some more work than you think. For example, errors to show players if the event is canceled. Good luck though.

**Comment by Mrtenz** [comment]
@tastybento Errors should be shown by the plugin cancelling the event.

**Comment by tastybento** [comment]
@mrtenz ok. Understood.

**Comment by tastybento** [comment]
@Mrtenz Can you test 3.0.6 branch to see if it does what you expect?

**Comment by Mrtenz** [comment]
The CoopJoinEvent seems to work fine. I haven't tested the CoopLeaveEvent yet, but the code looks good.

**Comment by tastybento** [comment]
Okay, we'll go with this. Thanks!
