### ISSUE TITLE
Auto Updater - auto file download

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#390]
https://www.spigotmc.org/threads/a-skyblock.30325/page-152#post-2059123

I know ASB already have a "update alert". So why don't make the download of new version automatic?
I saw it is possible. The updated file should be downloaded to an "update" subfolder in ASB folder.

**Comment by tastybento** [comment]
Bukkit.org changed their auto update system so I'm forced to work on this.

**Comment by tastybento** [comment]
This is now in the code. It _can auto download_ if we want it to in the future. For now I kept it as just announcement.
