### ISSUE TITLE
Island companion is not recognized

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#393]
Latest update shows; 
   # Recommended are: COW, PIG, SHEEP, CHICKEN, VILLAGER, HORSE, IRON_GOLEM, OCELOT,
   # RABBIT, WOLF, LLAMA or NOTHING. Default is COW.

But when you choose one of the new one's you get an Error.

Island companion is not recognized. Pick from COW, PIG, SHEEP, CHICKEN, VILLAGER, HORSE, IRON_GOLEM, OCELOT, RABBIT, WOLF, SNOWMAN, BAT, MUSHROOM_COW

http://prntscr.com/dglv2o

**Comment by tastybento** [comment]
Dupe of #373

**Comment by tastybento** [comment]
Fixed in 3.0.5.1.
