### ISSUE TITLE
Add the End to ASkyBlock

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#396]
This has been requested a few times.

**Comment by wasder** [comment]
Any ETA?

**Comment by tastybento** [comment]
@wasder no not right now.

**Comment by friishon** [comment]
When are you going to add end?
I would like to have the end world and put level for going

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#45
