### ISSUE TITLE
Magic Cobblegen not working

### ISSUE THREAD

**Issue by WauloK** [tastybento/askyblock#397]
Hi!

I had another cobblegen plugin installed so disabled it for Acid Island.
When I started the server on 3.0.5.1 and enabled all the Magic Cobblegen config.yml lines, I went to my old cobblegen and mined out the cobblestone block there. The lava and water (acid) touched but did not generate anything. 

I restarted, but still the same. Re-enabled my other plugin and it's now generating random ores again.

**Comment by tastybento** [comment]
It might be the cobblestone generator style. Can you post a picture or video of it? This is a surprisingly complicated thing to do as cobble is generated in weird ways in Minecraft.

**Comment by tastybento** [comment]
Also, what does **/asadmin cobblestats** say?

**Comment by WauloK** [comment]
/acid cobblestats says:
None

Config:
   # Toggle Magic Cobblestone Generator
   # If set to true, a cobble generator will not just generate cobblestone, but
   # also blocks you have specified.
   # Default is false, because it highly changes the gameplay.
   usemagiccobblegen: true

   # This won't be considered if usemagiccobblegen is set to false.
   # You can add, remove a block or modify its probability to be generated.
   # You can also set different probabilities from specified minimum levels
   magiccobblegenchances:
     # These probabilities will apply by default
     default:
       COBBLESTONE: 75.0
       STONE: 10.0
       COAL_ORE: 7.5
       IRON_ORE: 5.0
       DIAMOND_ORE: 2.0
       EMERALD_ORE: 0.5
     #These probabilities will apply if island level is higher than 500.
     500:
       COBBLESTONE: 50.0
       STONE: 20.0
       COAL_ORE: 10.0
       IRON_ORE: 10.0
       REDSTONE_ORE: 5.0
       DIAMOND_ORE: 4.0
       EMERALD_ORE: 1.0
![acidisland](https://cloud.githubusercontent.com/assets/4031036/21203068/e355ee9c-c2a4-11e6-9f2a-a3505b8e28bb.png)

**Comment by tastybento** [comment]
Let me try that type of generator. The stats clearly say that no ore is being generated. The YAML looks okay. Can you try another type of generator, e.g. Just pour water over some lava and see if you get anything? That will help establish whether the problem is another plugin or not.

**Comment by tastybento** [comment]
I built the generator you have and it works great. I would guess that either there's another plugin blocking the cobble gen event, or the config.yml has a bug in it and the default setting (false) is being used. Please check them.
