### ISSUE TITLE
Heads in warp gui are backwards

### ISSUE THREAD

**Issue by steve4744** [tastybento/askyblock#398]
When I select the "list of warps" from the island control-panel, the heads are displayed backwards, so I see the back of the players heads instead of the face.

**Comment by Poslovitch** [comment]
This is not a bug of ASkyBlock, this is a bug appeared in 1.11. I had this problem with an other plugin using heads, without any solutions...

**Comment by steve4744** [comment]
Its apparently fixed in MC 1.11.1....so we have to wait. Thanks.
[https://bugs.mojang.com/browse/MC-109831](url)

**Comment by Poslovitch** [comment]
It's fixed in 1.11.1 which is just realeased :)

**Comment by tastybento** [comment]
Good. It looks like it is still a bit unstable according to Spigot, but I'll close this now.
