### ISSUE TITLE
Create a software to help making challenges.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#402]
I'll finish the challenges rewrite first ;)

I saw this in a review and I thought it is a good idea.
I'll create a software (using Java) which it'll make challenges configuration easier (drag&drop...).

I hope I'll get your agreement.

**Comment by tastybento** [comment]
What I'd like to recommend is that you try to do this in-game and make it a plugin (or part of ASkyBlock). That way, server owners could enable mods to make challenges. It's just an idea. 

To make a challenge where the player must gather the items:

1. Player gathers items
2. Player runs command /asadmin makeinvchallenge mynewchallenge
3. The challenge is made.

For a challenge that requires items or entities nearby:
1. Player makes area with required items - bedrock is ignored so they can use it to make an island
2. Player places required items/entities around
3. Player does /asadmin makeislandchallenge and challenge is made

After then, there can be commands to add titles/custom description/ etc.

If you look at https://github.com/tastybento/invSwitcher you can see how items can be stored in yml files directly from the inventory. This could be a new format to store required items. It might need a new file.

This are just ideas, I'm willing to hear yours too!

**Comment by Poslovitch** [comment]
I think it won't be user friendly by doing it IG. There will be so many settings to config... And many lines of code to make it ^^
I prefer to do a software. Clean and efficient interface, an export as all-done challenges.yml. Install and go. :D

**Comment by tastybento** [comment]
Okay, if you want to go for it, please do!

**Comment by Steev93** [comment]
@Poslovitch I already have been working on something with a dev if you want to collaborate with me :)

**Comment by Poslovitch** [comment]
@Steev93 Good. But when I'll finish the challenges rewrite, you'll have to rework this ^^

**Comment by Steev93** [comment]
@Poslovitch That's all good :) using VisualStudio to write this really are any of the key ID changing ? like "rewardtext" or layout format ?

**Comment by Poslovitch** [comment]
Everything will change. ^^´

**Comment by Steev93** [comment]
Arghh haha I will still make it for those who have the old version. Can you say anything about the new files? like any of the code or not yet

**Comment by Poslovitch** [comment]
You can have a look in the pull request. It's not definitove but you can see some of the changes I've already made.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#42
