### ISSUE TITLE
Mob Spawners and the MS!

### ISSUE THREAD

**Issue by Mutim** [tastybento/askyblock#405]
Hey tastybento, I have a problem when trying to create a line on my /is ms that sells spawners. I don't know if this is possible, it may be, I just may be doing it wrong. Could you either help, or maybe consider adding it as an option in a future update? This is the error I get in console when making the Item: MOB_SPAWNER and the Data: PIG (I think it's data, the same thing that changes potion effects)

[12:02:52 ERROR]: [ASkyBlock] Problem parsing shop item from minishop.yml so skipping it: MOB_SPAWNER
[12:02:52 ERROR]: [ASkyBlock] Error is : For input string: "PIG"

Thank you for consideration, and help!

EDIT: It was Extra: PIG. This is the exact file>>>
      material: MOB_SPAWNER
      quantity: 1
      extra: PIG
      description: '&f&nPig Spawner&r|&3Spawn eggs not enough?|Want something more consistant?'
      price: 20000
      sellprice: 1000

**Comment by tastybento** [comment]
Hi! This will have to be added so we'll look at doing it.

**Comment by Mutim** [comment]
Thank you so much for replying. You know how it is, so many problems. I
have 3 very important plugins that are giving me problems, and you're the
only dev who's contacted me back. I'll let them sit in suspense then 😉. I
can't wait for the update!

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#41
