### ISSUE TITLE
Config isnt updating?

### ISSUE THREAD

**Issue by griffen4** [tastybento/askyblock#406]

**Comment by griffen4** [comment]
Welp I accidentally pressed enter but my config is not updating to the newest version here is my current config.

http://hastebin.com/ilabugobak.php

**Comment by Poslovitch** [comment]
The config doesn't update itself. When a new version is detected, it creates a config.new.yml, which allows you to have a look on what settings changed. You need to put the new settings in your config.yml manually. And when you update, remove the config.new.yml to make sure you'll have the updated one.

**Comment by griffen4** [comment]
yes I know that. I updated the config but it says that its not detecting the new version of the config even though I did manually update it. :/

**Comment by tastybento** [comment]
Ah, that's because the version number was not updated. Copy that over too (it says don't change it, but you can to stop this message)

**Comment by griffen4** [comment]
Oh ok thanks 👍
