### ISSUE TITLE
Protection range

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [tastybento/askyblock#407]
I have problem with setting protectionRange on 101.  It works as 100. :/

**Comment by tastybento** [comment]
Yes, protection ranges have to be even.

**Comment by Kryniowesegryderiusz** [comment]
So there is no way to set 101?

**Comment by tastybento** [comment]
No, because 100 means 50 blocks one way, 50 blocks the other. Minecraft doesn't have 1/2 blocks.
