### ISSUE TITLE
Unsupported issue

### ISSUE THREAD

**Issue by skittishtrigger** [tastybento/askyblock#41]
I know this is not an issue with your plugin directly but I was hoping you may had some ideas to help me figure out a way around  it.  I am using your plugin for 1.7.10 on a kcauldron server....(hides and waits for kick) everything works great once creating an island but when it does it completely clears player inventory in the overworld too. Any ideas? if not its ok. I understand this isn't really your problem :)

**Comment by tastybento** [comment]
Actually 1.23% of servers run Cauldron! 

So, askyblock clears inventory when the player starts the island for obvious reasons. You can tell it not to in the config but that could inspire players to load up on diamonds or obsidian before starting. As you have a multi world server you need to install a multi world inventory manager. I'm not sure what will work on Kcauldron but MultiInv or something from the multiverse stable might work.

**Comment by skittishtrigger** [comment]
I thought so but I wanted to make sure before I installed something that would mess with your plugin. I use it on all my servers :)  I will do that in the morning. Once again, You rock :)
