### ISSUE TITLE
Culinary Artist spawn egg

### ISSUE THREAD

**Issue by BiggDaddyy** [tastybento/askyblock#415]
it won't give a muchroom spawn egg it just give a empty spawnegg that can't spawn anything :)

itemReward: 'GOLD_BLOCK:2 GREEN_RECORD:1 RECORD_3:1 RECORD_5:1 MONSTER_EGG:MUSHROOM_COW:1 EMERALD:5'

**Comment by tastybento** [comment]
I'm working on a fix. Also Pig Zombie doesn't work.

**Comment by tastybento** [comment]
@BiggDaddyy Fixed. Please confirm with this version: https://github.com/tastybento/askyblock/releases/tag/3.0.5.3
