### ISSUE TITLE
How can I get the cocoa beans？？？？

### ISSUE THREAD

**Issue by lgq1205** [tastybento/askyblock#417]
How can I get the cocoa beans？？？？

**Comment by steve4744** [comment]
Should be a reward in the farmer challenge unless your config has been changed:
`rewardText: '16 redstone dust, 1 cocoa bean, 1 spawn egg(chicken,cow,pig)'`

**Comment by tastybento** [comment]
Cocoa beans are strangely INK_SACK:3.
