### ISSUE TITLE
How can I get the carrots potatoes ?

### ISSUE THREAD

**Issue by lgq1205** [tastybento/askyblock#418]
How can I get the carrots potatoes ?
It can only drop by zb?

**Comment by tastybento** [comment]
Use POTATO_ITEM and CARROT_ITEM. Here's a list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by lgq1205** [comment]
THX tastybento , but I want to know how can I get the carrots and potatoes in survival without other mod and any change？

**Comment by tastybento** [comment]
Um, that's a general Minecraft question and nothing to do with this plugin! To answer your question, though, they are a rare drop from zombies. So, you can build a mob-grinder and kill zombies and hopefully a some point they will drop a carrot or potato.

**Comment by lgq1205** [comment]
Thank you very much~
