### ISSUE TITLE
Missing Wither-Skeletons in the Nether

### ISSUE THREAD

**Issue by BenediktHr** [tastybento/askyblock#419]
Hey,
I've noticed that there are no more Wither-Skeletons in the Nether.

This is probably due to the spawn behavior of Minecraft.
Skeleton Spawner no longer spawn Wither Skeletons.

Do you have an idea / workaround how to fix the problem? (For existing islands)

**Comment by tastybento** [comment]
Huh! 

I tried a few things, but I can only think of adding nether bridges to the schematic to have them spawn naturally, giving away wither skeleton spawn eggs or creating a challenge that summons a wither skeleton upon completion (which you then kill).
