### ISSUE TITLE
Global challenge reset admin command

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#420]
Add an admin command to reset a challenge by name for all players. e.g.,

/asadmin resetchallengeforall glassmaker

The use case for this is to enable challenges to be reset on a timer.

If possible, the reset time should be optionally set:

/asadmin resetchallengeforall glassmaker 24h

**Comment by CoolLord22** [comment]
Can we leave suggestions here? If so, I'll put the one I suggested on spigot here too xD

On my server I have acid rain and water as acid. I want a way to be able to make players immune from this. For example, if they have a helmet on they're immune from acid rain. If they have all the parts of the armor they're immune from both water acid and acid rain. It'd be kind of a cool feature if you could add it. Thanks for reading!

**Comment by tastybento** [comment]
@CoolLord22 You should create a new issue for this. :-)

**Comment by tastybento** [comment]
@Poslovitch Shall I work on this one?

**Comment by Poslovitch** [comment]
@tastybento Yes please. I'll try to keep it working in my rewrite.

**Comment by tastybento** [comment]
Just need to localize and then this is done.

**Comment by bertek41** [comment]
Maybe you can add /asadmin completeallchallange <player> (for owner :D)?

**Comment by tastybento** [comment]
Localization completed.
