### ISSUE TITLE
Is Top Gui lacking player(s)

### ISSUE THREAD

**Issue by Muggyy** [tastybento/askyblock#421]
So Ive found that after generating the top ten with /asadmin topten the gui only includes two out of the three players with islands on the server.

Here is the topten.yml: http://pastebin.com/UwyCJY4c (150 is the default island level)

As you can see, it does include the second player in the file, but the gui only shows the first and third players: http://imgur.com/a/yy8Zf

Also, the top one is me, being online my skin/head is shown as my own, but the player who is offline has an alex skin/head, even though their skin is different. Not sure if this is a bug or not.

**Comment by tastybento** [comment]
There's a bug with 1.11 that is apparently fixed in 1.11.1 - it's a Mojang bug.
For the other issue, that is a bit odd. I wonder if there's a problem with obtaining the head for that player. Are there any errors in the console?

**Comment by Muggyy** [comment]
Server runs on 1.8.8 with my client being 1.8. Does that still cause that bug?

And no, there are no errors in console. I will check again but for now the answer is no.

**Comment by tastybento** [comment]
How about with warps? Do you see the missing player's head in the warps panel (or not as the case may be)?

**Comment by Muggyy** [comment]
As that player does not have a welcome sign on his island I can not tell if it works or not. Is there a way to do it manually that I dont know of?

**Comment by tastybento** [comment]
Ah ok. I'll close this now. If it crops up again just file another issue.
