### ISSUE TITLE
Controlpanel

### ISSUE THREAD

**Issue by wen0750** [tastybento/askyblock#422]
i have a problem something about of controlpanel
and i have a video.
https://youtu.be/NyomgLuPT1A

**Comment by CoolLord22** [comment]
Yeah, I can confirm. The same thing is happening for me.

**Comment by tastybento** [comment]
Try **/is cp on** to turn on your control panel.

The plugin "remembers" the control panel setting for each player. So if you started your island when the setting was off, you need to turn it on. The setting in config.yml is the default for new players. So do /is cp on.

**Comment by wen0750** [comment]
ok ,thanks for your reply
