### ISSUE TITLE
[Feature Request] Acid/Water damage

### ISSUE THREAD

**Issue by CoolLord22** [tastybento/askyblock#423]
I have acid rain and water as acid. I want a way to be able to make players immune from this. For example, if they have a helmet on they're immune from acid rain. If they have all the parts of the armor they're immune from both water acid and acid rain. It'd be kind of a cool feature if you could add it. Thanks for reading!

**Comment by tastybento** [comment]
The plugin already does give protection by using armor, but you're asking for it to be complete protection right? Like using a water-breathing potion completely protects? It can be done with an extra setting. I'll try and get it into the next release.

**Comment by CoolLord22** [comment]
Awesome! Thanks :)

**Comment by tastybento** [comment]
@CoolLord22 : I just remembered - there's a permission already for this askyblock.mod.noburn (or acidisland.mod.noburn). Will this work for you?

**Comment by CoolLord22** [comment]
I wanted something like, so if a player has lets say all their armor on (no matter what kind) they'll be immune from the acid damage. The permission I've already given to staff and myself so xD
