### ISSUE TITLE
[Feature Request] Monsters per island limit

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [tastybento/askyblock#425]
Its hard to average the per chunk monsters spawn limit to dont have laggs and also have working mobgrinders. So maybe could you add per island monsters limit. Then monsters could spawn quickly, mobgrindes will work and at the same time there wouldn't be enormous amount of them :)

**Comment by Poslovitch** [comment]
It looks like the Animals limit request in 3.0.6 milestone. So i think I should expand it to support monsters.

**Comment by tastybento** [comment]
Done in 3.0.6.
