### ISSUE TITLE
[Feature Request] Pages in Challenges.yml and Reset time on challenge

### ISSUE THREAD

**Issue by bingoberra** [tastybento/askyblock#427]
Hello!

I would like to request something that I'd like to see in the plugin.

A reset timer for challenges. This make it so ITEM challenges that are non repeatable gets a reset timer so you can do them every few hours, or every 30m etc. (If you complete it once, you still get to advance to next level.)

Resettimer: 24h | 30m | 2h | etc.¨

Pages in challenges. Novice -> next page -> Competent -> Or similar. I haven't thought about how this would look tho.. 
The "issue" I am experiencing right now is that it's too clustered, with the books so "close" to all the challenges?

Maybe add some spaces or put them on a lower row? I don't know how to do this without ruining the challenges.yml

**Comment by Poslovitch** [comment]
Challenges rewrite !
It will come in about 1 month. Pretty hard to finish as I'm very busy nowadays.

**Comment by bingoberra** [comment]
Alright, epic!

Waiting for that then ;) 👍

**Comment by tastybento** [comment]
Handled in #566
