### ISSUE TITLE
Redstone airplanes

### ISSUE THREAD

**Issue by griffen4** [tastybento/askyblock#428]
Hi so today I found a massive issue with a redstone airplane that you can make in the game. Basically people are making these redstone machines that can fly through the sky and can go across to other islands and break them! Here are some examples: 

Leaving there island limits and it is still working: https://gyazo.com/d07bd7b57107a2fee1af09ba826889b9

Breaking through a wall of the island in front of it: https://gyazo.com/563e89c42999e0943d64f14e30ac3d7c

Now I know this is a vanilla thing but I reported it here because it can break other peoples islands where they are not added on. If there is a fix to this please let me know. Other than that I hope this somehow gets fixed either with this plugin or another one. Thank you for the help!

- Griff

**Comment by tastybento** [comment]
For some reason I couldn't see the graphics, but if these rely on pistons, then just set allowpistonpush: false in config.yml. That'll fix it!

**Comment by Steev93** [comment]
Hey,
Could this be helpful on this topic?
>    Disable redstone operation on islands unless a team member is online.
>    disableofflineredstone: false

But having redstone only work within the island radius, soon as it reaches out it disables?

**Comment by tastybento** [comment]
@griffen4 @Steev93 I managed to see the GIFs and these are just piston machines. The piston setting will stop these at the edge of the player's island.

**Comment by griffen4** [comment]
I can confirm this fixed the issue thank you :D
