### ISSUE TITLE
Variable not working

### ISSUE THREAD

**Issue by guard1anslayer** [tastybento/askyblock#432]
So I'm having this problem with the variable {ISLAND_LEVEL}. It was working fine in past versions but when I updated it, it stopped working. Any help? Some screenshots to take a look at [click me](http://prntscr.com/dofrj7) and [here](http://prntscr.com/dofryw) I have protocolLib for any case installed and the updated vault version, no errors appear what so ever in the console. Any help would be appriciated. Thank you in advance!

**Comment by tastybento** [comment]
Weird! What version of server are you using now and what version of the plugin (before/now)? Do you have any chat plugins running? What plugin is doing the prefixing? EssentialsChat?

**Comment by guard1anslayer** [comment]
I am using essentialschat, nothing changed in it. When it was fine I was using the version 3.0.3.3 but when I updated it to 3.0.5.2 it stopped working. my server version is 1.8.8 spigot. I have a lot of plugins running but no plugin would interact with this one. If it would, it wouldn't work the first time!

**Comment by tastybento** [comment]
I just tried 3.0.5.2 with Essentials Chat and it works okay for me. There were no changes to the {ISLAND_LEVEL} code between those two versions. I can only think that the tag has changed in your config.yml file? Look around line 576, do you see:

   chatlevelprefix: "{ISLAND_LEVEL}"

?

**Comment by guard1anslayer** [comment]
Yes. The chat prefix is just fine.. I will try and reset the whole thing
and see if that works.

Στις 28 Δεκ 2016 7:01 ΠΜ, ο χρήστης "tastybento" <notifications@github.com>
έγραψε:

**Comment by tastybento** [comment]
Closing for now.
