### ISSUE TITLE
Issue with "Island Protected"

### ISSUE THREAD

**Issue by jareds118** [tastybento/askyblock#435]
Basically, when a new player joins they create an island. They get this message: Island Protected. When coming to investigate, it says that no one owns the island. They have to try multiple times to create a new island until they can actually build on it.

Found multiple other issues on this subject, none of them helped.
Very similar to this issue: https://github.com/tastybento/askyblock/issues/242
But with mine it says that the island is not owned by anyone.
No errors in the logs either.

[config.txt](https://github.com/tastybento/askyblock/files/674866/config.txt)

**Comment by tastybento** [comment]
Is this a new install or are you an established server? The islands.yml file may have become corrupted. There's an approach to try here: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#when-i-do-asadmin-info-on-an-island-or-acid-info-it-says-the-island-is-unowned-but-it-is-owned-why

**Comment by tastybento** [comment]
Closing for now.
