### ISSUE TITLE
(unconfirmed) reports of mending not working properly in 1.11.2

### ISSUE THREAD

**Issue by krustymk** [tastybento/askyblock#438]
Comment from one  of my players (she's pretty reliable)
'Seems to not be as effective in Skyblock as it is in other worlds. Is this a SB config? or a bug?

It's not completely absent, but most of the xp orbs seem to attach to player, rather than be applied to tools with Mending enchantments on them.'

**Comment by tastybento** [comment]
Hmm. There's nothing in ASkyBlock specifically to affect mending - indeed it's something I'm only just learning about. Let's monitor.

**Comment by tastybento** [comment]
Closing for now, but if you see it and confirm it's due to ASkyBlock, reopen.
