### ISSUE TITLE
Spaces in control panel

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#439]
Enable icons to be placed in specific inventory locations. See http://prnt.sc/d9bxvs

**Comment by Poslovitch** [comment]
So make an adaptative inventory size.
I agree!

**Comment by Steev93** [comment]
i know with MyCommand they have a custom code to do this in making your own GUI_Menu to custom where the icons go if you wanted to check it out :)

**Comment by tastybento** [comment]
Related to #443

**Comment by Poslovitch** [comment]
Will be done for 4.0

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#38
