### ISSUE TITLE
Island range problem

### ISSUE THREAD

**Issue by UnioDex** [tastybento/askyblock#441]
It is related with AcidIsland but AcidIsland has no issue tracker so im writing here. Same codebase anyway.

I made an update from 3.0.1 to 3.0.5.1 some of my players lost their island ranges. In my config protection range 100 and island range 110. Former players can use all 100 blocks but now they can only use 94. So their blocks stayed outside and levels dropped.

What should i do?

**Comment by tastybento** [comment]
If the island distance and island protection range are < 16, then you need to set overridelimit and cleanupblocks to true in the config.yml.

I'm going to make this automatic in the next version.

**Comment by UnioDex** [comment]
CleanUpBlocks will remove players blocks or just removes on island restart?

**Comment by tastybento** [comment]
It kicks off an async background task when an island is deleted. It removes any remaining blocks in overlapping chunks between islands. Typically it does 2 chunks per second and takes about 30 seconds to clear them all. You can see progress in the console log.

**Comment by UnioDex** [comment]
I made both true. But still same. Players island showing 94 range. And cant make anything to blocks out of range.

**Comment by tastybento** [comment]
What happens if you try to set the island range to 100? Do you see an error?
