### ISSUE TITLE
Custom Island Chest Not Filling

### ISSUE THREAD

**Issue by UmmIdkWhatUsername2Pick** [tastybento/askyblock#442]
So, I created a custom island for my donators to use, and put some custom items in the chest for them. (In the config, not in game) and they dont end up in the chest when I create the new island, is this a bug or am I screwing up?

**Comment by tastybento** [comment]
You have to have useDefaultChest: true in the schematic section for the schematic you are using.

**Comment by UmmIdkWhatUsername2Pick** [comment]
Thanks, I have yet to try this but I assume it works.

**Comment by tastybento** [comment]
Okay, closing for now.
