### ISSUE TITLE
[Request] spacers 

### ISSUE THREAD

**Issue by voodootje0** [tastybento/askyblock#443]
Dear tastybento,

Could you add support for spacers =)
![image](https://cloud.githubusercontent.com/assets/6852308/21584521/c197eb7e-d0ab-11e6-9534-027b762f3f5c.png)

(Now we did it like the image above but when you click on the spacer (glass pane) the schematic will create, if you could add support so when you only have icon, name and description it will be an spacer and when you click on the item only the event will be canceled and noting else)

Kind regards,
voodootje0

**Comment by Poslovitch** [comment]
Please add this to 3.0.6 milestone. I will also work on a proper API to make Panels easier to create.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#84
