### ISSUE TITLE
API: IslandFly Event Exception

### ISSUE THREAD

**Issue by Fluxty** [tastybento/askyblock#446]
This error occurs on both IslandEnterEvent & IslandExitEvent: http://pastebin.com/43NJA5ZX

This is the IslandFly plugin (code on page): https://www.spigotmc.org/resources/islandfly-askyblock.26868/

Here's what it looks like in my IDE (removed unused objects): http://pastebin.com/w0Xm2YQy

**Comment by tastybento** [comment]
The developer has not done a null check on the owner. event.getIslandOwner(); can return null if there is no current owner, e.g., the island is spawn or it is a known island, but currently has no owner (player was unregistered).
If the result is null, then the rest of the code should be skipped.
