### ISSUE TITLE
[Request] Spawners as value

### ISSUE THREAD

**Issue by voodootje0** [tastybento/askyblock#449]
Dear,

Now (silkspawners) spawners don't have really good support for value counting. You can only set MOB_SPAWNER as an value, but not an Iron Golem Spawner (MOB_SPAWNER:99).
Could you add support for (silkspawners) multiple spawners?

Kind regards,
voodootje0

**Comment by TheCamZone** [comment]
Yes please! This would be so useful

**Comment by tastybento** [comment]
I'm sorry, I don't understand the request. Can you give an example of what you want and where?

**Comment by TheCamZone** [comment]
Can you make it so each individual spawner on the island adds a certain amount of island level. I believe this is what he wants. So Irongolem spawners would give like 100 value, and blaze would give 50. Make this configurable in blockvalues.yml.

**Comment by tastybento** [comment]
Ahhh! Okay, I understand. We'll make it a feature request and investigate.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#83
