### ISSUE TITLE
Custom Island not Registering

### ISSUE THREAD

**Issue by UmmIdkWhatUsername2Pick** [tastybento/askyblock#451]
So I made a custom island and added it to the config. However, its not registering. [http://pastebin.com/LFJzhKua](url) (Config)

The schematic is called member.schematic

**Comment by tastybento** [comment]
Looks fine. The player doing the resetting or starting the new island must have the **member.island** permission to see it in the GUI (or be Op).

**Comment by UmmIdkWhatUsername2Pick** [comment]
I have tried this, (I am OP) and it does not show up in the GUI.

**Comment by tastybento** [comment]
What does **/asadmin reload** say? Is it being loaded correctly?

**Comment by tastybento** [comment]
No answer - closing.
