### ISSUE TITLE
Took backups -> Transferred to new server host -> Islands reset?

### ISSUE THREAD

**Issue by dimym** [tastybento/askyblock#452]
We've gotten a new server host on my server and took all the files to our new host but apparently the islands reset? I mean UUID's are in the files.

**Comment by tastybento** [comment]
Right. If all the files in the plugin folder and the world files moved, then I don't know why there would be any problem. Admins regularly zip up their files and dropbox them to me. Are you sure you didn't switch to offline mode or something? In that case, all the UUID's for players will be different.

**Comment by dimym** [comment]
No I didn't switch to offline mode.

**Comment by tastybento** [comment]
So, when you say "the islands have reset" what actually happens?

**Comment by YvesChasse** [comment]
I've had the same problem currently:

Here's all i can tell you and most likely his problem is similar to mine.
I was setting up bungeecord, Reset it changed it to onlinemode: True.
The server.properties in the server was always set to onlinemode: false for bungeecord. 
After that i noticed that all the islands were there although everyone was kicked from their islands themselves.
Now with your plugin i do believe that it's supposed to attempt to reconnect UUIDS to the correct un-owned islands?

Some players UUIDS changed but not all players UUIDS changed.
I attempted to manual change over the UUIDs over the playe-data in plugins/askyblock. That did not fix anything.

Now all the islands/spawns are there. No other server files were effected by the restarts. just that there are multiple unowned islands.

In islands.yml in the askyblock plugins folder. All UUIDS are still properly setup in the .yml. Just still unsure why all players were kicked off their islands (un-owned islands).

**Comment by tastybento** [comment]
No update.
