### ISSUE TITLE
Issue while using {ISLAND_LEVEL} prefix

### ISSUE THREAD

**Issue by mart1998** [tastybento/askyblock#454]
Hi, Since the update of today, I can not use the {ISLAND_LEVEL} prefix in my chat plugin. I am using the SimplePrefix plugin and have this format: '&8[&eLvl &b{ISLAND_LEVEL}&r&8]&r[prefix][name][suffix]'

**Comment by tastybento** [comment]
Okay. That's a poorly written plugin, but I adjusted ASkyBlock to enable it to work again. Here's a link to a release you can use: https://github.com/tastybento/askyblock/releases/tag/V3.0.5.5
