### ISSUE TITLE
Magic Cobble Generator doesn't work with auto cobble geneterator.

### ISSUE THREAD

**Issue by wasder** [tastybento/askyblock#455]
![](http://i.imgur.com/iixfQZD.png)
But if I break the block by hand, it will generate "magic"
![](http://i.imgur.com/FZsQVqR.png)

**Comment by krfcm** [comment]
This generator also do not work (I break the block by hand) http://screenshot.sh/oB1zsx0GVegoj http://screenshot.sh/n8mcVAFBwnDqP

**Comment by tastybento** [comment]
Yes, not all generators work. This is a known issue. It may take a while to fix.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#36
