### ISSUE TITLE
Creating Challenges

### ISSUE THREAD

**Issue by t0mmyxbl** [tastybento/askyblock#456]
I have created more challenges and it seems to be causing some sort of an issue. Basically when you unlock the second tier of challenges, clicking on the book to go to the previous challenge just doesn't do anything and also the final challenge in the list of this next tier, just doesn't do anything when clicked on. The other part is that to unlock the next tier of challenges it is asking for 1 more to be complete, except the waiveramount is set to 1. Reference to the following image might help:
https://gyazo.com/9a890cd14a4a75281097587d254e25a4

**Comment by t0mmyxbl** [comment]
Slight update, seems to only be on these novice challenges that the issue is occuring

**Comment by tastybento** [comment]
Please pastebin the challenges.yml file because then we can see what the problem is. Do you see any errors in the console log at all?

**Comment by t0mmyxbl** [comment]
http://pastebin.com/TVEcEZzf

That's the challenges.yml file, note that i changed the novice level to Amateur just to see if it fixed anything, but it didn't. I also do not get any console errors.

**Comment by tastybento** [comment]
The problem is that there is no icon for "CAULDRON:1" so it just shows nothing and all the following icons are in the wrong place. Unfortunately, there's no API check for non-visible icons so I cannot check for them right now. So, just search for "CAULDRON:1" and change it to "CAULDRON"

**Comment by t0mmyxbl** [comment]
Ah ok it's fine now, I didn't realise i'd put the 1 in there. Silly me. Thanks

**Comment by tastybento** [comment]
No problem. Enjoy!
