### ISSUE TITLE
[WIP] Enable settings panel to work for spawn

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#459]
Converge spawn settings with regular island settings.

**Comment by YellowZaki** [comment]
Have the permissions been changed?
Permissions like:
          askyblock.settings.allowCropTrample:
          askyblock.settings.allowDoorUse:
          askyblock.settings.allowEnchanting:
          askyblock.settings.allowEnderPearls:
          askyblock.settings.allowFurnaceUse:
          askyblock.settings.allowGateUse:
Don't work now
