### ISSUE TITLE
Add option to send enter island messeages in ActionBar

### ISSUE THREAD

**Issue by RikoDEV** [tastybento/askyblock#463]
I've got a great idea to send an enter / exit the island in ActionBar.

**Comment by Poslovitch** [comment]
Good idea.
@tastybento Add this in 3.0.6 milestone, please :)

**Comment by tastybento** [comment]
@Poslovitch You can do it?

**Comment by Poslovitch** [comment]
@tastybento This will need some NMS. I'll try to find a way to handle it properly.
