### ISSUE TITLE
Nether island count in level calculation

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#464]
This would be a config option that will make the nether island count in the global level calculation.
Maybe with customized values? (e.g: dirt values 10 in overworld, 2 in nether).

**Comment by tastybento** [comment]
@Poslovitch Any chance of a pull request for this? :-)

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#35
