### ISSUE TITLE
Feature request - allow players to own and/or be Member on multiple islands. 

### ISSUE THREAD

**Issue by 0x1x2** [tastybento/askyblock#466]
Title says all - feature request my players have asked for for a long time.

A permission like askyblock.maxislands.<amount> would be nice with this.

**Comment by tastybento** [comment]
Thanks for the request. Unfortunately, owning multiple islands it's not something that'll fit into the architecture of the plugin without a complete rewrite, so we can't do it. The coop feature enables players to become members of multiple islands without owning them and it can be permanent.
