### ISSUE TITLE
Possibly asadmin move?

### ISSUE THREAD

**Issue by XenonNeon** [tastybento/askyblock#47]
A way for admins to move an island from one location to another? Like my island was automatically made relatively far away from spawn, and id like it to be one of the neighboring islands to spawn that are currently empty, also, if two friends want islands beside each other but they weren't beside each other to start. That would be a great feature! Love the plugin! Also I'm not sure how to make this an "enhancement" label, im new to GitHub

**Comment by tastybento** [comment]
This is a good idea.

**Comment by tastybento** [comment]
This appears to be difficult to accomplish. It can be done manually using the admin register/unregister commands and the WorldEdit. I'm not going to add it to ASkyBlock.
