### ISSUE TITLE
Item Spawners

### ISSUE THREAD

**Issue by YouGamePlayHD** [tastybento/askyblock#474]
Hey,
is it possible to add an ITEMspawner to SkyBlock? How this is thought:
Either a mobspawner items or a special block drop defined items. You should also be able to buy them via shop (sign shop).
So here comes my suggestion: Let players specify special blocks in the config to spawn items like stone, diamonds, a.s.o.
Is this possible?
Kind regards

**Comment by Poslovitch** [comment]
Yes, it's possible. However, about if we'll do this, i dont know...

**Comment by tastybento** [comment]
This would be another plugin. Not a bad idea though.
