### ISSUE TITLE
Multi-world

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#476]
Make ASkyBlock, once island limit in the world reached, can create another world.

**Comment by tastybento** [comment]
What would be the benefit?

**Comment by Poslovitch** [comment]
May not be really useful as I originally said, but we can make ASkyBlock handles both spawn world and islands world.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#31
