### ISSUE TITLE
Extra Settings in different worlds

### ISSUE THREAD

**Issue by johnsoncui02** [tastybento/askyblock#478]
So I separated a world for the spawn area and the actual skyblock world. on the default spawn area i receive extra permissions and options but cannot edit or modify these settings regardless of OP.
![image](https://cloud.githubusercontent.com/assets/23487437/22273319/deeb5a2a-e254-11e6-8d41-3f76a9d07039.png)

on the other hand, i receive less permissions on the actual askyblock island world.
![image](https://cloud.githubusercontent.com/assets/23487437/22273331/f7dad5e2-e254-11e6-850b-ae15f7490baf.png)

I've also looked up the permissions and tnt, wither griefing was nowhere to be found.

**Comment by tastybento** [comment]
Modifying spawn settings using the GUI is a 3.0.6 feature and that is not released yet. You need to use the config.yml for now. Also the island spawn cannot be in a different world. If you want another world for spawn then you can do it and use WorldGuard or similar to protect it.
