### ISSUE TITLE
Nether Massive Lag

### ISSUE THREAD

**Issue by johnsoncui02** [tastybento/askyblock#481]
So the new nether spawn has all the glowstones on the very top of the world with netherracks. That creates massive lag I'm assuming because each glowstone there is it has to force the players to update each of those lighting updates which results in massive lag and stress on the server. Is it possible to remove all the glowstones and add in some sort of other blocks lets say like 10% netherquartz ore or somewhat?

**Comment by tastybento** [comment]
There's an option in config.yml to turn off the nether roof:

```
   # Make the new nether roof, if false, there is nothing up there
   # Change to false if lag is a problem from the generation
   netherroof: true 
```
