### ISSUE TITLE
Problem with "reused" Player Names.

### ISSUE THREAD

**Issue by Blacksheep92** [tastybento/askyblock#485]
Hey, 
we have a small problem.

Player ABC played a while ago on our AcidIsland Server.
He has been renamed, but was not on the server with the new name.

A new Player has claimed the name 'ABC'.
The Problem, all '/acid' commands affects the old player, not the new one.

I think, a simple workaround would be, to allow UUIDs as parameter for the '/acid' commands

**Comment by tastybento** [comment]
Thanks for letting me know about this use case. Is this an offline server?

There is a file called 'name-uuid.txt'. Could you share it via pastebin.com? Also, the UUID of the old and new player would be useful (assuming you have an online server).
 
A quick fix would be to find ABC in name-uuid.txt and replace it with the new player's info.

However, I'd like to look at the file so I can make this automatic.

**Comment by Blacksheep92** [comment]
Hey,
thanks for the fast answer!
It is a server in a bungeecord network. (So the server is running in offline mode, yes.)

Here are some informations:

**New UUID:**
4818d29b-dcf4-4fdc-9dbd-06979709a363
Current Name: Zeropower1989

**Old UUID:**
93314114-0668-42d9-a740-471b880d6848
Old Name: Zeropower1989
Current Name: lilchig


**name-uuid.txt contains**

zeropower1989
4818d29b-dcf4-4fdc-9dbd-06979709a363

& no entry for 93314114-0668-42d9-a740-471b880d6848

so there is nothing to change.^^

**Comment by tastybento** [comment]
I can't see why it wouldn't work then. Which /acid commands act strangely?

**Comment by Blacksheep92** [comment]
I have a unregistered island, and '/acid register Zeropower1989' registered the old UUID '93314114-0668-42d9-a740-471b880d6848' to that island.

A 'acid register 4818d29b-dcf4-4fdc-9dbd-06979709a363' would be perfect to fix this 😃

**Comment by Blacksheep92** [comment]
Hey, Could you make progress with the problem?
You can also come to our server & test it.

**Comment by tastybento** [comment]
Okay, I replicated this. I'm working on a fix now.

**Comment by tastybento** [comment]
This will be fixed in the latest release.
Quick fix/workaround - make sure there are no players on the old player's island. You can find the location of it by looking in the islands.yml file. The system is grabbing the name from that and caching it. The new version will use the name database first to avoid this problem.
