### ISSUE TITLE
Can you add Vietnamese ?

### ISSUE THREAD

**Issue by phjtieudoc** [tastybento/askyblock#490]
Can you add Vietnamese into your plugins askyblock, tastybento ?

**Comment by tastybento** [comment]
It is possible, but I need a translation!

**Comment by phitieudoc** [comment]
Can I join in your translation team ?

**Comment by tastybento** [comment]
Please feel free. You can submit it to this ticket or submit it as a github pull request to 3.0.6.

**Comment by phitieudoc** [comment]
Where can I submit it ??
Can you give me a link ?

**Comment by tastybento** [comment]
You can use pastebin.com and then post the link.

**Comment by phitieudoc** [comment]
Tks ! But is this the link of the file I need to translate ?
https://github.com/tastybento/askyblock/blob/master/locale/en-US.yml
Can I use word 2007 or 2003 to translate ? Because I don't know anything about program !

**Comment by phitieudoc** [comment]
This is the link of the file I am translating: https://www.dropbox.com/sh/t0gg1r9ei92194z/AAAU6PqYOI6a-TVOXQafeMIoa?dl=0

**Comment by tastybento** [comment]
Okay, let us know when it is done. If you know how to use github, you can fork ASkyBlock to your account, select the 3.0.6 branch, add the file to the locale folder, and then submit it back to me as a Pull Request. This will then get your name added to the contributors list. If that is too difficult, just paste the file with a comment at the top with your name for recognition.

**Comment by tastybento** [comment]
@phitieudoc Can you do it? If not, that's okay.

**Comment by phjtieudoc** [comment]
Oh ! It's already done but I don't know how to post it :(

**Comment by phjtieudoc** [comment]
I dunno if it work but here is the link : http://pastebin.com/TPywkgzf

**Comment by Poslovitch** [comment]
@phjtieudoc This pastebin is private, so we cant see it

**Comment by tastybento** [comment]
@phjtieudoc Please make your paste public or pastebin it again publicly.
