### ISSUE TITLE
Nether world - problem with generating

### ISSUE THREAD

**Issue by EvilZone36** [tastybento/askyblock#495]
Hello there. I got problem. Plugin can make nether automaticaly if is set TRUE in config but it generate only this: [Screen](https://ctrlv.cz/shots/2017/01/15/yEoP.png)
A tried make another Nether world via multiverse core and copy into skyblock nether world but everything goes wrong.

**Comment by tastybento** [comment]
If you want to use the regular nether, then you need to change the nether settings to not use the "newnether" in config.yml AND delete the complete ASkyBlock_nether world. Then it will be generated.
