### ISSUE TITLE
Player got a new island when he entered Nether portal

### ISSUE THREAD

**Issue by wasder** [tastybento/askyblock#496]
His original island still exists, there is a warp there.
![](http://i.imgur.com/NZlaZJU.png)
How could this happen? How can I return his island to him?

**Comment by tastybento** [comment]
Can you give a step by step recount of what happened? I can't understand how that could possibly happen. Do you have any config changes from default? If so, please pastebin your config.yml

**Comment by wasder** [comment]
He have played for about a month already. He entered Nether before, but today when he entered the portal he got a message that a new island was created and he found himself on a new island.
http://pastebin.com/JEbnWDQg

**Comment by tastybento** [comment]
I see that makeislandifnone: true. That means that if the plugin detects the player does not have an island one will be made. The only reason I can think this will occur is if his UUID changed, or if he was unregistered from his island.

**Comment by wasder** [comment]
Seems like it messed up with our internal system. We have our unique uuids.

**Comment by tastybento** [comment]
Yes, the whole premise of a Unique User ID (UUID) is that it is unique and never changes, as opposed to player names. If the UUID changes, then the plugin has no idea who the player is and will generate a new island for them. I recommend you do not change UUID's. I'll close this now. All the best!
