### ISSUE TITLE
Really bad bug with /island reset

### ISSUE THREAD

**Issue by AnonymousHitman** [tastybento/askyblock#497]
When players do /island reset and they teleport to their island, they cant edit the island. When they fly out of their island into the void it doesnt say 'leaving (player) island either. Please get back to me asap

**Comment by tastybento** [comment]
You need to post more information. 

1. What is the server version and plugin version you are using?
2. Describe step by step how to cause the problem, e.g., does it happen to all players?
3. What did you change? Post your config.yml to pastebin so we can see it.

As a quick fix, you can try to stop the server, move islands.yml to islands.old and restart. That may help.

**Comment by AnonymousHitman** [comment]
I figured it out. I had to reset it again because it was in a part that had spawn protection to I went to server.properties and changed the spawn protection to 0

**Comment by tastybento** [comment]
Ok, good.
