### ISSUE TITLE
Reset of Islands

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#498]
Unsure if this would be possible.. Players create an island and then they pass they stuff on and then join there friends island that they passed stuff to. Any way f fixing this or a way around it?

**Comment by tastybento** [comment]
Players have limited resets and reset cooldowns. You need to set those so that it's a pain to do this. You can also make it so that there's no visitor dropping/pickup and also stop coop if you really must.

**Comment by Steev93** [comment]
I have done that, it's set at 3000 Minutes but they join there friends island which has no time restriction after they create or reset an island. Goto Spawn and pass items/or move to an Enderchest since Enderchests are allowed to keep items. Coop is disabled

**Comment by Steev93** [comment]
I have done that, it's set at 3000 Minutes but they join there friends island which has no time restriction after they create or reset an island. Goto Spawn and pass items/or move to an Enderchest since Enderchests are allowed to keep items. Coop is disabled

**Comment by tastybento** [comment]
There's not much that can be done then in that case. Sorry.
