### ISSUE TITLE
Two Questions: Regarding Events API and World Saving

### ISSUE THREAD

**Issue by Fluxty** [tastybento/askyblock#499]
First issue: 
- If a player is present on an island, and teleports to another island, island enter event is never called (it would seem only island exit event is called)

Second:
- Is there any world saving in askyblock? We only need to save the askyblock world regularly, and Bukkit world save every 20 minutes hangs the server for a bit.

**Comment by tastybento** [comment]
I'll mark the first as a bug. I haven't tested it yet but if that does not happen it is a bug. 

For the second, the plugin saves its own data regularly but not the world. That is the server's job.

**Comment by tastybento** [comment]
Hey, I just tested and I see the enter and exit events called okay. I'm not sure why you are not seeing them. If you can provide more info, I'll look into it.
