### ISSUE TITLE
Per-schematic Companion Type Doesn't Change

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#50]
I want to change per-schematic companion type, but it doesn't want to change. Is it a bug? or am i missing something?

this is my config on schematic:

skyblock:
      icon: GRASS
      order: 3
      name: "Skyblock"
      description: "Original Skyblock|Stranded in Acid Island|with a Cute Companion!"
      filename: skyblock.schematic
      # All the goodies are inside the schematic
      useDefaultChest: false
      # Biome can be set here
      biome: PLAINS
      # If schematic should paste blocks without physics or not
      usephysics: true
      #permission: any.perm.you.like
      # This optional block determines where the player will spawn. It must be unique in
      # the schematic and will be replaced by air when pasted.
      #spawnblock: SPONGE
      companion: VILLAGER
      companionnames:
      - "&9[player]'s Companion"
      - "&dSoul mate"
      - "&cJane"
      partnerSchematic: nether

**Comment by tastybento** [comment]
The correct format is for the companion to be listed like below with a - sign before it:

    skyblock:
      icon: GRASS
      order: 3
      name: "Skyblock"
      description: "Original Skyblock|Stranded in Acid Island|with a Cute Companion!"
      filename: skyblock.schematic
      # All the goodies are inside the schematic
      useDefaultChest: false
      # Biome can be set here
      biome: PLAINS
      # If schematic should paste blocks without physics or not
      usephysics: true
      #     permission: any.perm.you.like
      # This optional block determines where the player will spawn. It must be unique in
      # the schematic and will be replaced by air when pasted.
      #spawnblock: SPONGE
      companion:
      - VILLAGER
      companionnames:
      - "&9[player]'s Companion"
      - "&dSoul mate"
      - "&cJane"
      partnerSchematic: nether
