### ISSUE TITLE
Problem with the choice of default island

### ISSUE THREAD

**Issue by D3athw0rld** [tastybento/askyblock#501]
Hi, I have a very strange problem. 
When I change the name of the "island" Schematic in config.yml, an island named "island" appeared, I don't know why, here is my config : 
http://pastebin.com/Cw9Ti8v0

And here is the screen of the GUI for choice the Island : 
http://prntscr.com/e65xhk

Thanks, and sorry for my bad english

**Comment by tastybento** [comment]
The line:

island:

Must be

default:

You cannot change this heading. You can give the island another bane but do not change the heading.

**Comment by D3athw0rld** [comment]
That works, thanks ! :D
