### ISSUE TITLE
Using ASkyblock as a default generator

### ISSUE THREAD

**Issue by Nev3rGiveUp** [tastybento/askyblock#505]
I followed the guide from the FAQ for the default island world. I did everything like it should be.
I get this error in my console. The strange thing is that there is no "useowngenerator:" option in the config.

 [ERROR]: [ASkyBlock]  The Generator for ASkyBlock is not registered so the plugin cannot start
[ERROR]: [ASkyBlock] If you are using your own generator or server.properties, set useowngenerator: true in config.yml
[ERROR]: [ASkyBlock] Otherwise:
[ERROR]: [ASkyBlock] Make sure you have the following in bukkit.yml (case sensitive):
[ERROR]: [ASkyBlock] worlds:
[ERROR]: [ASkyBlock] # The next line must be the name of your world:
[ERROR]: [ASkyBlock] ASkyBlock:
[ERROR]: [ASkyBlock] generator: ASkyBlock

This is a fresh install of Askyblock with no customization and it's the latest version. I am sorry if I miss anything but I couldn't find my mistake. I've been searching 3 hours for a solution.

**Comment by tastybento** [comment]
I assume you followed this?
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#how-do-i-set-up-my-server-so-that-askyblock-is-the-main-world

Paste your bukkit.yml and config.yml to pastebin.com and then paste the link. YML is tricky, the spaces have to be exactly spaces, not tabs.

**Comment by Nev3rGiveUp** [comment]
http://pastebin.com/088UWk9b - this is my bukkit.yml
http://pastebin.com/4ah6ymAT - this is my config.yml

Thanks for the fast response!

**Comment by tastybento** [comment]
Everything works great. I made a clean server install and it works fine with your files. I assume you are stopping the server and restarting and not using reload right? I'm using 1.11.2.

Here's what I did:

1. Started server in new folder
2. Accepted EULA and restarted
3. Stopped server
4. Put ASkyBlock and Vault into plugins
5. Restarted, logged in, made an island, logged out, stopped server.
6. Replaced ASkyBlock config.yml with your config.yml.
7. Edited server.properties to set the level as ASkyBlock.
8.Edited bukkit.yml to be your bukkit.yml.
9. Restarted server
10. Logged in, worked ok.

Sorry, I'm not sure where it isn't working for you.

**Comment by Nev3rGiveUp** [comment]
I did exactly that. Well... let me repeat it again and see if it's going to work. Sorry for the late answer.

**Comment by Nev3rGiveUp** [comment]
It's doing the same thing, I am on the latest version of spigot. The only thing that I wonder is - do I need multiverse?

**Comment by tastybento** [comment]
At this point, I recommend using multiverse. https://www.spigotmc.org/resources/multiverse-core.390/

**Comment by Nev3rGiveUp** [comment]
Okay, there is definitely a problem with one of my current plugins. I did a fresh install without a single plugin (only Vault and ASkyBlock) and everything worked. I'm really sorry.
