### ISSUE TITLE
Switching from Old Nether to New Nether Problem

### ISSUE THREAD

**Issue by dwgr8golfer** [tastybento/askyblock#506]
Hello,

When I first added askblock to my server I wanted to use the Old Nether instead of the New Nether. I changed the config.ywl newnether to be false.

Now I want to switch from the Old Nether to the New Nether.  I delete the askyblock_nether folder and update the config.ywl to create the new nether. 

When I restart the server, the nether generates as a standard nether without islands.  When players walk around the nether they find areas marked as being islands. But there are no islands.  Certain areas say "Now entering {players} island". Only that {player} can edit blocks in that area. But like I said earlier there are no islands. Just a standard nether.

I am not sure how to fix this.

**Comment by tastybento** [comment]
Are you using Multiverse?

if so, this should work:

1. Stop server
2. Delete the world ASkyBlock_nether
3. Restart the server

Players who happen to be in the Nether will log in and find themselves flying in the nether void. They can get back to their island by doing /is. Then when they go through their portal again, a nether island will be generated for them.

If ASkyBlock is your primary world (listed in server.properties) then you need to tell the server that the generator for it is ASkyBlock. Follow the instructions here: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#how-do-i-set-up-my-server-so-that-askyblock-is-the-main-world

Then do the steps above to remove the nether.

**Comment by dwgr8golfer** [comment]
This is fixed. Thank you for the help tastbento!
