### ISSUE TITLE
Limit teleporting to the aSkyBlock world.

### ISSUE THREAD

**Issue by Retvenit** [tastybento/askyblock#507]
Hi I'm trying to limit teleport commands granted to players by this plugin so that they can only be used from within the aSkyBlock world, (I want to force my players to find and use multiverse gates to go from world to world).

"/island warp" seems to be governed just fine by the "askyblock.island.warp" permission node.

However I'm having problems limiting "/island" and "/island spawn".

Looking at the [plugin's pages](https://www.spigotmc.org/resources/a-skyblock.1220/) I can't find a permission node for "/island spawn" at all, and while it looks like "askyblock.island.go" should govern "/island" it just doesn't seem to work, (I've used other nodes to block other commands to test that's not a setup issue at my end).  I noticed that the help page [here](https://github.com/tastybento/askyblock/wiki) doesn't include the askyblock.island.go permission node.  Has the node been removed from the plugin?

An option in the config file to limit all three teleportation commands so that they can only be used from within the askyblock world would be awesome.  (It would be even more awesome if you were also to add a config option to turn off challenges, then I wouldn't need to mess around with permission plugins and nodes at all ;p).

Failing that are there any nodes other than "askyblock.island.go" that I could use to limit the use of "/island" and "/island spawn"?  Or could permission nodes for these commands be added? 

thanks, sorry for the long post

**Comment by Retvenit** [comment]
err, sorry I see that "/island warp" is not one of the rogue commands, (its being managed just fine by "askyblock.island.warp").  It's just "/island", and "/island spawn" that are being feisty.  

A config option to limit all three teleport commands to the skyblock world only would still be awesome though :)

**Comment by Retvenit** [comment]
*slaps forehead*  So I finally thought of using the askyblock.island.* parent permission node which brought "/island" and "/island spawn" under control just fine (so specific permission nodes for them must be in there... somewhere).

guess this is more a matter of curiosity now, what are the specific permission nodes for "/island" and "/island spawn" if you don't mind me asking?

err, it could also be feature request(s):  For a config option to limit teleporting to within the skyblock world only, for a config option to disable challenges (similar to how you can disable minishop)...   and while I'm at it a config option to randomly vary the starting heights of each island within given limits would also be awesome! 

ty for the plugin btw it does everything (and more) that I need for my server :)

**Comment by tastybento** [comment]
Actually, this is a bug. The go permission is not being enforced and like you say, there should be a spawn permission too. Also, I will add a reset perm to make every command have a perm.

**Comment by tastybento** [comment]
All done. Your workaround is good, but this will provide finer control.

**Comment by Retvenit** [comment]
sweet, thanks heaps.  That was fast!
