### ISSUE TITLE
ASkyBlockAPI calculateLevel is broken

### ISSUE THREAD

**Issue by marint94** [tastybento/askyblock#509]
public boolean calculateIslandLevel(UUID playerUUID) {
        if (plugin.getPlayers().inTeam(playerUUID) && !plugin.getPlayers().hasIsland(playerUUID)) {		
            new LevelCalcByChunk(plugin, playerUUID, null, false);
            return true;
        }
        return false;
    }

Take a look at this.
Why can you only calculate a island level if someone doesn't have an island and is in a team? WTF is that?

**Comment by tastybento** [comment]
It's a bug and fixed in the latest branch.
