### ISSUE TITLE
Scoreboard WARN: no push

### ISSUE THREAD

**Issue by SlimeDog** [tastybento/askyblock#510]
Spigot 1.11.2, ASB 3.0.5.4
WARN on startup

> [12:28:37] [Server thread/INFO]: [ASkyBlock] Enabling ASkyBlock v3.0.5.4
[12:28:37] [Server thread/WARN]: [ASkyBlock] Problem removing no push from scoreboard.

**Comment by tastybento** [comment]
Fixed with a6962ed

**Comment by SlimeDog** [comment]
Fast, once I filed. :)

**Comment by tastybento** [comment]
I aim to please!
