### ISSUE TITLE
Error in Nether Island Generation

### ISSUE THREAD

**Issue by YouGamePlayHD** [tastybento/askyblock#515]
Hey,
on my server I'm using your plugin and I have experienced this error:
I changed the nether schematic, deleted the nether world and then restarted the server, When I enter the portal of a standard island, I get in a perfectly fine nether. But when I use a portal from the double island, there are gaping holes everywhere and islands are split in halves, the other half not being copied. What could this be? No errors in the console, here the config:
http://pastebin.com/SumKv5pU
Thanks in advance.

**Comment by tastybento** [comment]
I've no idea. Can you dropbox me your schematic so I can try it?

**Comment by YouGamePlayHD** [comment]
Here you go:
https://www.mediafire.com/?ll622357drsbs78

**Comment by YouGamePlayHD** [comment]
Here you go:
http://www.mediafire.com/file/ll622357drsbs78/nether.schematic

**Comment by tastybento** [comment]
Seems to work okay. Does this always happen? Can you run more tests to see if it's random? You can also try turning off entities and physics. Maybe it's something to do with your server not being able to paste the island so quickly.

**Comment by YouGamePlayHD** [comment]
Yeah, it always happens. I don't know...

**Comment by tastybento** [comment]
Sorry, but I don't know if there's anything I can do. I don't see this issue. The only idea I have is for you to zip up you ASkyBlock world and plugin folders and dropbox them to me so I can try with your files.

**Comment by tastybento** [comment]
What is your island protection range and island distance?

**Comment by YouGamePlayHD** [comment]
Wait, I fixed the problem myself. Thanks for your support ;)
