### ISSUE TITLE
Adding a island

### ISSUE THREAD

**Issue by iTwitchTV** [tastybento/askyblock#516]
When I try to add an island to my server it doesn't show up in the gui. I have the it the same name in the schematic and in the config heres a link to my config in a pastebin please tell me how to fix this. respond ASAP if possible

config --> http://pastebin.com/xJ3b9jnM

**Comment by tastybento** [comment]
The config works fine. Maybe there's an error in your schematic. What does it say when you do /asadmin reload? What do you see in the console when you start the plugin (look for ERROR)?

**Comment by iTwitchTV** [comment]
Oh turns out there was no bedrock in the island thank you so much ive been trying for a day to get this right

**Comment by tastybento** [comment]
ok
