### ISSUE TITLE
3.0.6 Bug: no language file can be chosen

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#517]
On:
   defaultlanguage: es-ES

I have the file es-ES.yml with my translation but it uses the en-US file by default.

**Comment by Poslovitch** [comment]
Could not reproduce this bug. What server and version are you running? Do you have any errors in the console logs?

**Comment by YellowZaki** [comment]
I'm using the latest 3.0.6 release. There is no console errors. When I copy the translation to en-US, it works, so it is not a malformed translation.

**Comment by tastybento** [comment]
@YellowZaki have you set your language to Spanish? Using the /is lang command? The default language in config.yml will only be for new players.

**Comment by YellowZaki** [comment]
I don't remember if I set my language to Spanish (I think I have never used the /is lang command, and I disabled that command for my players).
I have erased all the language files and I have kept the en-US with the spanish translation. So now there won't be any problem with old players/new players, they will be forced to use the only one file.

**Comment by tastybento** [comment]
ok closed for now.
