### ISSUE TITLE
GUI Spacing

### ISSUE THREAD

**Issue by iTwitchTV** [tastybento/askyblock#519]
I'm not sure if there is a option in the config that I have to enable or if this isn't possible while using aSkyblock but i'm trying to put spacing in between the island options. ill link my config in a pastebin

http://pastebin.com/MDv8Xb0y

**Comment by Poslovitch** [comment]
Idea has already been suggested
Duplicate of #439

**Comment by tastybento** [comment]
Yes, it's something we'll do in the future.
