### ISSUE TITLE
Do not incinerate in Nether Portal

### ISSUE THREAD

**Issue by Westus** [tastybento/askyblock#524]
Core: 
- Thermos-1.7.10-1614-server

Plugins:
- LuckPerms v3.0.0
- WorldEdit v6.1
- Vault v1.6.6
- WorldGuard v6.1
- ASkyBlock v3.0.5.4
- Essentials v2.0.1-b467
- EssentialsSpawn v2.0.1-b467

![2017-02-25_16 17 41](https://cloud.githubusercontent.com/assets/4818769/23331076/35d22bba-fb6f-11e6-94a6-c8ce4ea3d99c.png)

**Comment by tastybento** [comment]
If you remove WG does it work? It looks like fire is not enabled.

**Comment by Westus** [comment]
The problem was found. Server dropped after starting "level-name = ASkyBlock"
