### ISSUE TITLE
Missing chunks

### ISSUE THREAD

**Issue by wasder** [tastybento/askyblock#525]
Latetly sometimes newly created islands or reseted one are missing chunks
![](http://i.imgur.com/SkBg4zH.png)
What could be the reason to that?

**Comment by tastybento** [comment]
What server version are you using?

**Comment by wasder** [comment]
![](http://i.imgur.com/345vdXX.png)

**Comment by tastybento** [comment]
What is your island distance and island protection range?

**Comment by wasder** [comment]
Oh god. We have island distance set to 265 (odd) for some reason. I have no idea why it was set to that, as we have been setting this yet in September 2015.
Protection range is 200, though.
Could this be the reason? Why did it manifeste only now?

**Comment by tastybento** [comment]
That is odd. First, it should be an even number and second, it's a weird value. The concern I have is that it was changed mid game. That could cause problems. Have a look at islands.yml. There will be 5 numbers at the start of each a line like this:

ASkyBlock:
- -200:115:0:100:200....

The first 3 numbers are the island location, the 4th is the protection range and the 5th is the island distance. That 5th number _should_ be the same for each island. If you see different numbers e.g., 265 and something else, then you have a problem. How big will depend on how many islands are using the newer number.

**Comment by wasder** [comment]
I checked it and it is all the same since start - 265. There are 10076 island's records, holy shit.

**Comment by tastybento** [comment]
Okay, that's good. You may want to run a purge on your server, start with 120 days and then do 90, then 60 maybe. After a purge, restart the server and new island will infill from the center.

Let's just monitor this issue. If the distance is 265 and the protection is 200, then there is plenty of space between the islands and deletion should not be causing it. I can only think that the island isn't being fully pasted for some reason. I'm not sure why.

**Comment by wasder** [comment]
I purged as you said and it seemed to solve th problem. I guess that the problem was with ultra big world (9.7 gb).

I thought that I had purged islands some time ago, but not. Now I realise that you have to stay on server all the time the proccess is going. It's somehow confusing or must be documented. 

Thanks.

**Comment by tastybento** [comment]
I recommend you purge via the command console. I'm not sure about having to stay online if you are a player, but that could be true. I'll check into it. It's supposed to run in the background.

**Comment by tastybento** [comment]
Closing for now.
