### ISSUE TITLE
Command rewards with Island Level

### ISSUE THREAD

**Issue by YouGamePlayHD** [tastybento/askyblock#526]
Hey,
can you add a possibility to specify commands when a player reaches a certain level (like the Cobblestone-Gen)?

**Comment by tastybento** [comment]
Maybe. However, you can do that right now with a level challenge. When the player reaches that level, they hit the challenge and it'll run your commands. You can make it a "free" challenge, i.e., not linked to any challenge level so they can hit the button anytime. To make free challenges, just don't give them a level.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#23
