### ISSUE TITLE
On and off can set the default permissions

### ISSUE THREAD

**Issue by ItsMennyo** [tastybento/askyblock#527]
Add in V3.0.6 you can enable or disable the default permissions. I now have KitPvP on the same server where I SkyBlock to do and now they can sort of combat logging on /is

**Comment by tastybento** [comment]
Can you explain more what you mean? Are you talking about Settings?

You can allow or disallowed players to use Settings using permissions. Any setting can be prevented. The instructions are in config.yml.

**Comment by ItsMennyo** [comment]
By default, you have been given permissions such as:
        askyblock.island.*
        askyblock.team.create
        askyblock.team.kick
        askyblock.team.makeleader
        askyblock.team.join
        askyblock.intopten
so if you multiple game modes / worlds have on your server so they can just go from KitPvP SkyBlock and that's not entirely the point. So my question was whether you can create an option that the default permissions are out and put them by hand into my permission system.

I hope it's a bit obvious because I use Google -,-

**Comment by tastybento** [comment]
I do not completely understand your request. Is this a permissions question? 

Askyblock gives some permissions by default. You can remove any permission you like by giving the negative permission. For example, using PEX do:

/pex group default add -askyblock.team.create

If you want different permissions in different worlds then add them for that world only. For example,

/pex group default add askyblock.team.create ASkyBlock

I hope that helps you.

**Comment by ItsMennyo** [comment]
Thanks, this is what I mean LAMO...
