### ISSUE TITLE
Suggestion - possibility to have more than one island

### ISSUE THREAD

**Issue by PhantasiaMC** [tastybento/askyblock#533]
Hi ^^

An idea that popped up in my mind : is it possible to offer player the possibility to have more than one island ? This would be nice moreover when they want to join another player island, so they don't lose their own island in case of.

Best regards,

Maxime :)

**Comment by tastybento** [comment]
This is possible via the coop system. It doesn't give a player multiple islands of their own, but they can buddy up with others without losing their own island.
