### ISSUE TITLE
Event Exit and Enter are reversed

### ISSUE THREAD

**Issue by Cristaling** [tastybento/askyblock#534]
If a player switches from a island to another, the events are reversed:

`// Fire exit event
            final IslandExitEvent event = new IslandExitEvent(e.getPlayer().getUniqueId(), islandTo, e.getTo());
            plugin.getServer().getPluginManager().callEvent(event);
            // Fire entry event
            final IslandEnterEvent event2 = new IslandEnterEvent(e.getPlayer().getUniqueId(), islandFrom, e.getFrom());
plugin.getServer().getPluginManager().callEvent(event2);`

This is starting at line 443 in IslandGuard in listeners package.

**Comment by tastybento** [comment]
Thanks!
