### ISSUE TITLE
Issue With Custom Islands

### ISSUE THREAD

**Issue by iSkiddsPvP** [tastybento/askyblock#537]
Issue when trying to set up custom islands
Log: http://pastebin.com/H6Yb6aES
Schematic Section: http://pastebin.com/50CENrM0

**Comment by tastybento** [comment]
Thanks - I need the schematic file for testing. Can you dropbox it and share the link?

**Comment by tastybento** [comment]
Also, what did you use the make the schematic (WorldEdit version?)

**Comment by iSkiddsPvP** [comment]
Yeah, sure thing, I shall send them over ASAP. Probably tonight

On 7 Mar 2017, at 20:50, tastybento <notifications@github.com> wrote:

Also, what did you use the make the schematic (WorldEdit version?)
