### ISSUE TITLE
Exclude Player From Top Island

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#54]
Can you set new permission to exclude a player from top island? 

I usually have staff who plays arroud with world edit in his island.

**Comment by tastybento** [comment]
Okay.

One work around until then is to remove this permission from the staff - acidisland.island.info or askyblock.island.info. This will prevent them from using /is level. Then make their island level 0 (edit their player file) and then do /asadmin topten to wipe them off the list.

**Comment by fikry13** [comment]
can i help you fix this?

**Comment by tastybento** [comment]
Sure!
Make sure you do a pull of 2.9.6 branch.

**Comment by tastybento** [comment]
Fixed in V2.9.6. Actually I had to change the way it was checked to avoid problems with offline players. Only online player's permissions can be checked.
