### ISSUE TITLE
Island level on a variable

### ISSUE THREAD

**Issue by ChamuGamer** [tastybento/askyblock#540]
You can help me store the island level in a variable so I can send it in a sendMesssage or put the variable on a scoreboard
See on 
Team line5 = board.registerNewTeam("line5"); line5.addEntry("§5");
		**//line5.setPrefix(ChatColor.GREEN + "" + ChatColor.GOLD + "" + askyblock.calculateIslandLevel(player.getUniqueId()));**
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
`package com.hotmail.chamugamer;

import java.util.*;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
//import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitScheduler;
import org.bukkit.scoreboard.DisplaySlot;
import org.bukkit.scoreboard.Objective;
import org.bukkit.scoreboard.Scoreboard;
import org.bukkit.scoreboard.ScoreboardManager;
import org.bukkit.scoreboard.Team;

import com.wasteofplastic.askyblock.ASkyBlockAPI;
import com.wasteofplastic.askyblock.events.IslandLevelEvent;

public class Main extends JavaPlugin implements Listener {

	public static ArrayList<String> A = new ArrayList<String>();

	private ASkyBlockAPI askyblock = ASkyBlockAPI.getInstance();
    private Set<UUID> playersWaiting = new HashSet<UUID>();

    public void IslandLevelCalc() {
    	this.playersWaiting.clear();
        }
    
    public void getPlayersLevel(Player player) {
    	// Add to the list of players that I'm asking levels for
    	playersWaiting.add(player.getUniqueId());
    	// Kick off the island calculation. When it is done, it will fire the IslandLevelEvent
    	askyblock.calculateIslandLevel(player.getUniqueId());
    	//Int islevel = askyblock.calculateIslandLevel(player.getUniqueId());
    	Bukkit.getConsoleSender().sendMessage(ChatColor.GREEN + "Nivel de isla " + ChatColor.GOLD + "" + askyblock.calculateIslandLevel(player.getUniqueId()));
        }
        
        /**
         * Called when any island level calculation is complete. If it was by use
         * do something, otherwise ignore.
         * @param event
         */
        @EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
        public void onNewLevel(final IslandLevelEvent event) {
    	//Bukkit.getLogger().info("Island level event");
    	// Check to see if this is a player that was requested
    	if (playersWaiting.contains(event.getPlayer())) {
    	    // It was, so remove them from the set and then do something
    	    playersWaiting.remove(event.getPlayer());
    	    // DO SOMETHING
    	}
        }
	
	public void onEnable() {
		Bukkit.getPluginManager().registerEvents(this, this);
		Bukkit.getConsoleSender().sendMessage(ChatColor.GREEN + "AnimateScoreboard is now enabled!");

		saveConfig();
		getConfig().options().copyDefaults(true);

		Bukkit.getServer().getPluginManager().getPlugin("Askyblock");
		
	}

	public void add(final Player player) {
		final ScoreboardManager manager = Bukkit.getScoreboardManager();
		final Scoreboard board = manager.getNewScoreboard();
			    
		final Objective objective = board.registerNewObjective("Scoreboard", "dummy");
		objective.setDisplaySlot(DisplaySlot.SIDEBAR);

		playersWaiting.add(player.getUniqueId());
		
		// Header
		// String hline2 = getConfig().getString("Scoreboard.Header");

		Team line1 = board.registerNewTeam("line1");
		line1.addEntry("§1");
		line1.setPrefix(getConfig().getString("Scoreboard.Content.1"));

		Team line2 = board.registerNewTeam("line2");
		line2.addEntry("§2");
		line2.setPrefix(getConfig().getString("Scoreboard.Content.2"));
		line2.setSuffix("§fChamuGamer");

		Team line3 = board.registerNewTeam("line3");
		line3.addEntry("§3");
		line3.setPrefix(getConfig().getString("Scoreboard.Content.3"));
		line3.setSuffix("§6§lGood");

		Team line4 = board.registerNewTeam("line4");
		line4.addEntry("§4");
		line4.setPrefix(getConfig().getString("Scoreboard.Content.4"));

		 Team line5 = board.registerNewTeam("line5"); line5.addEntry("§5");
		**//line5.setPrefix(ChatColor.GREEN + "" + ChatColor.GOLD + "" + askyblock.calculateIslandLevel(player.getUniqueId()));**

		Team line6 = board.registerNewTeam("line6");
		line6.addEntry("§6");
		line6.setPrefix(getConfig().getString("Scoreboard.Content.6"));

		Team line7 = board.registerNewTeam("line7");
		line7.addEntry("§7");
		line7.setPrefix(getConfig().getString("Scoreboard.Content.7"));

		Team line8 = board.registerNewTeam("line8");
		line8.addEntry("§8");
		line8.setPrefix(getConfig().getString("Scoreboard.Content.8"));
		line8.setSuffix("§fjugar");

		Team line9 = board.registerNewTeam("line9");
		line9.addEntry("§9");
		line9.setPrefix(getConfig().getString("Scoreboard.Content.9"));

		Team line10 = board.registerNewTeam("line10");
		line10.addEntry("§0");
		line10.setPrefix(getConfig().getString("Scoreboard.Content.10"));
		line10.setSuffix("§e253.133");

		objective.getScore("§1").setScore(10);
		objective.getScore("§2").setScore(9);
		objective.getScore("§3").setScore(8);
		objective.getScore("§4").setScore(7);
		objective.getScore("§5").setScore(6);
		objective.getScore("§6").setScore(5);
		objective.getScore("§7").setScore(4);
		objective.getScore("§8").setScore(3);
		objective.getScore("§9").setScore(2);
		objective.getScore("§0").setScore(1);

		A.clear();
		A.add("1");

		BukkitScheduler Scheduler = Bukkit.getServer().getScheduler();
		Scheduler.scheduleSyncRepeatingTask(this, new Runnable() {
			@Override
			public void run() {
				Integer i = A.size();
				if (i == 1) {
					objective.setDisplayName(Colors("&f&lSkyblock"));

					A.add("A");
				}
				if (i == 2) {
					objective.setDisplayName(Colors("&2&lSkyblock"));
					@SuppressWarnings("unused")
					class testWhile {
						public void main(String[] args) {
							int i = 0;
							while (true) {
								i++;
								String me = "h" + i;
								Bukkit.broadcastMessage(ChatColor.RED + (player.getDisplayName() + me));
								if (i == 9) {
									break;
								}
							}
						}
					}

					A.add("B");
				}
				if (i == 3) {
					objective.setDisplayName(Colors("&f&lSkyblock"));
					A.add("C");
				}
				if (i == 3) {
					A.clear();
					A.add("1");
				}
			}
		}, 0, 5);
		player.setScoreboard(board);
	}

	public static String Colors(String text) {
		return text.replaceAll("&", "§");
	}

	@EventHandler
	public void PlayerJoinEvent(PlayerJoinEvent e) {
		Player p = e.getPlayer();
		this.add(p);
	}

}`

**Comment by tastybento** [comment]
There is a bug in the API. It will be fixed in 3.0.6. 

You can use:

new LevelCalcByChunk(plugin, playerUUID, null, false);

**Comment by ChamuGamer** [comment]
I can't use this **new LevelCalcByChunk(plugin, playerUUID, null, false);** You can show me an example plsss

**Comment by tastybento** [comment]
Um, do you mean that you want to put the island level into chat? That is already supported using {ISLAND_LEVEL}.

**Comment by ChamuGamer** [comment]
Using the ASKYBLOCK API

**Comment by ChamuGamer** [comment]
I want to use it on a scoreboard

**Comment by ChamuGamer** [comment]
I need the api for use {ISLAND_LEVEL}?

**Comment by ChamuGamer** [comment]
Can you show me a example

**Comment by tastybento** [comment]
If you just want to get the player's island level when their island level changes, do this in your listener class:

```
    @EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
    public void onNewLevel(final IslandLevelEvent event) {
        plugin.getLogger().info("Island level event");
        plugin.getLogger().info("The player's UUID is " + event.getPlayer());
        plugin.getLogger().info("The player's name is " + Bukkit.getServer().getPlayer(event.getPlayer()).getName());
        plugin.getLogger().info("The player's island level is " + event.getLevel());
    }

**Comment by ChamuGamer** [comment]
`
// **LISTENER CLASS**
   @EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
    public void onNewLevel(final IslandLevelEvent event) {
        plugin.getLogger().info("Island level event");
        plugin.getLogger().info("The player's UUID is " + event.getPlayer());
        plugin.getLogger().info("The player's name is " + Bukkit.getServer().getPlayer(event.getPlayer()).getName());
        plugin.getLogger().info("The player's island level is " + event.getLevel());
    }
// MAIN CLASS
Bukkit.broadcastMessage(onNewLevel);
`
