### ISSUE TITLE
KeepInventory

### ISSUE THREAD

**Issue by Lion048** [tastybento/askyblock#541]
I would like to have my server run on keepInventory but when I do /gamerule keepInventory true It doesnt work. When my player's fall off of their SkyBlock I have to manually give it back to them which gets annoying

**Comment by tastybento** [comment]
Closing - adjust MV settings.

**Comment by Lion048** [comment]
I dont use Multi-Verse

**Comment by tastybento** [comment]
Ah, in that case - go to the ASkyBlock world itself (and the nether) and issue the command. Tell me if that works for you. (ASkyBlock doesn't actually do anything to override this command).

**Comment by tastybento** [comment]
No response.
