### ISSUE TITLE
asadmin - ClearResetAll (No locale?) - /asadmin spy (incorrect locale?)

### ISSUE THREAD

**Issue by Latouth** [tastybento/askyblock#542]
It seems the /asadmin clearresetall command uses the /asadmin clearreset <player> locale....

It says
"resets the island reset limit for player" for "PLAYER" which makes no sense on "clearresetall" ... so maybe for the clearresetall, it could be... "resets the island reset limit for ALL players"

Also, /asadmin spy says "Team chat is ON/OFF"
which team chat... I would assume like "Spy mode is enabled" and "Spy mode is disabled" not a msg about teamchat?

Just some minor issues for admins.

**Comment by Latouth** [comment]
Oh, and maybe a way of schemate-ing a island? so like
/asadmin islandschem <player>
which then saves the file to plugins/ASkyBlock/schematics/players/

**Comment by tastybento** [comment]
Thanks for the locale reports. The fixes will be in 3.0.6.
Unfortunately, saving schematics is a whole new set of functionality that isn't part of ASkyBlock. Please use WorldEdit to save schematics instead.
