### ISSUE TITLE
PvP setting is overrided by multiverse-core

### ISSUE THREAD

**Issue by SaitDev** [tastybento/askyblock#543]
I wanna make a pvp zone in skyblock world instead of using 1 more world just for pvp area.

So i build a island and change its setting allow pvp to true. But the pvp setting in multiverse is false, player cant hurt anyone. I tried change pvp setting in multiverse to true, then player can pvp anywhere.

**Comment by ChamuGamer** [comment]
You tasted with the world edit? /region flag

**Comment by tastybento** [comment]
I run MV and I've never seen this issue. I'm not sure I can help here.

**Comment by SaitDev** [comment]
I figure it out. Its just my misunderstand at all. Because I test with 2 player both have askyblock.mod.bypasslock permission. That why when multiverse pvp is true and island pvp false we still can hurt each other.
Sorry for my mistake, plz remove issue label since its actually compatibility

**Comment by tastybento** [comment]
ok
