### ISSUE TITLE
Message encoding fail?

### ISSUE THREAD

**Issue by C0LiSii0N** [tastybento/askyblock#544]
Hi, I have a little problem with the French traduction, because of the "Special caracter" like éèàî etc. The plugin replace it with some sort of wierd caracter, I think it's because of the text encoding, but when I try to put the file in UTF-8 I can't change the language to french.

**Comment by tastybento** [comment]
Please provide step by step instructions how to reproduce the issue. For example:

1. Copy fr-FR.yml to locale.yml
2. Restart server

**Comment by C0LiSii0N** [comment]
In the server I do /is lang 7 (7 for french)

**Comment by tastybento** [comment]
Oh. What server do you use? Maybe the server does not have UTF-8 French installed...

**Comment by tastybento** [comment]
No response.
