### ISSUE TITLE
Exponential Island Level calculation

### ISSUE THREAD

**Issue by ChiefMoneyBags** [tastybento/askyblock#545]
I am requesting a feature that would allow you to enable a setting in config that would make leveling up your island take exponentially more points with each level gained, much like the way gaining EXP is exponential. It would also be nice to be able to change the equation for this in config so people can control the rate at which levels are harder to obtain. You can add different equations for different is levels like the way cobble gen values change with island level. This would add a nice level balancing option for servers.

The algorithm shown below takes effect on any islands that exceed level 10, before 10 levels are all the same base value. Small example of configurable equation:

Base_Level_Points: 1000

level 10:
  required_points = points_of_previous_level * 1.05
level 250:
  required_points = points_of_previous_level * 1.1

So Level 1 - 10 would by default take 1000 points each to reach, then each level after would grow using the algorithm
level 11 - required_points = 1000 * 1.05
level 12 - required_points = 1050 * 1.05
level 13 - required_points = 1102.5 * 1.05
ETC.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#21
