### ISSUE TITLE
Trouble using /is level in a plugin (api).

### ISSUE THREAD

**Issue by Woosy** [tastybento/askyblock#546]
Hello,

I'm currently developping a plugin, where I need to get the island level of a player in order to put it into a scoreboard.
The problem is, that I didn't found a way to update it, unless with the command /is level.

I saw in the config.yml that there was a way to change the time before an is level update, but I don't really understand how to use it...

(Sorry for my shitty english, and if I wasn't clear enough, tell me and I'll give you more infos)
Thanks man.

**Comment by tastybento** [comment]
True, that's on purpose. Calculating island levels take a lot of processing power and memory. It has to scan every block in the whole island. So, the best way to do a scoreboard plugin is to listen for the IslandLevelEvent - https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/events/IslandLevelEvent.java
That will give you the island level when it is calculated by the player, or on login if you set that option in config.yml.

**Comment by Woosy** [comment]
So what's the utility of this line ? (from config.yml)
   # Island level calculation cool down in seconds
   levelwait: 60

**Comment by tastybento** [comment]
That is to prevent players from running island level calculations continually and brings down your server.

**Comment by Woosy** [comment]
Okay ! (Maybe you should explain it in the config file :P)
Thanks for taking time to reply to me, and congratz for all this awesome work.
