### ISSUE TITLE
"island Protected"

### ISSUE THREAD

**Issue by NJ2013** [tastybento/askyblock#547]
I was having a save error yesterday so i did some basic changes being it was showing old data from when i had it installed before like Is Top read as a player had 917 level when i only loaded it last week when i restarted it totally screwed up. It then acted as if the player who created the island was a guest and states the island is protected but it is that players island i dont see perms to fix and i do not see why

I had an error from the saving yesterday. For the island protected i am not getting an error so i cant post that nor troubleshoot it myself.

I did install a new jar new plugin folder as if it had never been there but when  i started it the island i had been on was there again and same issue persisted

I can try this on another bungee and see if it just is conflicting with another plugin

**Comment by tastybento** [comment]
Check you didn't change the island distance by accident.

If the islands.yml file is out of sync, stop the server, move/delete it and restart.

**Comment by NJ2013** [comment]
Thank you 
That did the trick i would have thought deleting it entirely would have done the same i thought i had done that but i guess it didnt work. It seems to be working i get no errors except from perworldinventory regarding economy which i am not using anyways. If it saves it should be fine now. 
Thanks again
