### ISSUE TITLE
Overlapping Region Spam

### ISSUE THREAD

**Issue by Fluxty** [tastybento/askyblock#549]
TacoSpigot 1.8.8, latest AskyBlock. We just made a plugin which uses the askyblock API to check if there is an island at the players location & if they are a member of that island when they right click a chest (Seller's wand item, but checking island after they've right clicked a chest). Now, this spams console (on both SkyBlock servers with this plugin)

https://hasteb.in/adoheqenax.css

Our logs get massive from this.

**Comment by tastybento** [comment]
Your islands.yml file must have become corrupted. Probably nothing to do with that plugin you wrote. Stop server, delete islands.yml and restart. You'll need to redo the island spawn if you have one.

**Comment by Fluxty** [comment]
Oh okay, that won't hurt any players getting to their islands or anything?

**Comment by tastybento** [comment]
Take backups, but no, it shouldn't cause any problems. If you still see the error, then something more sinister is happening.

**Comment by tastybento** [comment]
Open if there's a problem.
