### ISSUE TITLE
Challenge turn-in multiple times in one command

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/askyblock#551]
This is a feature request, and sadly I made it a bit way too late for your most recent update lol.

On our server we tend to get some REALLY dedicated skyblockers who get ungodly amounts of items for challenge turn-ins (slimeballs, cacti, etc) and do it one stack at a time can get really frustrating when they have a dozen double chest full of said item. Would it be possible to add an optional argument at the end of the challenge complete command for turning it in more than once?

Example: I want to complete a cactus challenge that takes 64 cacti, but I have 640 cacti and want to do it 10x:
/c c cactusfarmer 10

And that would attempt to turn in the challenge 10 times and check for 10x the required amount of items. There could also be an optional challenge config line to allow mass challenge turn ins for a challenge or not.

Thanks again for such an awesome plugin, and appreciate ya reading my idea~

**Comment by Poslovitch** [comment]
Will be made for the challenges rewrite ;)

**Comment by tastybento** [comment]
Handled in #566
