### ISSUE TITLE
Temp permission in spawn

### ISSUE THREAD

**Issue by SaitDev** [tastybento/askyblock#556]
Since 3.0.6 bring new feature that can give player temp permissions when they are in their island.
It would be great if we can grant player some temp permissions when they are in spawn too

**Comment by tastybento** [comment]
Not a bad idea.

**Comment by Poslovitch** [comment]
Add this for 4.0?

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#18
