### ISSUE TITLE
/challenge didn't work

### ISSUE THREAD

**Issue by Ewous** [tastybento/askyblock#559]
The /c didnt work after the new MAJ..

12:37:09 CONSOLE: [INFO] MELO_FTW issued server command: /c
12:37:09 CONSOLE: ERROR]: null
12:37:09 CONSOLE: exception executing command 'c' in plugin ASkyBlock v3.0.6
12:37:10 CONSOLE: Source) [?:1.7.0]
12:37:10 CONSOLE: Source) [?:1.7.0]
12:37:10 CONSOLE: Source) [?:1.7.0]
12:37:10 CONSOLE: Source) [?:1.7.0]
12:37:10 CONSOLE: java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
12:37:10 CONSOLE: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
12:37:10 CONSOLE: Source) ~[?:1.7.0]
12:37:10 CONSOLE: Source) ~[?:1.7.0]
12:37:33 CONSOLE: [INFO] MELO_FTW issued server command: /c
12:37:33 CONSOLE: ERROR]: null
12:37:33 CONSOLE: exception executing command 'c' in plugin ASkyBlock v3.0.6
12:37:33 CONSOLE: Source) [?:1.7.0]
12:37:33 CONSOLE: Source) [?:1.7.0]
12:37:33 CONSOLE: Source) [?:1.7.0]
12:37:33 CONSOLE: Source) [?:1.7.0]
12:37:33 CONSOLE: java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag

**Comment by Poslovitch** [comment]
@tastybento I think it's due to the ItemFlag.HIDE_ENCHANTS. Maybe this enum doesn't exist in 1.7?

**Comment by Ewous** [comment]
@Poslovitch my minecraft server is in Spigot 1.8

**Comment by tastybento** [comment]
What server build is it. Looks custom because it says 1.7.0.

**Comment by Ewous** [comment]
@tastybento 

 [12:36:40] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-15fa8e1-17a3db7 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by Ewous** [comment]
23:11:00 CONSOLE: ERROR]: [ASkyBlock] The updater could not contact dev.bukkit.org for updating.
23:11:00 CONSOLE: ERROR]: [ASkyBlock] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
23:11:00 CONSOLE: ERROR]: [ASkyBlock] null
23:11:00 CONSOLE: returned HTTP response code: 521 for URL: https://api.curseforge.com/servermods/files?projectIds=85189
23:11:00 CONSOLE: Source) ~[?:1.7.0]
23:11:00 CONSOLE: Source) ~[?:1.7.0]
23:11:00 CONSOLE: Source) [?:1.7.0]

**Comment by tastybento** [comment]
Yes, the curseforge api site is down. I've filed a ticket with them.

**Comment by tastybento** [comment]
@Ewous 1.8 has bugs, bad bugs. You should update to at least 1.8.8.

**Comment by Poslovitch** [comment]
And i think it's also because of CraftBukkit. You should switch on Spigot or PaperSpigot, which are more efficient.

**Comment by Ewous** [comment]
OK the /c works ! but now i have this error :

10:54:12 CONSOLE: ERROR]: [ASkyBlock] The updater could not contact dev.bukkit.org for updating.
10:54:12 CONSOLE: ERROR]: [ASkyBlock] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
10:54:12 CONSOLE: ERROR]: [ASkyBlock] null
10:54:12 CONSOLE: returned HTTP response code: 521 for URL: https://api.curseforge.com/servermods/files?projectIds=85189
10:54:12 CONSOLE: Source) ~[?:1.8.0_71]
10:54:12 CONSOLE: Source) ~[?:1.8.0_71]
10:54:12 CONSOLE: Source) ~[?:1.8.0_71]
10:54:12 CONSOLE: Source) [?:1.8.0_71]

**Comment by Poslovitch** [comment]
Glad to here it.

About the error
Do you read what is written on them?
Really, the answer of your question is on the first two lines

**Comment by tastybento** [comment]
This is a temporary issue with the bukkit web site, I've filed a ticket with them.
