### ISSUE TITLE
Can not add cocoa and Nether warts in island minishop

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#56]
It doesn't show any error but the item is not available in minishop
my setting:
    item8:
      material: COCOA
      quantity: 32
      price: 20
      sellprice: 15
   item10:
      material: NETHER_WARTS
      quantity: 32
      price: 20
      sellprice: 15

**Comment by tastybento** [comment]
You have to use INK_SACK:3 or 351:3 for the cocoa beans.
For the nether warts is actually is NETHER_STALK.

Bukkit have different names for items that you see in an inventory and a block.

**Comment by fikry13** [comment]
item8:
material: INK_SACK
quantity: 32
price: 20
extra: 3
sellprice: 15

still not working. nether_stalk is fine
