### ISSUE TITLE
Bug with fly.

### ISSUE THREAD

**Issue by Tissandre** [tastybento/askyblock#562]
Hi Tasty !

I make the update 3.0.6, and with poslovitch we discussed quite a lot, for llimited brewing stand, and guardian in the section entitylimit.

But i am here for report a bug.

In my server, player just can fly with an enchant "fly" to place in boots, i used crazy-enchantements.
No probleme before the update, but now, my players have some trouble with the fly, and ME too :/

When i try to fly, i cant :o but i am in mode creative, then i type /fly and i can fly ok, but when i go in another world, /mvtp skyfarm, i cant fly .... then i need to type /fly

Tanks for your answer.

**Comment by Ewous** [comment]
Got the same bug

**Comment by tastybento** [comment]
This will be fixed in 3.0.6.1
0b6ec740b57ae70d2c367abc7ce188c004cd30ac

**Comment by tastybento** [comment]
Fixed with 3.0.6.1.
