### ISSUE TITLE
Challenges Rewrite

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#566]
**CHECKLIST**

*Challenges*
- [ ] Requirements: permissions or challenges (or completed X-times challenges) to be able to complete (and show, so add a config option to hide challenges if their permission/challenges requirements are not completed) a challenge.
- [ ] Requirements: island levels (for PLAYER & ISLAND)
- [ ] Requirements: support for just one element from a list of items/blocks/entities (e.g: "homestead": oak door or birch door or spruce door...)
- [ ] Requirements & Rewards: Support for potion arrows, spawn eggs, enchanted books, custom named &/or enchanted items, fireworks
- [ ] Rewards: default & special repetitions rewards (e.g: default reward is stone, 5th repetition reward is dirt)
- [ ] Add: "CUSTOM" challenge type, which can only be completed by admin command or by API.
- [ ] Completion: Challenges can be completed again after an specified amount of time

*Tweaks*
- [ ] "INVENTORY" challenges will be called "PLAYER"
- [ ] List missing requirements when wanting to complete a challenge
- [ ] Add config option to make possible to complete PLAYER challenges in all worlds.
- [ ] Handle the case there are no challenge levels
- [ ] Add customisable check range for ISLAND challenges
- [ ] Require money, perms or other to unlock next level
- [ ] Add option to disable challenges (usechallenges)

*GUI*
- [ ] Convert to the new type of Panels ("Panels rewrite"): pages, no more cursor position reset, customisable...
- [ ] Display how many times the challenge has been completed (except if not repeatable)
- [ ] Challenge levels can now have their own display name & item.

*API*
- [ ] Remake challenge-related API

*Bazar*
- [ ] Challenge turn-in multiple times in one command / Click/command to complete as much as possible of the/all challenge

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#10
