### ISSUE TITLE
[Bug] Global Settings

### ISSUE THREAD

**Issue by AconTM** [tastybento/askyblock#567]
Hey everybody! 

i put the Setting "SPAWN_EGG" on True but it doesnt work! many restarts and reconfigs dont work! Pls help!

**Comment by AconTM** [comment]
#Update 

i dont can change any setting..

**Comment by tastybento** [comment]
After you change a setting in the config.yml, you need to reset everyone's setting in the game (just changing it in config.yml doesn't change previously set island settings).

Do /asadmin settingsreset SPAWN_EGGS

/asadmin settingsreset [help | all | flag]: Resets all islands to default protection settings
flag options: 
all, ACID_DAMAGE, ANVIL, ARMOR_STAND, BEACON, BED, BREAK_BLOCKS, BREEDING, BREWING, BUCKET, COLLECT_LAVA, COLLECT_WATER, CHEST, CHORUS_FRUIT, CRAFTING, CREEPER_PAIN, CROP_TRAMPLE, DOOR, EGGS, ENCHANTING, ENDER_PEARL, ENTER_EXIT_MESSAGES, FIRE, FIRE_EXTINGUISH, FIRE_SPREAD, FURNACE, GATE, HORSE_INVENTORY, HORSE_RIDING, HURT_MOBS, HURT_MONSTERS, LEASH, LEVER_BUTTON, MILKING, MOB_SPAWN, MONSTER_SPAWN, MUSIC, NETHER_PVP, PLACE_BLOCKS, PORTAL, PRESSURE_PLATE, PVP, REDSTONE, SPAWN_EGGS, SHEARING, VILLAGER_TRADING, VISITOR_ITEM_DROP, VISITOR_ITEM_PICKUP

**Comment by tastybento** [comment]
Added to FAQ: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#i-changed-an-island-setting-in-configyml-but-it-doesnt-change-on-peoples-islands

**Comment by AconTM** [comment]
It works in the Normal World (Spawn / lobby), but it doenst work on my Island

**Comment by AconTM** [comment]
ok, after "/asadmin settingsreset all" its just Finaly work ^^ thank you :)
