### ISSUE TITLE
can still open doors/furnace after selecting visitor disallowed

### ISSUE THREAD

**Issue by krustymk** [tastybento/askyblock#568]
as the title says, visitors can still use doors/furnaces

**Comment by tastybento** [comment]
I can't replicate this. What server version are you using? Also, check that the visitor doesn't have any bypass perms. Finally, if you upgraded from 3.0.6 from an earlier version, you may need to reset all the settings by doing /asadmin settingsreset all. That will reset every island to the config defaults. Let me know how it goes.
