### ISSUE TITLE
Is biomes keep saying that player doesn't have permission

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#57]
I set /is biomes permission to this group. But it keep saying that player doesn't have permission. Am i missing something?

  Esquire:
    options:
      default: 'false'
    permissions:
    - essentials.hat
    - acidisland.island.*
    - acidisland.island.biomes
    - acidisland.biomes.cold_taiga
    - acidisland.biomes.desert
    - acidisland.biomes.flower_forest
    - acidisland.biomes.hell
    - acidisland.biomes.jungle
    - acidisland.biomes.mushroom_island
    - acidisland.biomes.swampland
    - acidisland.biomes.mesa
    - acidisland.biomes.savanna
    - acidisland.biomes.roofed_forest
    - exchanger.menu

**Comment by tastybento** [comment]
Have you reflected those permissions in the config?

**Comment by tastybento** [comment]
Post the biome section of your config.yml
