### ISSUE TITLE
Can't use villager eggs?

### ISSUE THREAD

**Issue by Disorbs** [tastybento/askyblock#570]
for some reason i still cant spawn any villager eggs and everything else works fine other mob eggs but villager eggs and its not disabled in the config.yml or anything?

i also tried starting the server without aSkyblock and it worked but then i loaded aSkyblock and it
stopped working so im guessing its an issue with this plugin

Tried: /asadmin settingsreset all
didn't work

Paper spigot 1.11.2
ASkyBlock: V3.0.5.4
config.yml - http://pastebin.com/QvXYkgQQ

**Comment by tastybento** [comment]
Please update to 3.0.6. We're not fixing bugs on older versions. If you still see the same issue then file another bug report. Thanks.
