### ISSUE TITLE
Support numeric IDs for everything (chestItems,...)

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#571]
Will be easier to use ;)

**Comment by tastybento** [comment]
How do you mean? Numerical IDs are deprecated vs Materials. Also, where are they not supported?

**Comment by Poslovitch** [comment]
The numerical IDs are deprecated, but still supported in Spigot. I received this suggestion and they also told me that when you have to edit every items from the challenges it is really long

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#15
