### ISSUE TITLE
Extend /is settings to both coop & visitors

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#573]
Old idea: A menu to select what will the coop player be able to do

New idea: Like Landlord 
![ss 2017-03-26 at 03 44 54](https://cloud.githubusercontent.com/assets/20014332/24331775/47344d10-123b-11e7-93a0-80ec139ae92f.png)

In the /is settings, the leader will be able to select what the cooped players and the visitors can do.
(Purpose: avoid destruction while coop)

**Comment by tastybento** [comment]
I don't like this - too complicated.

**Comment by Poslovitch** [comment]
Please check again: I edited this idea

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#14
