### ISSUE TITLE
API -- Get warp location?

### ISSUE THREAD

**Issue by Gaurav99** [tastybento/askyblock#577]
Hey,
Could you add a method in the API to get the warp location of the island?  There's a "Island#getSpawnPoint" but if I'm not mistaken that's the members' spawn point, not the visitor warp.

Thanks!

**Comment by tastybento** [comment]
Warps are per player. So, to get the warps on an island (there could be more than one), first get a list of UUIDs of the island members (getOwner(), getTeamMembers() etc.), then use getWarp(UUID) to get the warp for each member. Done!
