### ISSUE TITLE
Enable spawner types to have different level contribution values

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#579]
Also enable Extreme spawners to contribute to level values.

**Comment by Poslovitch** [comment]
What are «Extreme» Spawners?

**Comment by tastybento** [comment]
It's a (paid) plugin that enables spawners to be merged into one. Basically, if a player gets two spawners of the same type, they can squash them together into one that will spawn twice as often.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#12
