### ISSUE TITLE
Let other users join another Island but keep theres?

### ISSUE THREAD

**Issue by OPMNetwork** [tastybento/askyblock#58]
Is there a way of allowing another user join someone elses Island but still keep theres at the same time. :) Thanks! :P

**Comment by tastybento** [comment]
Yes! Enable coop. Make sure the players have the askyblock.coop permission. Then they can use the coop commands.

**Comment by OPMNetwork** [comment]
Thanks so much! Best owner of a plugin! :P

**Comment by OPMNetwork** [comment]
Where do i find the Coop part?

**Comment by tastybento** [comment]
You just have to make sure players have askyblock.coop permission. That's it. If they have that permission then the commands will become available. They will be able to do /island coop <name> and that will make a player coop. If they want to expel them then they will do /is expel <name>. Be sure to warn players that if they coop someone, the coop player has ALL the same capabilities as themselves and can steal blocks or wreck things, so they should be careful they trust the coop player.
