### ISSUE TITLE
Villager Eggs won't work

### ISSUE THREAD

**Issue by Disorbs** [tastybento/askyblock#580]
We are not allowed to use any villager eggs and everything else works fine other mob eggs but villager eggs and its not disabled in the config.yml or anything?

i also tried starting the server without aSkyblock and it worked but then i loaded aSkyblock and it
stopped working so im guessing its an issue with this plugin

Tried: /asadmin settingsreset all
Tried: /asadmin settingsreset spawn_eggs
didn't work

Video: https://i.gyazo.com/a7c84debe84bcd47ef0c9328b6510702.mp4
Plugins: https://i.gyazo.com/3a2764feec41bf2ebc099fea759db3d0.png
Paper spigot 1.11.2
ASkyBlock: V3.0.6 (latest)
New Config: http://pastebin.com/vDGnYCQH

**Comment by Poslovitch** [comment]
On the video, we can clearly see that something cancels the villager summoning.
As far as I know, there is nothing that could stop the villager summoning inside ASkyBlock's code. Or, at least, it should have sent you a message.
Do you have any errors in the logs?

**Comment by Disorbs** [comment]
no errors let me try removing one plugin at a time and see if its conflicting with one.

**Comment by tastybento** [comment]
@Disorbs Any luck?

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#11
