### ISSUE TITLE
Bug with /is biomes

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#582]
This bug was reported to me from 3 different french servers.

It seems it happens when protection range is over 100.

When a player change the biome of his island, sometimes it works fine (20%), or it don't work. In this case, there are 3 "types" of bug :
1. The biome changed only in a 100*100 blocks area (even if the protection range is, i.e., 250).
2. The biome changed on all the island but with a chunk-sized grid pattern (plains, new biome, plains, new biome, ...)
3. The biome changed on all the island but with a block-sized grid pattern

If you didn't understand what I said (as it is hard to explain), ask for more infos, i'll try to explain it better.

**Comment by tastybento** [comment]
Have a look in SetBiome.java and see if you can see a bug - I can't right now. The biome change loop operates on the whole island area, not just the protection area, so the protection area comment makes me wary. It does 10,000 blocks per second. In more recent servers, players must not only log out and log back in, but the server must unload the chunks before the biome changes. Maybe there is some caching going on...

**Comment by Poslovitch** [comment]
I'll investigate. Maybe should we force the chunk reloading?

**Comment by tastybento** [comment]
If there is a player in the area, you cannot force the chunk to reload. This was possible with 1.7.9 but started to break in 1.8 and was removed from the API by md5.

**Comment by Poslovitch** [comment]
This is problematical :/
I don't have much idea on how to fix it... I'll try to see on other plugins using biomes

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#9
