### ISSUE TITLE
Schematic CPU

### ISSUE THREAD

**Issue by Leugiim0815** [tastybento/askyblock#587]
Hello tastybento,

i have a big problem with the askyblock plugin on my server, i send you here the timings, you can see that the schematic single task the cpu over 1.000 is, do you have a idea how i can fix that?
https://timings.spigotmc.org/?url=dipibavowe

Greetings from germany!
- leugiim

**Comment by tastybento** [comment]
Hi!

Your schematic is taking 500ms (1/2 second) to paste. How big is it? Maybe it is too big.

**Comment by Leugiim0815** [comment]
Hello,

it's the default schematic

**Comment by tastybento** [comment]
So, is there a noticeable lag when you start a new island to other players? Just because the % is high doesn't mean its a problem. The % for ASkyBlock as a whole is low.
