### ISSUE TITLE
Add option to desactivate challenges

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#588]
Like "useEconomy" or "useMinishop"

**Comment by tastybento** [comment]
This is already possible using permissions.

**Comment by Poslovitch** [comment]
Yes, but like the minishop it looks more «clean»

**Comment by tastybento** [comment]
Okay, if you want to add it. :-)

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#8
