### ISSUE TITLE
Flying disabled at Team island

### ISSUE THREAD

**Issue by Tyloonie** [tastybento/askyblock#589]
Hi,

The fly permission is super awesome, however it only works on the players own island. If the player is in a team and working on someone else's island, they are not able to use the flying permission - which sucks.

Could you add an option that allows people with the "askyblock.islandfly" permission to also fly on the team islands? Else it makes no sense to have access to the fly - it will force people to play alone.

Best wishes

**Comment by tastybento** [comment]
When you say on a team, do you mean coop? Or actually on a team?

**Comment by Tyloonie** [comment]
On an actual team accomplished by /is invite. But could you enable flying both for coop and a team?

**Comment by tastybento** [comment]
I can't replicate this sorry - team members and coop members are already able to fly if they are on a team or coop island. Double check the players have the askyblock.islandfly permission and also double check they are definitely team members of the island. (Do /asadmin info for example).

**Comment by Tyloonie** [comment]
Seems to work now. Maybe my dumb friend who tested it did not know how to fly? xD Sorry to waste your time.

**Comment by tastybento** [comment]
There is a different bug that is fixed in 3.0.6.1 that was stopping flying in some situations. Maybe that caused it.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#7
