### ISSUE TITLE
Add island setting to allow/disallow visitors to fly on an island

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#590]
Even if visitors don't have the fly option, a player may be able to give them the ability to fly while visiting.

**Comment by ZacMalone16** [comment]
Could their be an option to make this automatic? To clear this up, if Surx has askyblock.othersmayfly then whomever warps/tpas/homes to Surx's island is put into automatic fly. :)

**Comment by tastybento** [comment]
That could be an option, yes.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#6
