### ISSUE TITLE
Option to disable tooltips formatter

### ISSUE THREAD

**Issue by DJRwi** [tastybento/askyblock#591]
I hate auto new lines

**Comment by Poslovitch** [comment]
What are you talking about?

**Comment by tastybento** [comment]
I think he's talking about the chop command. It fixed the line length to 20 or something. It was before we introduced the newline character | in descriptions. I agree that it'd be good to remove it and replace with just |'s in the descriptions.

**Comment by Poslovitch** [comment]
I think so

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#4

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#5
