### ISSUE TITLE
Display /is & /asadmin help as a GUI

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#593]
This will be enabled by a config option (but will be true by default).

It will display a GUI that will display all arguments. 
When clicking on an icon, this will suggest it to the player (so it will open chat and write "/is go", in example)

**Comment by tastybento** [comment]
For /is, how would this be different from the cp GUI?

**Comment by tastybento** [comment]
Also, tab complete provides suggestions on the command line.

**Comment by Poslovitch** [comment]
The cp will be remade in the Panels rewrite, so I'll have a look at this moment

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#2
