### ISSUE TITLE
Prolbem with growing up of plants

### ISSUE THREAD

**Issue by Gartentrulla** [tastybento/askyblock#596]
dear tastybento,
since a few days we have the problem,that carrots, seed, gras, potatos end so on dosn't grow. Not in all direktions, but in someone. I don't know since what time the Problem starts.
If you can help me to fix it I would very pleased.
My Server is: mein-paradies.your-nuke.de If you have time, I like to Show you what I mean.

Sorry for my bad english, I'm german.
With best regards
your Gartentrulla

**Comment by Poslovitch** [comment]
So, I came to his server.

He tried using bonemeal on seeds on a wet farmland : it wasn't working. Oddly, seeds next to this block were grown.
After that, he tried on a dry farmland : it worked.

I asked him if he didn't update any plugins : he sayd nothing has been changed.

That's it for my "after-visit report"

**Comment by Gartentrulla** [comment]
good evening,
here is the list of plugins we have on the spielewelt:
This is a List of all Plugins:

LinksOnSigns
MOTDManager
FrameProtect
WorldEdit
OnlyProxyJoin
Essentials
LogBlock
AutoMessage
Heads
WorldBorder
WeatherGod
ProtocolLib
WorldGuard
RogueParkour
EssentialsProtect
Steel
EditableSign
PermissionsEx
EssentialsAntiBuild
FishingPlus
Vault
Trampolin
oreGeneratorRevolution
EssentialsSpawn
Lores
BungeeTabListPlus
Herochat
TTT
TNTRun
LWC
1vs1
FwdMsgChanger
uCars
Citizens
ASkyBlock
InsanityRun
Craftbook
ServerSigns
HerochatBungeeBridgeBukkit
ChestShop
Multiverse-Core
DeathCube
Shopkeepers
HeavySpleef
Bedwars
HolograpficDisplays

all of them are working since over 1 year. 
the Trouble ist, i don't know, when the Problem starts.

Thank you for your help

With best regards
your Gartentrulla (I'm female)

**Comment by Gartentrulla** [comment]
good morning,
thank you very much for your help and the notice that a plugin could be make the problem. Yes it was a plugin: bedwars  made by MineHome.
I checked older Versions of Minecraft and so i could find which one made the Problem, but I don't know how to fix it. Maybe the progger of MineHome can help.

Thanks a lot.
With best regards your Gartentrulla
