### ISSUE TITLE
[Request] Ocean Biome and Mob limit adjustment

### ISSUE THREAD

**Issue by Kritex** [tastybento/askyblock#599]
- I think more biome (Ocean, etc.) should be added to plugin. The Reason is new farming techniques and supply will be gathered in this way. 

- Mob limits are having an issue. Limits in config are not working properly. (Version V3.0.5.4)

**Comment by SaitDev** [comment]
3.0.5.4 doesnt have island mob limit. Its just mob limit in a chunk.
Use newest version https://www.spigotmc.org/resources/askyblock.1220/

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#80
