### ISSUE TITLE
[Request] Island Chat

### ISSUE THREAD

**Issue by Kritex** [tastybento/askyblock#600]
- A feature that you can speak to people only on the island. To sum up, when i enter an island, i will be able to speak with other people only on the island with a command;

- /islandtalk, /istalk, /it    Island talk between party and trust members on an island

**Comment by SaitDev** [comment]
for island party, Isnt it `/island teamchat` ?

**Comment by ChiefMoneyBags** [comment]
i think he means a per island chat channel. so i can be a visitor on an island and talk specifically with other players on that island. team chat is only members of your own island.

**Comment by Kritex** [comment]
@ChiefMoneyBags Yes, exactly.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#79
