### ISSUE TITLE
A whole lot of bugs

### ISSUE THREAD

**Issue by TheWranger** [tastybento/askyblock#601]
1. Snow deals acid damage, therefore making snowy islands a non-existant thing.
2. If a player resets their island in a non-AcidIsland world, their inventory won't be reset with them.
3. The island fly system seems buggy as when players teleport to their island from another world, they cannot fly.

Version: Latest of everything.

**Comment by tastybento** [comment]
I'll look at these. For #2 are you using a per world inventory plugin?

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#78
