### ISSUE TITLE
Island size not upgrading (askyblock.island.range.<number>)

### ISSUE THREAD

**Issue by cloakfox** [tastybento/askyblock#602]
Hello,

I am currently selling the option for my users to upgrade their island size from 150x150 to for example 200x200. The standard size is 150. So by giving them the permission askyblock.island.range.200
Should effectively upgrade their island by 50x50. Except this does not work on already created islands. It only works if you create a new island.

I am currently using ASkyblock V3.0.5.4
On PaperSpigot 1.8.8

Skype: cloakfox (from the netherlands)

**Comment by cloakfox** [comment]
Max distance is set at 350 in my config file.

**Comment by Poslovitch** [comment]
First of all, You should update to 3.0.6.1 ;)

**Comment by cloakfox** [comment]
There is nothing in the changelogs/update notes that indicates this issue is fixed in versions after 3.0.5.4
Updating is also genuinely a pain in the ass, since I have to redo my configs each config.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#77
