### ISSUE TITLE
Permission for no hunger on islands

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#63]
It would be great a permission like askyblock.nohunger for vips to hunger bar don't decrease on islands (I saw it in another skyblock plugin)

**Comment by RobiRami** [comment]
Added this in this commit:
https://github.com/RobiRami/acidisland/commit/a91eff0dc2bd28e449d749db9abc1273c784228c

**Comment by tastybento** [comment]
Done.
