### ISSUE TITLE
[Bug] /asadmin tp Appearing

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#66]
When I go to a player's island using /asadmin tp user I always appear in the player's nether portal so I go to the nether (I have to break the portal quickly to go to their islands)

**Comment by tastybento** [comment]
This is true, but only if you are in creative mode. If you are not, you will be able to step out of the portal.

**Comment by YellowZaki** [comment]
oh, and could you enable it in creative mode?

**Comment by tastybento** [comment]
All I can do is teleport you elsewhere on the island. I'll look into doing that.

**Comment by tastybento** [comment]
Changed in V2.9.6.
