### ISSUE TITLE
[Enhancement] Decimal numbers for blockvalues

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#67]
I would like to set decimal blockvalues to calculate the island level because using integers is not exact.
The total island level would be only integers.
PD: I dont know how to user labels here

**Comment by tastybento** [comment]
This is not needed because you can change the level cost. Set it to 1000 (or 10000) instead of 100 and you can still use integers.

For example:

# Value of one island level. Default 100. 
levelcost: 1000

blocks:

  ACACIA_STAIRS: 1

Acacia stairs are now worth 0.1 compared to before.

**Comment by YellowZaki** [comment]
Thanks a lot, I didn't understand the parameter "levelcost:"
