### ISSUE TITLE
Biome reset when user with biomes perm leave the island

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#69]
In my server, VIP users have the perms to change their biomes and they can live with other users (being leaders), change their biome and leave the island. So I would like that when an island leader who has the perm to change biomes use /is makeleader user, the biome of the island get reset to the default biome.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#73
