### ISSUE TITLE
Some permission is not working

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#76]
Max homes - acidisland.island.maxhomes.<number>
    Max team members - acidisland.team.maxsize.<number>
    Initial island protection size - acidisland.island.range.<number> 

that Permission is not working, even though i already give the player permission

**Comment by tastybento** [comment]
Sorry, I can replicate this issue. I just tested and they all work find. Did you remember to reload permissions after you set them for the player?

acidisland.island.maxhomes.4 - gave player 4 homes
acidisland.team.maxsize.28 - gave the player a team size of 28
acidisland.island.range.300 - gave player max range when they reset island.
