### ISSUE TITLE
restart limit is reset when player gets invited to other team

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#77]
it would be best if when a player join another island it give player 1 restart instead of reset it al

**Comment by tastybento** [comment]
Sorry, I don't understand. Can you explain in another way?

**Comment by fikry13** [comment]
Player lost their island restart ability after they use all of their restart ability. But when they join an island, or get invited to an island, their restart ability is reset.

**Comment by tastybento** [comment]
So, you want it so that when they join another island, their island restart ability is reset. Ok.

**Comment by tastybento** [comment]
Should be in V2.9.6.
