### ISSUE TITLE
Add automated integration testing

### ISSUE THREAD

**Issue by jaxzin** [tastybento/askyblock#80]
So I'm going to look into adding the automated integration testing we discussed at the Silicon Valley Minecraft meetup on Aug 29, 2015.  I've got the server jars (using the spigot BuildTools.jar, but that only builds the 1.8.8 version of craftbukkit and spigot jars.  How do I recreate the older versions that are referenced in your pom.xml on the `master` branch?

**Comment by tastybento** [comment]
You can use Build Tools to build everything from 1.8 using java -jar BuildTools.jar --rev <version>, e.g., java -jar BuildTools.jar --rev 1.8.
For 1.7.9, you have to find a download site, or I can share it with you via dropbox.

**Comment by tastybento** [comment]
Time to close!
