### ISSUE TITLE
[Bug] Bad biome changing

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/askyblock#83]
When I change the biome of my island, there is a space of my island where the biome changing havent taken effect, and out of the island is the rest of the biome. Is like the biome is displaced 8 blocks diagonally from a corner of the island

**Comment by tastybento** [comment]
Teleport to somewhere else, like another world, so that the chunks are unloaded from the server, then teleport back. Is the biome set then? The biome is only set when the chunks are loaded.

**Comment by YellowZaki** [comment]
Thats not the problem. Part of the changed biome is out of the island (in the near island) Is like the biome is not well placed, it is displaced being bad placed in respect the island area. If you dont understand the issue I will post a photo

**Comment by tastybento** [comment]
Sorry, I don't understand the layout. Could you post a diagram? ASkyBlock updates the biome of every block inside the island space when the chunks are loaded. If one area is not changing biome then something must be stopping it for some reason.

**Comment by YellowZaki** [comment]
Then I will post the diagram.
Part of the biome is out of the island. The part of the biome which is missing on the island, is out of the island.

**Comment by YellowZaki** [comment]
![biomes](https://cloud.githubusercontent.com/assets/13599841/9631057/a4630d48-517e-11e5-8e17-8433ce391656.png)

**Comment by tastybento** [comment]
Thanks! EXCELLENT DIAGRAM!
Okay, I know what's going on. The biome setting is being done by chunk (16x16 blocks). Let me look into if there's a way to do it better.

**Comment by tastybento** [comment]
In your world, what are your island and protection distances?

**Comment by tastybento** [comment]
Fixed in 2.9.6.5 by commit 7e7ae2d9701ce1d7e0f4786892578c305245d0dc
