### ISSUE TITLE
Owned Island Dissapeared when doing /acid purge unowned

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#86]
The title says it all. and sometimes i see on console when plugin says that a player doesnt have an island bit he actualy does and plugin says something about fixing it, why is that happening?

**Comment by tastybento** [comment]
Ooh. There's actually no reason to ever run that command now and I'm going to remove it from the admin list. It was a very specialized command that was to fix an issue where islands were not being deleted properly a while back. Out of interest, why did you run it? The best command for removing unused islands is just /acid purge.

To answer your second question - what version of the plugin are you using? If it's the latest, it should fix all players who have mismatched data when they log in. The reason why this can happen is usually around server crashes preventing the islands.yml file from saving. There will be improvements in the next version to preserve islands.yml.

If you have some specific console error you are concerned about post it and I'll tell you what it means.

**Comment by fikry13** [comment]
I run it just for fun actually, i thought it can reduce server memory usage and such.

okay thanks, i will check if that happens in the future, last time it hapens it was version 2.9.5.

**Comment by xXBarchticXx** [comment]
Yo tasty just a suggestion but maybe you can fix it by adding the islands in islands.yml in realtime and then reloading it? Possibly every few minutes it does it?
