### ISSUE TITLE
Add ability to remove minishop

### ISSUE THREAD

**Issue by xXBarchticXx** [tastybento/askyblock#90]
Basically I want this since I have my own shop gui plugin that is extremely advanced (not downtalking your plugin just has more features) and I do not want to use the minishop.

**Comment by tastybento** [comment]
This is possible via permissions. Just give your default group the negative permission
 -askyblock.island.minishop

**Comment by xXBarchticXx** [comment]
Would this remove the item from the gui?

**Comment by tastybento** [comment]
It removes the mini shop from the game for those players. The command /is ms is removed and they don't see it at all.

**Comment by xXBarchticXx** [comment]
I mean from the controlpanel gui?

**Comment by tastybento** [comment]
Just edit controlpanel.yml and remove it.
