### ISSUE TITLE
Island are random lost

### ISSUE THREAD

**Issue by xion87** [tastybento/askyblock#92]
I got a lot of complain where player with island they dont have their islland anymore, and /is command it make create a new one instead, (their old island still exist example in top list or warp if setted) and for i fix if he is lucy (warp exist or other team got coordinates) i have to reset the owner again for fix, i think is a uuid issue or similiar, i am using a dedicated server in offline mode with bungeecord in offline mode, please do something.... :(

**Comment by xion87** [comment]
also i noticed some island are lost, other are just been overwriten on it

**Comment by tastybento** [comment]
If the player uses a name with mixed case, then this can happen. The offline server creates a UUID based on the user name, so Mike is different to mike.

**Comment by xion87** [comment]
is not a mixed name issue... user told me that he never loged with different name, same for all user that lost island

**Comment by tastybento** [comment]
Try the latest version. I added a lot of safety features around saving of islands.yml. It now saves when islands are made and every 5 minutes. If the server is crashing for some reason, or was not shutdown properly the older versions did not save islands.yml, so that could cause the lost islands.

**Comment by xion87** [comment]
mmm i just shutdown forced 2 days ago... so it can be that... i wi try (same it happened llike 2-3 times

**Comment by xion87** [comment]
also i just noticed that i got 210 unowned island, there is a way for recovery these?...

**Comment by tastybento** [comment]
You may want to wait a while after you run the latest version. What will happen is that as players log in it will try and sync up their island to the unowned island. You can then remove unowned island by doing /asadmin purge unowned. However, I recommend you do a full backup beforehand.
