### ISSUE TITLE
Item frames are damaged by creeper explosions even if allowcreepergriefing=false

### ISSUE THREAD

**Issue by NxDs** [tastybento/askyblock#94]

**Comment by NxDs** [comment]
Correction, the mob griefing for other users is not working with item frames only.

**Comment by tastybento** [comment]
Hey - I'm sorry, I can't understand this ticket. Can you close it or expand what the problem is?

**Comment by NxDs** [comment]
Yeah sorry I was unclear.
We set the config option allowcreepergriefing to false and now the players can't grief other player's islands as expected. The problem is that the griefers are able to break itenframes with creeper explosions and this means that item frames are somehow not protected by that option unlike all the other blocks.

**Comment by tastybento** [comment]
Ah, okay. So when allowcreepergriefing = false, the island is protected, but item frames are still damaged by creeper explosions. Understood. I can work on that.

**Comment by NxDs** [comment]
Exactly, thanks and sorry for the non-clarity of my first post...

**Comment by tastybento** [comment]
Fixed in 82d28fcd09373eb54ba9c5e221e22b2828aebb9d.

**Comment by NxDs** [comment]
Thanks a lot.
