### ISSUE TITLE
Nether Island for the start in Acidisland_Nether 

### ISSUE THREAD

**Issue by Karpatz** [tastybento/askyblock#96]
Hi i have a issue

When we start with a custom nether island in the nether, the island is not considered a true in the island.yml because these islands appear in the acidisland world not in the Acidisland_nether. we can't do /is go /is sethome etc ..it's said "you are not in your island") The loot of greenhouse whith the bone meal doesn t work with this start. Im using the last version of the plugins with spigot 1.8.3.

**Comment by tastybento** [comment]
I see that sethome isn't working. I'll find out why and fix it.

**Comment by tastybento** [comment]
Island level is also not targeting the nether island.

**Comment by tastybento** [comment]
Coop wasn't working too. Fixed all of the above. Checking for other potential issues.

**Comment by Karpatz** [comment]
The warps sign doesnt work , And when they build a nether portal in the nether, to go to the "partner" island the interface always open .

**Comment by tastybento** [comment]
Confirmed that warp signs don't work.

I don't understand your second point. When I make a portal and go through it, I appear correctly on the overworld island. What do you mean "the interface always open"? Which interface?

**Comment by tastybento** [comment]
Warp signs fixed. New jar here: https://github.com/tastybento/askyblock/releases/tag/V2.9.6.8

**Comment by Karpatz** [comment]
The gui interface with the acidisland menu.

**Comment by tastybento** [comment]
So, you mean that when a player goes through the portal, they see the control panel menu? Can you share your config.yml?
I will publish an AcidIsland version once I've worked out this problem.

**Comment by Karpatz** [comment]
Yes for this issue , with the nether island, When they goes trought the portal, they see the control panel  when they arrive at the overworld island , but if they create an another portal in the overworld island, it work.

The config file:
https://www.dropbox.com/s/nhszft5renwoymw/acidconfig.yml?dl=0

**Comment by Karpatz** [comment]
Hi no idea when you'll upgrade the plugin? Cause i really want this feature ! ^^

**Comment by tastybento** [comment]
I need to check out your config file. For some reason I missed your comment. I will look at it soon.

**Comment by tastybento** [comment]
I've fixed the issue, but just one comment. In your config.yml file you have this:

````   # Immediately teleport player to their island (home 1 if it exists) when 
   # entering the world
   immediateteleport: true
````
Most servers don't need this and it will interfere with portals joining up, so I recommend it is made false.

**Comment by tastybento** [comment]
I plan to release this weekend.

**Comment by Karpatz** [comment]
Ok thx a lot , and great work ! y'r awesome ! ^^

**Comment by Karpatz** [comment]
The issue is resolved with the new version of the plugins Thx ^^ but Greenhouse doesn't work in the Nether, bone meal is consumed but they are no loot in the greenhouse.
