### ISSUE TITLE
Source code maven bug

### ISSUE THREAD

**Issue by Nawiks** [tastybento/askyblock#97]
Hi, I love ASkyblock its a nice plugin.
I want to modify it to add shortcuts, but when I want to compile the source code with maven I obtain errors, impossible to correct :

Project build error: 'dependencies.dependency.systemPath' for spigotmc.org:spigot.1.8.3:jar must specify an absolute path but is /Users/ben/serverJars/spigot-1.8.3.jar

And similar for:

- spigot-1.8.4.jar
- craftbukkit-1.7.9-R0.3-20140705.002733-4.jar
- spigot-1.8.jar
- HeroChat.jar
- spigot-1.8.6.jar
- spigot-1649.jar

And I also have :

- Missing artifact bukkit.org:craftbukkit:jar:1.7.9 
and :
- Missing artifact spigotmc.org:spigot.1.8.4:jar:1.8.4
- Missing artifact spigotmc.org:spigot.1.8.6:jar:1.8.6
- Missing artifact spigotmc.org:spigot-1.8:jar:1.8
- Missing artifact spigotmc.org:spigot.1.8.3:jar:1.8.3
- Missing artifact spigotmc.org:spigot-1649:jar:1.7.10
- Missing artifact org.dthielke:Herochat:jar:5.6.7

Please help me ! :( I really want modify it to adapt it to my server
Sorry I do not speak English very well, I am french :)
Thanks you !

**Comment by tastybento** [comment]
These files are minecraft server jar files and cannot be distributed. You can build all the 1.8.x ones using BuildTools from the Spigot web site. You will have to find the others yourself somewhere...
For Herochat - there is a maven repository, but I found it unreliable. You can download the jar yourself and point to it by editing the pom.xml.

**Comment by Nawiks** [comment]
But how I can create a specific version of 1.8 with buildtools? I obtains all the time 1.8.8.
Thanks

**Comment by Nawiks** [comment]
And I do not manage to modify the pom.xml later I full all the time of error, you can explain to me how can it be done please ?
Thanks you

**Comment by tastybento** [comment]
Build tools instructions are here (https://www.spigotmc.org/wiki/buildtools/) to make a specific version, you do for example:
````java -jar BuildTools.jar --rev 1.8.3````

BUT if you are going to run 1.8.8 only and these changes are just for you, you can hack the code so you do not need these jars. You can remove the every folder in the nms package except for fallback and v1_8_R3. Then remove the dependencies from the pom.

**Comment by Nawiks** [comment]
Yes i Write :

java -jar BuildTools.jar --rev 1.8.6

And i receive in the console :

Attempting to build version: '1.8.6' use --rev <version> to override

 Everything works well but at the end i obtain 1.8.8 version of spigot ans bukkit...
What is the problem please ?

And if i get for example 1.8.6 craftbukkit how i can set it in the pom.xml ?

And for your last post, how i can remove the dependencies from the pom.xml ?

Please help me :(
Thanks you

**Comment by Nawiks** [comment]
Ok i delete all folder in the nms package except fallback and v1_8_R3.
And i want remove the dependencies and add Bukkit 1.8.8 from the pom.xml
I write in the pom.xml : 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.wasteofplastic</groupId>
	<artifactId>askyblock</artifactId>
	<packaging>jar</packaging>

	<name>com.wasteofplastic</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<server.jars>/Users/ben/serverJars</server.jars>
	</properties>

	<build>
		<defaultGoal>clean package install</defaultGoal>
		<finalName>askyblock</finalName>
		<sourceDirectory>${basedir}/src/</sourceDirectory>
		<resources>
			<resource>
				<targetPath>.</targetPath>
				<filtering>true</filtering>
				<directory>${basedir}</directory>
				<includes>
					<include>*.yml</include>
				</includes>
			</resource>
			<resource>
				<targetPath>schematics</targetPath>
				<filtering>false</filtering>
				<directory>${basedir}/schematics</directory>
				<includes>
					<include>*.schematic</include>
				</includes>
			</resource>
			<resource>
				<targetPath>locale</targetPath>
				<filtering>false</filtering>
				<directory>${basedir}/locale</directory>
				<includes>
					<include>*.yml</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>schematic</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>net.milkbowl.vault</groupId>
			<artifactId>VaultAPI</artifactId>
			<version>1.5</version>
		</dependency>
		<dependency>
			<groupId>com.sk89q</groupId>
			<artifactId>worldguard</artifactId>
			<version>LATEST</version>
			<scope>provided</scope>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>bukkit.org</groupId>
			<artifactId>craftbukkit</artifactId>
			<scope>system</scope>
			<systemPath>C:\Users\antonin\.m2\repository\org\bukkit\craftbukkit\bukkit-1.8.8-R0.1-SNAPSHOT.jar</systemPath>
			<version>1.8.8</version>
		</dependency>
		<dependency>
			<groupId>org.dthielke</groupId>
			<artifactId>Herochat</artifactId>
			<scope>system</scope>
			<systemPath>C:\Users\antonin\.m2\repository\org\dthielke\Herochat-5.6.7.jar</systemPath>
			<version>5.6.7</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>vault-repo</id>
			<url>http://nexus.theyeticave.net/content/repositories/pub_releases</url>
		</repository>
		<repository>
			<id>worldedit-repo</id>
			<url>http://maven.sk89q.com/repo/</url>
		</repository>
	</repositories>
	<version>2.9.6.8</version>
</project>


But when i compile i obtain this error : 

[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[31,29] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[31,42] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[32,29] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[36,5] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[36,32] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[37,5] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[40,47] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[42,33] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[42,73] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[62,12] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[62,40] error: cannot find symbol
[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.235 s
[INFO] Finished at: 2015-10-03T13:26:34+02:00
[INFO] Final Memory: 16M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project askyblock: Compilation failure: Compila
tion failure:
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[8,35] error: package net.minecraft.server.v1_7_R4
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[9,35] error: package net.minecraft.server.v1_7_R4
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[10,35] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[11,35] error: package net.minecraft.server.v1_7_R
4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[15,37] error: package org.bukkit.craftbukkit.v1_7
_R4 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[16,47] error: package org.bukkit.craftbukkit.v1_7
_R4.inventory does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[21,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[22,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\NMSAbstraction.java:[5,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_7_R4\NMSHandler.java:[57,29] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\NMSAbstraction.java:[17,29] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\org\jnbt\ByteArrayTag.java:
[9,40] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\panels\SettingsPanel.java:[8,26] error: package net.md_5.bungee.api does not e
xist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[66,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[67,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[68,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[69,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[83,41] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[28,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[29,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[575,40] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[1119,30] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\Schematic.java:[1119,61] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\BannerBlock.java:[16,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\BannerBlock.java:[17,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[217,38] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[226,43] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[239,36] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[344,36] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\IslandBlock.java:[350,57] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\schematics\BannerBlock.java:[86,36] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\org\jnbt\ByteTag.java:[9,35
] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[7,35] error: package net.minecraft.server.v1_8_R2
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[8,35] error: package net.minecraft.server.v1_8_R2
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[9,35] error: package net.minecraft.server.v1_8_R2
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[10,35] error: package net.minecraft.server.v1_8_R
2 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[11,35] error: package net.minecraft.server.v1_8_R
2 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[15,37] error: package org.bukkit.craftbukkit.v1_8
_R2 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[16,47] error: package org.bukkit.craftbukkit.v1_8
_R2.inventory does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[21,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[22,15] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R2\NMSHandler.java:[43,29] error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\org\jnbt\IntTag.java:[9,34]
 error: cannot find symbol
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[7,35] error: package net.minecraft.server.v1_8_R1
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[8,35] error: package net.minecraft.server.v1_8_R1
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[9,35] error: package net.minecraft.server.v1_8_R1
 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[10,35] error: package net.minecraft.server.v1_8_R
1 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[11,35] error: package net.minecraft.server.v1_8_R
1 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[15,37] error: package org.bukkit.craftbukkit.v1_8
_R1 does not exist
[ERROR] \Users\antonin\Desktop\askyblock-2.9.6.8\src\com\wasteofplastic\askybloc
k\nms\v1_8_R1\NMSHandler.java:[16,47] error: package org.bukkit.craftbukkit.v1_8
_R1.inventory does not exist

and : 

[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.wasteofplastic:askyblock:jar:2.9.6.8
[WARNING] 'dependencies.dependency.systemPath' for bukkit.org:craftbukkit:jar sh
ould use a variable instead of hard-coded path C:\user\antonin\.m2\repository
\org\bukkit\craftbukkit\bukkit-1.8.8-R0.1-SNAPSHOT.jar @ line 78, column 16
[WARNING]  'dependencies.dependency.systemPath' for org.dthielke:Herochat:jar sho
uld use a variable instead of hard-coded path C:\user\antonin\.m2\repository
\org\dthielke\Herochat-5.6.7.jar @ line 85, column 16
[WARNING]

Thanks you for help

**Comment by Nawiks** [comment]
Oh no sorry ! I managed to run everything, but I do not find where to modify the inventory of challenges in the code. Where is it please? Thanks you

**Comment by tastybento** [comment]
Challenges are in the file challenges.yml. That is where you can change and add challenges.
